unit BacupUnit;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TBackupForm=class(TForm)
    DbList: TComboBox;
    SpeedButton1: TSpeedButton;
    SaveDialog1: TSaveDialog;
    procedure FormCreate(Sender : TObject);
    procedure SpeedButton1Click(Sender : TObject);
    procedure DbListChange(Sender : TObject);
    procedure _PROC_00A06855(Sender : TObject);
    procedure _PROC_00A06897(Sender : TObject);
    procedure _PROC_00A068E9(Sender : TObject);
    procedure _PROC_00A06985(Sender : TObject);
    procedure _PROC_00A06990(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  BackupForm: TBackupForm;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TBackupForm.FormCreate(Sender : TObject);
begin
(*
00A0660C   C3                     ret

*)
end;

procedure TBackupForm.SpeedButton1Click(Sender : TObject);
begin
(*
00A066F0   55                     push    ebp
00A066F1   8BEC                   mov     ebp, esp
00A066F3   33C9                   xor     ecx, ecx
00A066F5   51                     push    ecx
00A066F6   51                     push    ecx
00A066F7   51                     push    ecx
00A066F8   51                     push    ecx
00A066F9   51                     push    ecx
00A066FA   51                     push    ecx
00A066FB   51                     push    ecx
00A066FC   53                     push    ebx
00A066FD   56                     push    esi
00A066FE   57                     push    edi
00A066FF   8BD8                   mov     ebx, eax
00A06701   33C0                   xor     eax, eax
00A06703   55                     push    ebp

* Possible String Reference to: 'È?ŸÔˇÎ√_^[ãÂ]√'
|
00A06704   683868A000             push    $00A06838
00A06709   64FF30                 push    dword ptr fs:[eax]
00A0670C   648920                 mov     fs:[eax], esp

* Reference to control TBackupForm.SaveDialog1 : TSaveDialog
|
00A0670F   8B83F8020000           mov     eax, [ebx+$02F8]
00A06715   8B10                   mov     edx, [eax]

* Possible reference to virtual method TSaveDialog.OFFS_3C
|
00A06717   FF523C                 call    dword ptr [edx+$3C]
00A0671A   84C0                   test    al, al
00A0671C   0F84D3000000           jz      00A067F5
00A06722   33C0                   xor     eax, eax
00A06724   55                     push    ebp

* Possible String Reference to: 'È‚÷Ôˇ∏Ëh†'
|
00A06725   68E167A000             push    $00A067E1
00A0672A   64FF30                 push    dword ptr fs:[eax]
00A0672D   648920                 mov     fs:[eax], esp
00A06730   8D55FC                 lea     edx, [ebp-$04]

* Reference to TDataModule_Main instance
|
00A06733   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A06738   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0673A   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099846C
|
00A0673D   E82A1DF9FF             call    0099846C
00A06742   8B55FC                 mov     edx, [ebp-$04]

* Reference to TDataModule_Main instance
|
00A06745   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0674A   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
00A0674C   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009927E8
|
00A0674F   E894C0F8FF             call    009927E8

* Possible String Reference to: 'BACKUP DATABASE ['
|
00A06754   685068A000             push    $00A06850
00A06759   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TBackupForm.DbList : TComboBox
|
00A0675C   8B83F0020000           mov     eax, [ebx+$02F0]

* Reference to: Controls.Proc_0094B1D8
|
00A06762   E8714AF4FF             call    0094B1D8
00A06767   FF75F0                 push    dword ptr [ebp-$10]

* Possible String Reference to: '] TO  DISK = N''
|
00A0676A   686C68A000             push    $00A0686C
00A0676F   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TBackupForm.SaveDialog1 : TSaveDialog
|
00A06772   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to : TSaveDialog._PROC_00943540()
|
00A06778   E8C3CDF3FF             call    00943540
00A0677D   FF75EC                 push    dword ptr [ebp-$14]

* Possible String Reference to: '' WITH  INIT ,  NOUNLOAD ,  NAME = 
|                                N''
|
00A06780   688468A000             push    $00A06884
00A06785   8D55E8                 lea     edx, [ebp-$18]

* Reference to control TBackupForm.DbList : TComboBox
|
00A06788   8B83F0020000           mov     eax, [ebx+$02F0]

* Reference to: Controls.Proc_0094B1D8
|
00A0678E   E8454AF4FF             call    0094B1D8
00A06793   FF75E8                 push    dword ptr [ebp-$18]

* Possible String Reference to: ' backup',  NOSKIP ,  STATS = 10,  N
|                                OFORMAT'
|
00A06796   68B468A000             push    $00A068B4
00A0679B   8D45F4                 lea     eax, [ebp-$0C]
00A0679E   BA07000000             mov     edx, $00000007

* Reference to: System.Proc_00904BAC
|
00A067A3   E804E4EFFF             call    00904BAC
00A067A8   8B55F4                 mov     edx, [ebp-$0C]
00A067AB   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.Proc_009050F4
|
00A067AE   E841E9EFFF             call    009050F4
00A067B3   8B55F8                 mov     edx, [ebp-$08]

* Reference to TDataModule_Main instance
|
00A067B6   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A067BB   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
00A067BD   8B405C                 mov     eax, [eax+$5C]
00A067C0   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TADOCommand.OFFS_38
|
00A067C2   FF5138                 call    dword ptr [ecx+$38]
00A067C5   8D55E4                 lea     edx, [ebp-$1C]

* Reference to TDataModule_Main instance
|
00A067C8   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A067CD   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
00A067CF   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009920D0
|
00A067D2   E8F9B8F8FF             call    009920D0
00A067D7   33C0                   xor     eax, eax
00A067D9   5A                     pop     edx
00A067DA   59                     pop     ecx
00A067DB   59                     pop     ecx
00A067DC   648910                 mov     fs:[eax], edx
00A067DF   EB14                   jmp     00A067F5
00A067E1   E9E2D6EFFF             jmp     00903EC8

* Possible String Reference to: 'Unknown Error. Backup Failed.'
|
00A067E6   B8E868A000             mov     eax, $00A068E8

* Reference to : TMessageForm._PROC_00944368()
|
00A067EB   E878DBF3FF             call    00944368

* Reference to: System.Proc_009042F4
|
00A067F0   E8FFDAEFFF             call    009042F4

****** END
|
00A067F5   33C0                   xor     eax, eax
00A067F7   5A                     pop     edx
00A067F8   59                     pop     ecx
00A067F9   59                     pop     ecx
00A067FA   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[ãÂ]√'
|
00A067FD   683F68A000             push    $00A0683F
00A06802   8D45E4                 lea     eax, [ebp-$1C]

* Reference to: System.Proc_0090690C
|
00A06805   E80201F0FF             call    0090690C
00A0680A   8D45E8                 lea     eax, [ebp-$18]

* Reference to: System.Proc_00904834
|
00A0680D   E822E0EFFF             call    00904834
00A06812   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.Proc_00904834
|
00A06815   E81AE0EFFF             call    00904834
00A0681A   8D45F0                 lea     eax, [ebp-$10]

* Reference to: System.Proc_00904834
|
00A0681D   E812E0EFFF             call    00904834
00A06822   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.Proc_00904834
|
00A06825   E80AE0EFFF             call    00904834
00A0682A   8D45F8                 lea     eax, [ebp-$08]
00A0682D   BA02000000             mov     edx, $00000002

* Reference to: System.Proc_00904F70
|
00A06832   E839E7EFFF             call    00904F70
00A06837   C3                     ret

00A06838   E93FD9EFFF             jmp     0090417C
00A0683D   EBC3                   jmp     00A06802

****** END
|
00A0683F   5F                     pop     edi
00A06840   5E                     pop     esi
00A06841   5B                     pop     ebx
00A06842   8BE5                   mov     esp, ebp
00A06844   5D                     pop     ebp
00A06845   C3                     ret

*)
end;

procedure TBackupForm.DbListChange(Sender : TObject);
begin
(*
00A06908   55                     push    ebp
00A06909   8BEC                   mov     ebp, esp
00A0690B   6A00                   push    $00
00A0690D   53                     push    ebx
00A0690E   8BD8                   mov     ebx, eax
00A06910   33C0                   xor     eax, eax
00A06912   55                     push    ebp

* Possible String Reference to: 'È#ÿÔˇÎ[Y]√êUãÏ3¿UhÖi†'
|
00A06913   685469A000             push    $00A06954
00A06918   64FF30                 push    dword ptr fs:[eax]
00A0691B   648920                 mov     fs:[eax], esp
00A0691E   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TBackupForm.DbList : TComboBox
|
00A06921   8B83F0020000           mov     eax, [ebx+$02F0]

* Reference to: Controls.Proc_0094B1D8
|
00A06927   E8AC48F4FF             call    0094B1D8
00A0692C   837DFC00               cmp     dword ptr [ebp-$04], +$00
00A06930   0F95C2                 setnz   dl

* Reference to control TBackupForm.SpeedButton1 : TSpeedButton
|
00A06933   8B83F4020000           mov     eax, [ebx+$02F4]
00A06939   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TSpeedButton.OFFS_64
|
00A0693B   FF5164                 call    dword ptr [ecx+$64]
00A0693E   33C0                   xor     eax, eax
00A06940   5A                     pop     edx
00A06941   59                     pop     ecx
00A06942   59                     pop     ecx
00A06943   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√êUãÏ3¿UhÖi†'
|
00A06946   685B69A000             push    $00A0695B
00A0694B   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
00A0694E   E8E1DEEFFF             call    00904834
00A06953   C3                     ret

00A06954   E923D8EFFF             jmp     0090417C
00A06959   EBF0                   jmp     00A0694B

****** END
|
00A0695B   5B                     pop     ebx
00A0695C   59                     pop     ecx
00A0695D   5D                     pop     ebp
00A0695E   C3                     ret

*)
end;

procedure TBackupForm._PROC_00A06855(Sender : TObject);
begin
(*
00A06855   50                     push    eax
00A06856   20444154               and     [ecx+eax*2+$54], al
00A0685A   41                     inc     ecx
00A0685B   42                     inc     edx
00A0685C   41                     inc     ecx
00A0685D   53                     push    ebx
00A0685E   45                     inc     ebp
00A0685F   205B00                 and     [ebx+$00], bl
00A06862   0000                   add     [eax], al

*)
end;

procedure TBackupForm._PROC_00A06897(Sender : TObject);
begin
(*
00A06897   4E                     dec     esi
00A06898   4C                     dec     esp
00A06899   4F                     dec     edi
00A0689A   41                     inc     ecx
00A0689B   44                     inc     esp
00A0689C   202C20                 and     [eax], ch
00A0689F   204E41                 and     [esi+$41], cl
00A068A2   4D                     dec     ebp
00A068A3   45                     inc     ebp
00A068A4   203D204E2700           and     [$00274E20], bh
00A068AA   0000                   add     [eax], al

*)
end;

procedure TBackupForm._PROC_00A068E9(Sender : TObject);
begin
(*
00A068E9   6E                     outsb
00A068EA   6B6E6F77               imul    ebp, [esi+$6F], $77
00A068EE   6E                     outsb
00A068EF   204572                 and     [ebp+$72], al
00A068F2   726F                   jb      00A06963
00A068F4   722E                   jb      00A06924
00A068F6   204261                 and     [edx+$61], al
00A068F9   636B75                 arpl    [ebx+$75], bp
00A068FC   7020                   jo      00A0691E
00A068FE   46                     inc     esi
00A068FF   61                     popa
00A06900   696C65642E000000       imul    ebp, [ebp+$64], $0000002E
00A06908   55                     push    ebp
00A06909   8BEC                   mov     ebp, esp
00A0690B   6A00                   push    $00
00A0690D   53                     push    ebx
00A0690E   8BD8                   mov     ebx, eax
00A06910   33C0                   xor     eax, eax
00A06912   55                     push    ebp

* Possible String Reference to: 'È#ÿÔˇÎ[Y]√êUãÏ3¿UhÖi†'
|
00A06913   685469A000             push    $00A06954
00A06918   64FF30                 push    dword ptr fs:[eax]
00A0691B   648920                 mov     fs:[eax], esp
00A0691E   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TBackupForm.DbList : TComboBox
|
00A06921   8B83F0020000           mov     eax, [ebx+$02F0]

* Reference to: Controls.Proc_0094B1D8
|
00A06927   E8AC48F4FF             call    0094B1D8
00A0692C   837DFC00               cmp     dword ptr [ebp-$04], +$00
00A06930   0F95C2                 setnz   dl

* Reference to control TBackupForm.SpeedButton1 : TSpeedButton
|
00A06933   8B83F4020000           mov     eax, [ebx+$02F4]
00A06939   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TSpeedButton.OFFS_64
|
00A0693B   FF5164                 call    dword ptr [ecx+$64]
00A0693E   33C0                   xor     eax, eax
00A06940   5A                     pop     edx
00A06941   59                     pop     ecx
00A06942   59                     pop     ecx
00A06943   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√êUãÏ3¿UhÖi†'
|
00A06946   685B69A000             push    $00A0695B
00A0694B   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
00A0694E   E8E1DEEFFF             call    00904834
00A06953   C3                     ret

00A06954   E923D8EFFF             jmp     0090417C
00A06959   EBF0                   jmp     00A0694B

****** END
|
00A0695B   5B                     pop     ebx
00A0695C   59                     pop     ecx
00A0695D   5D                     pop     ebp
00A0695E   C3                     ret

00A0695F   90                     nop
00A06960   55                     push    ebp
00A06961   8BEC                   mov     ebp, esp
00A06963   33C0                   xor     eax, eax
00A06965   55                     push    ebp

* Possible String Reference to: 'ÈÚ◊ÔˇÎ¯]√ã¿É-X!°'
|
00A06966   688569A000             push    $00A06985
00A0696B   64FF30                 push    dword ptr fs:[eax]
00A0696E   648920                 mov     fs:[eax], esp
00A06971   FF055821A100           inc     dword ptr [$00A12158]
00A06977   33C0                   xor     eax, eax
00A06979   5A                     pop     edx
00A0697A   59                     pop     ecx
00A0697B   59                     pop     ecx
00A0697C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-X!°'
|
00A0697F   688C69A000             push    $00A0698C
00A06984   C3                     ret

*)
end;

procedure TBackupForm._PROC_00A06985(Sender : TObject);
begin
(*
00A06985   E9F2D7EFFF             jmp     0090417C
00A0698A   EBF8                   jmp     00A06984
00A0698C   5D                     pop     ebp
00A0698D   C3                     ret

*)
end;

procedure TBackupForm._PROC_00A06990(Sender : TObject);
begin
(*
00A06990   832D5821A10001         sub     dword ptr [$00A12158], +$01
00A06997   C3                     ret

*)
end;

end.