unit CharacterMarkUnit;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TCharacterMarkForm=class(TForm)
    Panel1: TPanel;
    SpeedButton2: TSpeedButton;
    Characters: TListBox;
    BitBtn1: TBitBtn;
    SpeedButton1: TSpeedButton;
    procedure SpeedButton2Click(Sender : TObject);
    procedure BitBtn1Click(Sender : TObject);
    procedure SpeedButton1Click(Sender : TObject);
    procedure CharactersClick(Sender : TObject);
    procedure CharactersKeyPress(Sender : TObject);
    procedure CharactersDblClick(Sender : TObject);
    procedure _PROC_009FA7F4(Sender : TObject);
    procedure _PROC_009FA8A7(Sender : TObject);
    procedure _PROC_009FA9FC(Sender : TObject);
    procedure _PROC_009FAA2C(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  CharacterMarkForm: TCharacterMarkForm;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TCharacterMarkForm.SpeedButton2Click(Sender : TObject);
begin
(*
009FA708   56                     push    esi
009FA709   8BF0                   mov     esi, eax

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA70B   8B86F8020000           mov     eax, [esi+$02F8]
009FA711   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00D4
|
009FA713   FF92D4000000           call    dword ptr [edx+$00D4]

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA719   8B86F8020000           mov     eax, [esi+$02F8]

* Reference to field TListBox.OFFS_0218
|
009FA71F   8B8018020000           mov     eax, [eax+$0218]

* Possible String Reference to: 'CharactersList.txt'
|
009FA725   BA3CA79F00             mov     edx, $009FA73C
009FA72A   8B08                   mov     ecx, [eax]
009FA72C   FF5174                 call    dword ptr [ecx+$74]
009FA72F   5E                     pop     esi
009FA730   C3                     ret

*)
end;

procedure TCharacterMarkForm.BitBtn1Click(Sender : TObject);
begin
(*
009FA750   55                     push    ebp
009FA751   8BEC                   mov     ebp, esp
009FA753   6A00                   push    $00
009FA755   53                     push    ebx
009FA756   56                     push    esi
009FA757   8BD8                   mov     ebx, eax
009FA759   33C0                   xor     eax, eax
009FA75B   55                     push    ebp

* Possible String Reference to: 'é‘™ðÿëð^[Y]Ã‹ÀU‹ìQV‰Uü‹ð‹EüèÎ¤ðÿ3ÀU
|                                hl¨Ÿ'
|
009FA75C   68E6A79F00             push    $009FA7E6
009FA761   64FF30                 push    dword ptr fs:[eax]
009FA764   648920                 mov     fs:[eax], esp

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA767   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to field TListBox.OFFS_0218
|
009FA76D   8B8018020000           mov     eax, [eax+$0218]
009FA773   8B10                   mov     edx, [eax]
009FA775   FF5214                 call    dword ptr [edx+$14]
009FA778   85C0                   test    eax, eax
009FA77A   7E4C                   jle     009FA7C8

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA77C   8B83F8020000           mov     eax, [ebx+$02F8]
009FA782   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FA784   FF92C8000000           call    dword ptr [edx+$00C8]
009FA78A   85C0                   test    eax, eax
009FA78C   7C30                   jl      009FA7BE

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA78E   8BB3F8020000           mov     esi, [ebx+$02F8]
009FA794   8BC6                   mov     eax, esi
009FA796   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FA798   FF92C8000000           call    dword ptr [edx+$00C8]
009FA79E   8BD0                   mov     edx, eax
009FA7A0   8D4DFC                 lea     ecx, [ebp-$04]

* Reference to field TListBox.OFFS_0218
|
009FA7A3   8B8618020000           mov     eax, [esi+$0218]
009FA7A9   8B30                   mov     esi, [eax]
009FA7AB   FF560C                 call    dword ptr [esi+$0C]
009FA7AE   8B55FC                 mov     edx, [ebp-$04]

* Reference to field TCharacterMarkForm.OFFS_0304
|
009FA7B1   8D8304030000           lea     eax, [ebx+$0304]

* Reference to: System.Proc_00904888
|
009FA7B7   E8CCA0F0FF             call    00904888
009FA7BC   EB12                   jmp     009FA7D0
009FA7BE   33C0                   xor     eax, eax

* Reference to field TCharacterMarkForm.OFFS_024C
|
009FA7C0   89834C020000           mov     [ebx+$024C], eax
009FA7C6   EB08                   jmp     009FA7D0
009FA7C8   33C0                   xor     eax, eax

* Reference to field TCharacterMarkForm.OFFS_024C
|
009FA7CA   89834C020000           mov     [ebx+$024C], eax
009FA7D0   33C0                   xor     eax, eax
009FA7D2   5A                     pop     edx
009FA7D3   59                     pop     ecx
009FA7D4   59                     pop     ecx
009FA7D5   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]Ã‹ÀU‹ìQV‰Uü‹ð‹EüèÎ¤ðÿ3ÀUhl¨Ÿ'
|
009FA7D8   68EDA79F00             push    $009FA7ED
009FA7DD   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009FA7E0   E84FA0F0FF             call    00904834
009FA7E5   C3                     ret

009FA7E6   E99199F0FF             jmp     0090417C
009FA7EB   EBF0                   jmp     009FA7DD

****** END
|
009FA7ED   5E                     pop     esi
009FA7EE   5B                     pop     ebx
009FA7EF   59                     pop     ecx
009FA7F0   5D                     pop     ebp
009FA7F1   C3                     ret

*)
end;

procedure TCharacterMarkForm.SpeedButton1Click(Sender : TObject);
begin
(*
009FA8F8   56                     push    esi
009FA8F9   8BF0                   mov     esi, eax

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA8FB   8B86F8020000           mov     eax, [esi+$02F8]

* Reference to field TListBox.OFFS_0218
|
009FA901   8B8018020000           mov     eax, [eax+$0218]
009FA907   8B10                   mov     edx, [eax]
009FA909   FF5214                 call    dword ptr [edx+$14]
009FA90C   85C0                   test    eax, eax
009FA90E   7E36                   jle     009FA946

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA910   8B86F8020000           mov     eax, [esi+$02F8]
009FA916   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FA918   FF92C8000000           call    dword ptr [edx+$00C8]
009FA91E   85C0                   test    eax, eax
009FA920   7C24                   jl      009FA946

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA922   8B86F8020000           mov     eax, [esi+$02F8]
009FA928   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00E0
|
009FA92A   FF92E0000000           call    dword ptr [edx+$00E0]

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA930   8B86F8020000           mov     eax, [esi+$02F8]

* Reference to field TListBox.OFFS_0218
|
009FA936   8B8018020000           mov     eax, [eax+$0218]

* Possible String Reference to: 'CharactersList.txt'
|
009FA93C   BA50A99F00             mov     edx, $009FA950
009FA941   8B08                   mov     ecx, [eax]
009FA943   FF5174                 call    dword ptr [ecx+$74]
009FA946   5E                     pop     esi
009FA947   C3                     ret

*)
end;

procedure TCharacterMarkForm.CharactersClick(Sender : TObject);
begin
(*
009FA964   53                     push    ebx
009FA965   8BD8                   mov     ebx, eax

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA967   8B83F8020000           mov     eax, [ebx+$02F8]
009FA96D   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FA96F   FF92C8000000           call    dword ptr [edx+$00C8]
009FA975   85C0                   test    eax, eax
009FA977   0F9DC2                 setnl   dl

* Reference to control TCharacterMarkForm.BitBtn1 : TBitBtn
|
009FA97A   8B83FC020000           mov     eax, [ebx+$02FC]
009FA980   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TBitBtn.OFFS_64
|
009FA982   FF5164                 call    dword ptr [ecx+$64]

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA985   8B83F8020000           mov     eax, [ebx+$02F8]
009FA98B   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FA98D   FF92C8000000           call    dword ptr [edx+$00C8]
009FA993   85C0                   test    eax, eax
009FA995   0F9DC2                 setnl   dl

* Reference to control TCharacterMarkForm.SpeedButton1 : TSpeedButton
|
009FA998   8B8300030000           mov     eax, [ebx+$0300]
009FA99E   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TSpeedButton.OFFS_64
|
009FA9A0   FF5164                 call    dword ptr [ecx+$64]
009FA9A3   5B                     pop     ebx
009FA9A4   C3                     ret

*)
end;

procedure TCharacterMarkForm.CharactersKeyPress(Sender : TObject);
begin
(*
009FA9A8   53                     push    ebx
009FA9A9   56                     push    esi
009FA9AA   8BD8                   mov     ebx, eax
009FA9AC   80390D                 cmp     byte ptr [ecx], $0D
009FA9AF   751E                   jnz     009FA9CF

* Reference to control TCharacterMarkForm.BitBtn1 : TBitBtn
|
009FA9B1   8B83FC020000           mov     eax, [ebx+$02FC]
009FA9B7   8B10                   mov     edx, [eax]

* Possible reference to virtual method TBitBtn.OFFS_50
|
009FA9B9   FF5250                 call    dword ptr [edx+$50]
009FA9BC   84C0                   test    al, al
009FA9BE   740F                   jz      009FA9CF

* Reference to control TCharacterMarkForm.BitBtn1 : TBitBtn
|
009FA9C0   8B83FC020000           mov     eax, [ebx+$02FC]
009FA9C6   66BEEBFF               mov     si, $FFEB

* Reference to: System.Proc_00903BE4
|
009FA9CA   E81592F0FF             call    00903BE4
009FA9CF   5E                     pop     esi
009FA9D0   5B                     pop     ebx
009FA9D1   C3                     ret

*)
end;

procedure TCharacterMarkForm.CharactersDblClick(Sender : TObject);
begin
(*
009FA9D4   53                     push    ebx
009FA9D5   56                     push    esi
009FA9D6   8BD8                   mov     ebx, eax

* Reference to control TCharacterMarkForm.BitBtn1 : TBitBtn
|
009FA9D8   8B83FC020000           mov     eax, [ebx+$02FC]
009FA9DE   8B10                   mov     edx, [eax]

* Possible reference to virtual method TBitBtn.OFFS_50
|
009FA9E0   FF5250                 call    dword ptr [edx+$50]
009FA9E3   84C0                   test    al, al
009FA9E5   740F                   jz      009FA9F6

* Reference to control TCharacterMarkForm.BitBtn1 : TBitBtn
|
009FA9E7   8B83FC020000           mov     eax, [ebx+$02FC]
009FA9ED   66BEEBFF               mov     si, $FFEB

* Reference to: System.Proc_00903BE4
|
009FA9F1   E8EE91F0FF             call    00903BE4
009FA9F6   5E                     pop     esi
009FA9F7   5B                     pop     ebx
009FA9F8   C3                     ret

*)
end;

procedure TCharacterMarkForm._PROC_009FA7F4(Sender : TObject);
begin
(*
009FA7F4   55                     push    ebp
009FA7F5   8BEC                   mov     ebp, esp
009FA7F7   51                     push    ecx
009FA7F8   56                     push    esi
009FA7F9   8955FC                 mov     [ebp-$04], edx
009FA7FC   8BF0                   mov     esi, eax
009FA7FE   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.Proc_00904CD4
|
009FA801   E8CEA4F0FF             call    00904CD4
009FA806   33C0                   xor     eax, eax
009FA808   55                     push    ebp
009FA809   686CA89F00             push    $009FA86C
009FA80E   64FF30                 push    dword ptr fs:[eax]
009FA811   648920                 mov     fs:[eax], esp

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA814   8B86F8020000           mov     eax, [esi+$02F8]

* Reference to field TListBox.OFFS_0218
|
009FA81A   8B8018020000           mov     eax, [eax+$0218]
009FA820   8B55FC                 mov     edx, [ebp-$04]
009FA823   8B08                   mov     ecx, [eax]
009FA825   FF5154                 call    dword ptr [ecx+$54]
009FA828   85C0                   test    eax, eax
009FA82A   7D14                   jnl     009FA840

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA82C   8B86F8020000           mov     eax, [esi+$02F8]

* Reference to field TListBox.OFFS_0218
|
009FA832   8B8018020000           mov     eax, [eax+$0218]
009FA838   8B55FC                 mov     edx, [ebp-$04]
009FA83B   8B08                   mov     ecx, [eax]
009FA83D   FF5138                 call    dword ptr [ecx+$38]

* Reference to control TCharacterMarkForm.Characters : TListBox
|
009FA840   8B86F8020000           mov     eax, [esi+$02F8]

* Reference to field TListBox.OFFS_0218
|
009FA846   8B8018020000           mov     eax, [eax+$0218]

* Possible String Reference to: 'CharactersList.txt'
|
009FA84C   BA80A89F00             mov     edx, $009FA880
009FA851   8B08                   mov     ecx, [eax]
009FA853   FF5174                 call    dword ptr [ecx+$74]
009FA856   33C0                   xor     eax, eax
009FA858   5A                     pop     edx
009FA859   59                     pop     ecx
009FA85A   59                     pop     ecx
009FA85B   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^Y]Ã'
|
009FA85E   6873A89F00             push    $009FA873
009FA863   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009FA866   E8C99FF0FF             call    00904834
009FA86B   C3                     ret

009FA86C   E90B99F0FF             jmp     0090417C
009FA871   EBF0                   jmp     009FA863

****** END
|
009FA873   5E                     pop     esi
009FA874   59                     pop     ecx
009FA875   5D                     pop     ebp
009FA876   C3                     ret

*)
end;

procedure TCharacterMarkForm._PROC_009FA8A7(Sender : TObject);
begin
(*
009FA8A7   F8                     clc
009FA8A8   0200                   add     al, byte ptr [eax]
009FA8AA   008B80180200           add     [ebx+$21880], cl
009FA8B0   00BAE4A89F00           add     [edx+$9FA8E4], bh
009FA8B6   8B08                   mov     ecx, [eax]
009FA8B8   FF5168                 call    dword ptr [ecx+$68]
009FA8BB   EB0E                   jmp     009FA8CB
009FA8BD   8B83F8020000           mov     eax, [ebx+$02F8]
009FA8C3   8B10                   mov     edx, [eax]
009FA8C5   FF92D4000000           call    dword ptr [edx+$00D4]
009FA8CB   33D2                   xor     edx, edx
009FA8CD   8B83FC020000           mov     eax, [ebx+$02FC]
009FA8D3   8B08                   mov     ecx, [eax]
009FA8D5   FF5164                 call    dword ptr [ecx+$64]
009FA8D8   5B                     pop     ebx
009FA8D9   C3                     ret

*)
end;

procedure TCharacterMarkForm._PROC_009FA9FC(Sender : TObject);
begin
(*
009FA9FC   55                     push    ebp
009FA9FD   8BEC                   mov     ebp, esp
009FA9FF   33C0                   xor     eax, eax
009FAA01   55                     push    ebp

* Possible String Reference to: 'éV—ðÿëø]Ã‹Àƒ-À ¡'
|
009FAA02   6821AA9F00             push    $009FAA21
009FAA07   64FF30                 push    dword ptr fs:[eax]
009FAA0A   648920                 mov     fs:[eax], esp
009FAA0D   FF05C020A100           inc     dword ptr [$00A120C0]
009FAA13   33C0                   xor     eax, eax
009FAA15   5A                     pop     edx
009FAA16   59                     pop     ecx
009FAA17   59                     pop     ecx
009FAA18   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-À ¡'
|
009FAA1B   6828AA9F00             push    $009FAA28
009FAA20   C3                     ret

009FAA21   E95697F0FF             jmp     0090417C
009FAA26   EBF8                   jmp     009FAA20

****** END
|
009FAA28   5D                     pop     ebp
009FAA29   C3                     ret

*)
end;

procedure TCharacterMarkForm._PROC_009FAA2C(Sender : TObject);
begin
(*
009FAA2C   832DC020A10001         sub     dword ptr [$00A120C0], +$01
009FAA33   C3                     ret

*)
end;

end.