unit ConnectOptions;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TConnectOptionsForm=class(TForm)
    PageControl1: TPageControl;
    TabSheet1: TTabSheet;
    TabSheet2: TTabSheet;
    SpeedButton1: TSpeedButton;
    Label60: TLabel;
    Label55: TLabel;
    Label53: TLabel;
    Label2: TLabel;
    Label1: TLabel;
    Edit3: TEdit;
    Edit2: TEdit;
    aliases2: TComboBox;
    Aliases: TComboBox;
    Label61: TLabel;
    ResetCollumnEdit: TEdit;
    Label3: TLabel;
    ResetTableEdit: TEdit;
    CharacterNameCollumnInresttableEdit: TEdit;
    Label4: TLabel;
    SaveConfigButton: TBitBtn;
    BitBtn1: TBitBtn;
    DatasourceName: TEdit;
    procedure LoadConfigButtonClick(Sender : TObject);
    procedure SaveConfigButtonClick(Sender : TObject);
    procedure FormShow(Sender : TObject);
    procedure SpeedButton1Click(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure aliases2Change(Sender : TObject);
    procedure Edit3KeyPress(Sender : TObject);
    procedure DatasourceNameChange(Sender : TObject);
    procedure _PROC_00A01F39(Sender : TObject);
    procedure _PROC_00A020F3(Sender : TObject);
    procedure _PROC_00A02248(Sender : TObject);
    procedure _PROC_00A02278(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  ConnectOptionsForm: TConnectOptionsForm;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TConnectOptionsForm.LoadConfigButtonClick(Sender : TObject);
begin
(*
00A01CC4   C3                     ret

*)
end;

procedure TConnectOptionsForm.SaveConfigButtonClick(Sender : TObject);
begin
(*
00A01CC8   55                     push    ebp
00A01CC9   8BEC                   mov     ebp, esp
00A01CCB   B904000000             mov     ecx, $00000004
00A01CD0   6A00                   push    $00
00A01CD2   6A00                   push    $00
00A01CD4   49                     dec     ecx
00A01CD5   75F9                   jnz     00A01CD0
00A01CD7   51                     push    ecx
00A01CD8   53                     push    ebx
00A01CD9   8BD8                   mov     ebx, eax
00A01CDB   33C0                   xor     eax, eax
00A01CDD   55                     push    ebp

* Possible String Reference to: 'Èò"ˇÎ÷[ãÂ]√'
|
00A01CDE   68DF1EA000             push    $00A01EDF
00A01CE3   64FF30                 push    dword ptr fs:[eax]
00A01CE6   648920                 mov     fs:[eax], esp
00A01CE9   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TConnectOptionsForm.aliases2 : TComboBox
|
00A01CEC   8B831C030000           mov     eax, [ebx+$031C]

* Reference to: Controls.Proc_0094B1D8
|
00A01CF2   E8E194F4FF             call    0094B1D8
00A01CF7   8B55FC                 mov     edx, [ebp-$04]

* Reference to pointer to GlobalVar_00A12180
|
00A01CFA   A144FEA000             mov     eax, dword ptr [$00A0FE44]

* Reference to: System.Proc_00904888
|
00A01CFF   E8842BF0FF             call    00904888
00A01D04   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TConnectOptionsForm.Edit3 : TEdit
|
00A01D07   8B8314030000           mov     eax, [ebx+$0314]

* Reference to: Controls.Proc_0094B1D8
|
00A01D0D   E8C694F4FF             call    0094B1D8
00A01D12   8B55F8                 mov     edx, [ebp-$08]

* Reference to pointer to GlobalVar_00A12184
|
00A01D15   A1BCFDA000             mov     eax, dword ptr [$00A0FDBC]

* Reference to: System.Proc_00904888
|
00A01D1A   E8692BF0FF             call    00904888
00A01D1F   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TConnectOptionsForm.Edit2 : TEdit
|
00A01D22   8B8318030000           mov     eax, [ebx+$0318]

* Reference to: Controls.Proc_0094B1D8
|
00A01D28   E8AB94F4FF             call    0094B1D8
00A01D2D   8B55F4                 mov     edx, [ebp-$0C]

* Reference to pointer to GlobalVar_00A12188
|
00A01D30   A140FEA000             mov     eax, dword ptr [$00A0FE40]

* Reference to: System.Proc_00904888
|
00A01D35   E84E2BF0FF             call    00904888
00A01D3A   8D55F0                 lea     edx, [ebp-$10]

* Reference to control TConnectOptionsForm.Aliases : TComboBox
|
00A01D3D   8B8320030000           mov     eax, [ebx+$0320]

* Reference to: Controls.Proc_0094B1D8
|
00A01D43   E89094F4FF             call    0094B1D8
00A01D48   8B55F0                 mov     edx, [ebp-$10]

* Reference to pointer to GlobalVar_00A1218C
|
00A01D4B   A188FBA000             mov     eax, dword ptr [$00A0FB88]

* Reference to: System.Proc_00904888
|
00A01D50   E8332BF0FF             call    00904888
00A01D55   8D55EC                 lea     edx, [ebp-$14]

* Reference to control TConnectOptionsForm.DatasourceName : TEdit
|
00A01D58   8B8344030000           mov     eax, [ebx+$0344]

* Reference to: Controls.Proc_0094B1D8
|
00A01D5E   E87594F4FF             call    0094B1D8
00A01D63   8B55EC                 mov     edx, [ebp-$14]

* Reference to pointer to GlobalVar_00A1217C
|
00A01D66   A1ACFAA000             mov     eax, dword ptr [$00A0FAAC]

* Reference to: System.Proc_00904888
|
00A01D6B   E8182BF0FF             call    00904888

* Reference to TDataModule_Main instance
|
00A01D70   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A01D75   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A01D77   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
00A01D7A   E83D48F8FF             call    009865BC

* Possible String Reference to: 'Provider=MSDASQL.1;Password='
|
00A01D7F   68F41EA000             push    $00A01EF4

* Reference to pointer to GlobalVar_00A12184
|
00A01D84   A1BCFDA000             mov     eax, dword ptr [$00A0FDBC]
00A01D89   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Persist Security Info=True;User ID
|                                ='
|
00A01D8B   681C1FA000             push    $00A01F1C

* Reference to pointer to GlobalVar_00A12188
|
00A01D90   A140FEA000             mov     eax, dword ptr [$00A0FE40]
00A01D95   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Data Source='
|
00A01D97   684C1FA000             push    $00A01F4C

* Reference to pointer to GlobalVar_00A1217C
|
00A01D9C   A1ACFAA000             mov     eax, dword ptr [$00A0FAAC]
00A01DA1   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Initial Catalog='
|
00A01DA3   68641FA000             push    $00A01F64

* Reference to pointer to GlobalVar_00A1218C
|
00A01DA8   A188FBA000             mov     eax, dword ptr [$00A0FB88]
00A01DAD   FF30                   push    dword ptr [eax]

* Reference to pointer to GlobalVar_00A12174
|
00A01DAF   A178FCA000             mov     eax, dword ptr [$00A0FC78]
00A01DB4   BA08000000             mov     edx, $00000008

* Reference to: System.Proc_00904BAC
|
00A01DB9   E8EE2DF0FF             call    00904BAC

* Possible String Reference to: 'Provider=MSDASQL.1;Password='
|
00A01DBE   68F41EA000             push    $00A01EF4

* Reference to pointer to GlobalVar_00A12184
|
00A01DC3   A1BCFDA000             mov     eax, dword ptr [$00A0FDBC]
00A01DC8   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Persist Security Info=True;User ID
|                                ='
|
00A01DCA   681C1FA000             push    $00A01F1C

* Reference to pointer to GlobalVar_00A12188
|
00A01DCF   A140FEA000             mov     eax, dword ptr [$00A0FE40]
00A01DD4   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Data Source='
|
00A01DD6   684C1FA000             push    $00A01F4C

* Reference to pointer to GlobalVar_00A1217C
|
00A01DDB   A1ACFAA000             mov     eax, dword ptr [$00A0FAAC]
00A01DE0   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Initial Catalog='
|
00A01DE2   68641FA000             push    $00A01F64

* Reference to pointer to GlobalVar_00A12180
|
00A01DE7   A144FEA000             mov     eax, dword ptr [$00A0FE44]
00A01DEC   FF30                   push    dword ptr [eax]

* Reference to pointer to GlobalVar_00A12178
|
00A01DEE   A114FFA000             mov     eax, dword ptr [$00A0FF14]
00A01DF3   BA08000000             mov     edx, $00000008

* Reference to: System.Proc_00904BAC
|
00A01DF8   E8AF2DF0FF             call    00904BAC
00A01DFD   8D45E8                 lea     eax, [ebp-$18]

* Reference to pointer to GlobalVar_00A12174
|
00A01E00   8B1578FCA000           mov     edx, [$00A0FC78]
00A01E06   8B12                   mov     edx, [edx]

* Reference to: System.Proc_009050F4
|
00A01E08   E8E732F0FF             call    009050F4
00A01E0D   8B55E8                 mov     edx, [ebp-$18]

* Reference to TDataModule_Main instance
|
00A01E10   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A01E15   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A01E17   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_00998488
|
00A01E1A   E86966F9FF             call    00998488

* Reference to control TConnectOptionsForm.TabSheet2 : TTabSheet
|
00A01E1F   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to field TTabSheet.OFFS_0210
|
00A01E25   80B81002000000         cmp     byte ptr [eax+$0210], $00
00A01E2C   7460                   jz      00A01E8E
00A01E2E   8D55E4                 lea     edx, [ebp-$1C]

* Reference to ConnectOptionsForm
|
00A01E31   A11C21A100             mov     eax, dword ptr [$00A1211C]

* Reference to field ConnectOptionsForm.OFFS_0330
|
00A01E36   8B8030030000           mov     eax, [eax+$0330]

* Reference to: Controls.Proc_0094B1D8
|
00A01E3C   E89793F4FF             call    0094B1D8
00A01E41   8B55E4                 mov     edx, [ebp-$1C]

* Reference to pointer to GlobalVar_00A1216C
|
00A01E44   A14CFDA000             mov     eax, dword ptr [$00A0FD4C]

* Reference to: System.Proc_00904888
|
00A01E49   E83A2AF0FF             call    00904888
00A01E4E   8D55E0                 lea     edx, [ebp-$20]

* Reference to ConnectOptionsForm
|
00A01E51   A11C21A100             mov     eax, dword ptr [$00A1211C]

* Reference to field ConnectOptionsForm.OFFS_0334
|
00A01E56   8B8034030000           mov     eax, [eax+$0334]

* Reference to: Controls.Proc_0094B1D8
|
00A01E5C   E87793F4FF             call    0094B1D8
00A01E61   8B55E0                 mov     edx, [ebp-$20]

* Reference to pointer to GlobalVar_00A12170
|
00A01E64   A194FBA000             mov     eax, dword ptr [$00A0FB94]

* Reference to: System.Proc_00904888
|
00A01E69   E81A2AF0FF             call    00904888
00A01E6E   8D55DC                 lea     edx, [ebp-$24]

* Reference to ConnectOptionsForm
|
00A01E71   A11C21A100             mov     eax, dword ptr [$00A1211C]

* Reference to field ConnectOptionsForm.OFFS_0328
|
00A01E76   8B8028030000           mov     eax, [eax+$0328]

* Reference to: Controls.Proc_0094B1D8
|
00A01E7C   E85793F4FF             call    0094B1D8
00A01E81   8B55DC                 mov     edx, [ebp-$24]

* Reference to pointer to GlobalVar_00A12168
|
00A01E84   A1D8FFA000             mov     eax, dword ptr [$00A0FFD8]

* Reference to: System.Proc_00904888
|
00A01E89   E8FA29F0FF             call    00904888

* Reference to: Unit_00A096BC.Proc_00A0B6D4
|
00A01E8E   E841980000             call    00A0B6D4
00A01E93   84C0                   test    al, al
00A01E95   7518                   jnz     00A01EAF
00A01E97   6A10                   push    $10

* Possible String Reference to: 'Error!'
|
00A01E99   B9781FA000             mov     ecx, $00A01F78

* Possible String Reference to: 'Cannot Write ini file'
|
00A01E9E   BA801FA000             mov     edx, $00A01F80

* Reference to TApplication instance
|
00A01EA3   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A01EA8   8B00                   mov     eax, [eax]

* Reference to : TApplication._PROC_0096C968()
|
00A01EAA   E8B9AAF6FF             call    0096C968
00A01EAF   33C0                   xor     eax, eax
00A01EB1   5A                     pop     edx
00A01EB2   59                     pop     ecx
00A01EB3   59                     pop     ecx
00A01EB4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[ãÂ]√'
|
00A01EB7   68E61EA000             push    $00A01EE6
00A01EBC   8D45DC                 lea     eax, [ebp-$24]
00A01EBF   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904858
|
00A01EC4   E88F29F0FF             call    00904858
00A01EC9   8D45E8                 lea     eax, [ebp-$18]

* Reference to: System.Proc_00904F58
|
00A01ECC   E88730F0FF             call    00904F58
00A01ED1   8D45EC                 lea     eax, [ebp-$14]
00A01ED4   BA05000000             mov     edx, $00000005

* Reference to: System.Proc_00904858
|
00A01ED9   E87A29F0FF             call    00904858
00A01EDE   C3                     ret

00A01EDF   E99822F0FF             jmp     0090417C
00A01EE4   EBD6                   jmp     00A01EBC

****** END
|
00A01EE6   5B                     pop     ebx
00A01EE7   8BE5                   mov     esp, ebp
00A01EE9   5D                     pop     ebp
00A01EEA   C3                     ret

*)
end;

procedure TConnectOptionsForm.FormShow(Sender : TObject);
begin
(*
00A01F98   C3                     ret

*)
end;

procedure TConnectOptionsForm.SpeedButton1Click(Sender : TObject);
begin
(*
00A01F9C   55                     push    ebp
00A01F9D   8BEC                   mov     ebp, esp
00A01F9F   33C9                   xor     ecx, ecx
00A01FA1   51                     push    ecx
00A01FA2   51                     push    ecx
00A01FA3   51                     push    ecx
00A01FA4   51                     push    ecx
00A01FA5   8945FC                 mov     [ebp-$04], eax
00A01FA8   33C0                   xor     eax, eax
00A01FAA   55                     push    ebp

* Possible String Reference to: 'Èè ˇÎÎãÂ]√'
|
00A01FAB   68E820A000             push    $00A020E8
00A01FB0   64FF30                 push    dword ptr fs:[eax]
00A01FB3   648920                 mov     fs:[eax], esp
00A01FB6   8D55F8                 lea     edx, [ebp-$08]

* Reference to ConnectOptionsForm
|
00A01FB9   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TConnectOptionsForm.DatasourceName : TEdit
|
00A01FBC   8B8044030000           mov     eax, [eax+$0344]

* Reference to: Controls.Proc_0094B1D8
|
00A01FC2   E81192F4FF             call    0094B1D8
00A01FC7   837DF800               cmp     dword ptr [ebp-$08], +$00
00A01FCB   0F84E4000000           jz      00A020B5
00A01FD1   8D55F4                 lea     edx, [ebp-$0C]

* Reference to ConnectOptionsForm
|
00A01FD4   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TConnectOptionsForm.Edit2 : TEdit
|
00A01FD7   8B8018030000           mov     eax, [eax+$0318]

* Reference to: Controls.Proc_0094B1D8
|
00A01FDD   E8F691F4FF             call    0094B1D8
00A01FE2   837DF400               cmp     dword ptr [ebp-$0C], +$00
00A01FE6   0F84C9000000           jz      00A020B5
00A01FEC   33C0                   xor     eax, eax
00A01FEE   55                     push    ebp

* Possible String Reference to: 'ÈÃ ˇÈzˇˇˇj'
|
00A01FEF   68AB20A000             push    $00A020AB
00A01FF4   64FF30                 push    dword ptr fs:[eax]
00A01FF7   648920                 mov     fs:[eax], esp
00A01FFA   8D55F0                 lea     edx, [ebp-$10]

* Reference to ConnectOptionsForm
|
00A01FFD   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TConnectOptionsForm.DatasourceName : TEdit
|
00A02000   8B8044030000           mov     eax, [eax+$0344]

* Reference to: Controls.Proc_0094B1D8
|
00A02006   E8CD91F4FF             call    0094B1D8
00A0200B   8B45F0                 mov     eax, [ebp-$10]

* Reference to ConnectOptionsForm
|
00A0200E   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TConnectOptionsForm.Aliases : TComboBox
|
00A02011   8B9220030000           mov     edx, [edx+$0320]

* Reference to field TComboBox.OFFS_023C
|
00A02017   8B923C020000           mov     edx, [edx+$023C]

* Reference to: Unit_00A096BC.Proc_00A0C040
|
00A0201D   E81EA00000             call    00A0C040
00A02022   33C0                   xor     eax, eax
00A02024   5A                     pop     edx
00A02025   59                     pop     ecx
00A02026   59                     pop     ecx
00A02027   648910                 mov     fs:[eax], edx

****** FINALLY
|
00A0202A   68CD20A000             push    $00A020CD

* Reference to ConnectOptionsForm
|
00A0202F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TConnectOptionsForm.Aliases : TComboBox
|
00A02032   8B8020030000           mov     eax, [eax+$0320]

* Reference to field TComboBox.OFFS_023C
|
00A02038   8B903C020000           mov     edx, [eax+$023C]

* Reference to ConnectOptionsForm
|
00A0203E   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TConnectOptionsForm.aliases2 : TComboBox
|
00A02041   8B801C030000           mov     eax, [eax+$031C]

* Reference to field TComboBox.OFFS_023C
|
00A02047   8B803C020000           mov     eax, [eax+$023C]
00A0204D   8B08                   mov     ecx, [eax]
00A0204F   FF5108                 call    dword ptr [ecx+$08]

* Reference to ConnectOptionsForm
|
00A02052   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TConnectOptionsForm.Aliases : TComboBox
|
00A02055   8B8020030000           mov     eax, [eax+$0320]
00A0205B   33D2                   xor     edx, edx

* Reference to: Controls.Proc_0094B208
|
00A0205D   E8A691F4FF             call    0094B208

* Reference to ConnectOptionsForm
|
00A02062   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TConnectOptionsForm.aliases2 : TComboBox
|
00A02065   8B801C030000           mov     eax, [eax+$031C]
00A0206B   33D2                   xor     edx, edx

* Reference to: Controls.Proc_0094B208
|
00A0206D   E89691F4FF             call    0094B208

* Reference to ConnectOptionsForm
|
00A02072   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TConnectOptionsForm.Aliases : TComboBox
|
00A02075   8B8020030000           mov     eax, [eax+$0320]

* Reference to field TComboBox.OFFS_023C
|
00A0207B   8B803C020000           mov     eax, [eax+$023C]
00A02081   8B10                   mov     edx, [eax]
00A02083   FF5214                 call    dword ptr [edx+$14]
00A02086   85C0                   test    eax, eax
00A02088   7E20                   jle     00A020AA

* Reference to ConnectOptionsForm
|
00A0208A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TConnectOptionsForm.Aliases : TComboBox
|
00A0208D   8B8020030000           mov     eax, [eax+$0320]
00A02093   B201                   mov     dl, $01
00A02095   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TComboBox.OFFS_64
|
00A02097   FF5164                 call    dword ptr [ecx+$64]

* Reference to ConnectOptionsForm
|
00A0209A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TConnectOptionsForm.aliases2 : TComboBox
|
00A0209D   8B801C030000           mov     eax, [eax+$031C]
00A020A3   B201                   mov     dl, $01
00A020A5   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TComboBox.OFFS_64
|
00A020A7   FF5164                 call    dword ptr [ecx+$64]
00A020AA   C3                     ret

00A020AB   E9CC20F0FF             jmp     0090417C
00A020B0   E97AFFFFFF             jmp     00A0202F
00A020B5   6A00                   push    $00

* Possible String Reference to: 'Warning!'
|
00A020B7   B9F420A000             mov     ecx, $00A020F4

* Possible String Reference to: 'You must set Dasource and DBuser fi
|                                rst!'
|
00A020BC   BA0021A000             mov     edx, $00A02100

* Reference to TApplication instance
|
00A020C1   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A020C6   8B00                   mov     eax, [eax]

* Reference to : TApplication._PROC_0096C968()
|
00A020C8   E89BA8F6FF             call    0096C968

****** END
|
00A020CD   33C0                   xor     eax, eax
00A020CF   5A                     pop     edx
00A020D0   59                     pop     ecx
00A020D1   59                     pop     ecx
00A020D2   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: 'ãÂ]√'
|
00A020D5   68EF20A000             push    $00A020EF
00A020DA   8D45F0                 lea     eax, [ebp-$10]
00A020DD   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904858
|
00A020E2   E87127F0FF             call    00904858
00A020E7   C3                     ret

00A020E8   E98F20F0FF             jmp     0090417C
00A020ED   EBEB                   jmp     00A020DA

****** END
|
00A020EF   8BE5                   mov     esp, ebp
00A020F1   5D                     pop     ebp
00A020F2   C3                     ret

*)
end;

procedure TConnectOptionsForm.FormCreate(Sender : TObject);
begin
(*

* Reference to field TConnectOptionsForm.OFFS_01F8
|
00A02128   C680F801000001         mov     byte ptr [eax+$01F8], $01
00A0212F   C3                     ret

*)
end;

procedure TConnectOptionsForm.aliases2Change(Sender : TObject);
begin
(*
00A02130   55                     push    ebp
00A02131   8BEC                   mov     ebp, esp
00A02133   6A00                   push    $00
00A02135   53                     push    ebx
00A02136   8BD8                   mov     ebx, eax
00A02138   33C0                   xor     eax, eax
00A0213A   55                     push    ebp
00A0213B   687C21A000             push    $00A0217C
00A02140   64FF30                 push    dword ptr fs:[eax]
00A02143   648920                 mov     fs:[eax], esp
00A02146   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TConnectOptionsForm.Aliases : TComboBox
|
00A02149   8B8320030000           mov     eax, [ebx+$0320]

* Reference to: Controls.Proc_0094B1D8
|
00A0214F   E88490F4FF             call    0094B1D8
00A02154   837DFC00               cmp     dword ptr [ebp-$04], +$00
00A02158   0F95C2                 setnz   dl

* Reference to control TConnectOptionsForm.SaveConfigButton : TBitBtn
|
00A0215B   8B833C030000           mov     eax, [ebx+$033C]
00A02161   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TBitBtn.OFFS_64
|
00A02163   FF5164                 call    dword ptr [ecx+$64]
00A02166   33C0                   xor     eax, eax
00A02168   5A                     pop     edx
00A02169   59                     pop     ecx
00A0216A   59                     pop     ecx
00A0216B   648910                 mov     fs:[eax], edx

****** FINALLY
|
00A0216E   688321A000             push    $00A02183
00A02173   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
00A02176   E8B926F0FF             call    00904834
00A0217B   C3                     ret

00A0217C   E9FB1FF0FF             jmp     0090417C
00A02181   EBF0                   jmp     00A02173

****** END
|
00A02183   5B                     pop     ebx
00A02184   59                     pop     ecx
00A02185   5D                     pop     ebp
00A02186   C3                     ret

*)
end;

procedure TConnectOptionsForm.Edit3KeyPress(Sender : TObject);
begin
(*
00A02188   56                     push    esi
00A02189   8BF0                   mov     esi, eax
00A0218B   80390D                 cmp     byte ptr [ecx], $0D
00A0218E   751E                   jnz     00A021AE

* Reference to control TConnectOptionsForm.BitBtn1 : TBitBtn
|
00A02190   8B8640030000           mov     eax, [esi+$0340]
00A02196   8B10                   mov     edx, [eax]

* Possible reference to virtual method TBitBtn.OFFS_50
|
00A02198   FF5250                 call    dword ptr [edx+$50]
00A0219B   84C0                   test    al, al
00A0219D   740F                   jz      00A021AE

* Reference to control TConnectOptionsForm.SpeedButton1 : TSpeedButton
|
00A0219F   8B86FC020000           mov     eax, [esi+$02FC]
00A021A5   66BEEBFF               mov     si, $FFEB

* Reference to: System.Proc_00903BE4
|
00A021A9   E8361AF0FF             call    00903BE4
00A021AE   5E                     pop     esi
00A021AF   C3                     ret

*)
end;

procedure TConnectOptionsForm.DatasourceNameChange(Sender : TObject);
begin
(*
00A021B0   55                     push    ebp
00A021B1   8BEC                   mov     ebp, esp
00A021B3   6A00                   push    $00
00A021B5   53                     push    ebx
00A021B6   8BD8                   mov     ebx, eax
00A021B8   33C0                   xor     eax, eax
00A021BA   55                     push    ebp
00A021BB   683D22A000             push    $00A0223D
00A021C0   64FF30                 push    dword ptr fs:[eax]
00A021C3   648920                 mov     fs:[eax], esp
00A021C6   33D2                   xor     edx, edx

* Reference to control TConnectOptionsForm.Aliases : TComboBox
|
00A021C8   8B8320030000           mov     eax, [ebx+$0320]

* Reference to: Controls.Proc_0094B208
|
00A021CE   E83590F4FF             call    0094B208
00A021D3   33D2                   xor     edx, edx

* Reference to control TConnectOptionsForm.aliases2 : TComboBox
|
00A021D5   8B831C030000           mov     eax, [ebx+$031C]

* Reference to: Controls.Proc_0094B208
|
00A021DB   E82890F4FF             call    0094B208
00A021E0   33D2                   xor     edx, edx

* Reference to control TConnectOptionsForm.Aliases : TComboBox
|
00A021E2   8B8320030000           mov     eax, [ebx+$0320]
00A021E8   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TComboBox.OFFS_64
|
00A021EA   FF5164                 call    dword ptr [ecx+$64]
00A021ED   33D2                   xor     edx, edx

* Reference to control TConnectOptionsForm.aliases2 : TComboBox
|
00A021EF   8B831C030000           mov     eax, [ebx+$031C]
00A021F5   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TComboBox.OFFS_64
|
00A021F7   FF5164                 call    dword ptr [ecx+$64]
00A021FA   33D2                   xor     edx, edx

* Reference to control TConnectOptionsForm.SaveConfigButton : TBitBtn
|
00A021FC   8B833C030000           mov     eax, [ebx+$033C]
00A02202   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TBitBtn.OFFS_64
|
00A02204   FF5164                 call    dword ptr [ecx+$64]
00A02207   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TConnectOptionsForm.DatasourceName : TEdit
|
00A0220A   8B8344030000           mov     eax, [ebx+$0344]

* Reference to: Controls.Proc_0094B1D8
|
00A02210   E8C38FF4FF             call    0094B1D8
00A02215   837DFC00               cmp     dword ptr [ebp-$04], +$00
00A02219   0F95C2                 setnz   dl

* Reference to control TConnectOptionsForm.SpeedButton1 : TSpeedButton
|
00A0221C   8B83FC020000           mov     eax, [ebx+$02FC]
00A02222   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TSpeedButton.OFFS_64
|
00A02224   FF5164                 call    dword ptr [ecx+$64]
00A02227   33C0                   xor     eax, eax
00A02229   5A                     pop     edx
00A0222A   59                     pop     ecx
00A0222B   59                     pop     ecx
00A0222C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√UãÏ3¿Uhm"†'
|
00A0222F   684422A000             push    $00A02244
00A02234   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
00A02237   E8F825F0FF             call    00904834
00A0223C   C3                     ret

00A0223D   E93A1FF0FF             jmp     0090417C
00A02242   EBF0                   jmp     00A02234

****** END
|
00A02244   5B                     pop     ebx
00A02245   59                     pop     ecx
00A02246   5D                     pop     ebp
00A02247   C3                     ret

*)
end;

procedure TConnectOptionsForm._PROC_00A01F39(Sender : TObject);
begin
(*
00A01F39   7365                   jnb     00A01FA0
00A01F3B   7220                   jb      00A01F5D
00A01F3D   49                     dec     ecx
00A01F3E   44                     inc     esp
00A01F3F   3D00000000             cmp     eax, $00000000
00A01F44   FFFF                   DB  $FF, $FF  //      
00A01F46   FFFF                   DB  $FF, $FF  //      
00A01F48   0D0000003B             or      eax, $3B000000
00A01F4D   44                     inc     esp
00A01F4E   61                     popa
00A01F4F   7461                   jz      00A01FB2
00A01F51   20536F                 and     [ebx+$6F], dl
00A01F54   7572                   jnz     00A01FC8
00A01F56   63653D                 arpl    [ebp+$3D], sp
00A01F59   0000                   add     [eax], al

00A01F5B   00FF                   add     bh, bh
00A01F5D   FFFF                   DB  $FF, $FF  //      
00A01F5F   FF11                   call    dword ptr [ecx]
00A01F61   0000                   add     [eax], al

00A01F63   003B                   add     [ebx], bh
00A01F65   49                     dec     ecx
00A01F66   6E                     outsb
00A01F67   697469616C204361       imul    esi, [ecx+ebp*2+$61], $6143206C
00A01F6F   7461                   jz      00A01FD2
00A01F71   6C                     insb
00A01F72   6F                     outsd
00A01F73   673D00000045           cmp     eax, $45000000
00A01F79   7272                   jb      00A01FED
00A01F7B   6F                     outsd
00A01F7C   7221                   jb      00A01F9F
00A01F7E   0000                   add     [eax], al

00A01F80   43                     inc     ebx
00A01F81   61                     popa
00A01F82   6E                     outsb
00A01F83   6E                     outsb
00A01F84   6F                     outsd
00A01F85   7420                   jz      00A01FA7
00A01F87   57                     push    edi
00A01F88   7269                   jb      00A01FF3
00A01F8A   7465                   jz      00A01FF1
00A01F8C   20696E                 and     [ecx+$6E], ch
00A01F8F   692066696C65           imul    esp, [eax], $656C6966
00A01F95   0000                   add     [eax], al

00A01F97   00C3                   add     bl, al
00A01F99   8D4000                 lea     eax, [eax+$00]
00A01F9C   55                     push    ebp
00A01F9D   8BEC                   mov     ebp, esp
00A01F9F   33C9                   xor     ecx, ecx
00A01FA1   51                     push    ecx
00A01FA2   51                     push    ecx
00A01FA3   51                     push    ecx
00A01FA4   51                     push    ecx
00A01FA5   8945FC                 mov     [ebp-$04], eax
00A01FA8   33C0                   xor     eax, eax
00A01FAA   55                     push    ebp

* Possible String Reference to: 'Èè ˇÎÎãÂ]√'
|
00A01FAB   68E820A000             push    $00A020E8
00A01FB0   64FF30                 push    dword ptr fs:[eax]
00A01FB3   648920                 mov     fs:[eax], esp
00A01FB6   8D55F8                 lea     edx, [ebp-$08]

* Reference to ConnectOptionsForm
|
00A01FB9   8B45FC                 mov     eax, [ebp-$04]

* Reference to field ConnectOptionsForm.OFFS_0344
|
00A01FBC   8B8044030000           mov     eax, [eax+$0344]

* Reference to: Controls.Proc_0094B1D8
|
00A01FC2   E81192F4FF             call    0094B1D8
00A01FC7   837DF800               cmp     dword ptr [ebp-$08], +$00
00A01FCB   0F84E4000000           jz      00A020B5
00A01FD1   8D55F4                 lea     edx, [ebp-$0C]

* Reference to ConnectOptionsForm
|
00A01FD4   8B45FC                 mov     eax, [ebp-$04]

* Reference to field ConnectOptionsForm.OFFS_0318
|
00A01FD7   8B8018030000           mov     eax, [eax+$0318]

* Reference to: Controls.Proc_0094B1D8
|
00A01FDD   E8F691F4FF             call    0094B1D8
00A01FE2   837DF400               cmp     dword ptr [ebp-$0C], +$00
00A01FE6   0F84C9000000           jz      00A020B5
00A01FEC   33C0                   xor     eax, eax
00A01FEE   55                     push    ebp

* Possible String Reference to: 'ÈÃ ˇÈzˇˇˇj'
|
00A01FEF   68AB20A000             push    $00A020AB
00A01FF4   64FF30                 push    dword ptr fs:[eax]
00A01FF7   648920                 mov     fs:[eax], esp
00A01FFA   8D55F0                 lea     edx, [ebp-$10]

* Reference to ConnectOptionsForm
|
00A01FFD   8B45FC                 mov     eax, [ebp-$04]

* Reference to field ConnectOptionsForm.OFFS_0344
|
00A02000   8B8044030000           mov     eax, [eax+$0344]

* Reference to: Controls.Proc_0094B1D8
|
00A02006   E8CD91F4FF             call    0094B1D8
00A0200B   8B45F0                 mov     eax, [ebp-$10]

* Reference to ConnectOptionsForm
|
00A0200E   8B55FC                 mov     edx, [ebp-$04]

* Reference to field ConnectOptionsForm.OFFS_0320
|
00A02011   8B9220030000           mov     edx, [edx+$0320]
00A02017   8B923C020000           mov     edx, [edx+$023C]

* Reference to: Unit_00A096BC.Proc_00A0C040
|
00A0201D   E81EA00000             call    00A0C040
00A02022   33C0                   xor     eax, eax
00A02024   5A                     pop     edx
00A02025   59                     pop     ecx
00A02026   59                     pop     ecx
00A02027   648910                 mov     fs:[eax], edx

****** FINALLY
|
00A0202A   68CD20A000             push    $00A020CD

* Reference to ConnectOptionsForm
|
00A0202F   8B45FC                 mov     eax, [ebp-$04]

* Reference to field ConnectOptionsForm.OFFS_0320
|
00A02032   8B8020030000           mov     eax, [eax+$0320]
00A02038   8B903C020000           mov     edx, [eax+$023C]

* Reference to ConnectOptionsForm
|
00A0203E   8B45FC                 mov     eax, [ebp-$04]

* Reference to field ConnectOptionsForm.OFFS_031C
|
00A02041   8B801C030000           mov     eax, [eax+$031C]
00A02047   8B803C020000           mov     eax, [eax+$023C]
00A0204D   8B08                   mov     ecx, [eax]
00A0204F   FF5108                 call    dword ptr [ecx+$08]

* Reference to ConnectOptionsForm
|
00A02052   8B45FC                 mov     eax, [ebp-$04]

* Reference to field ConnectOptionsForm.OFFS_0320
|
00A02055   8B8020030000           mov     eax, [eax+$0320]
00A0205B   33D2                   xor     edx, edx

* Reference to: Controls.Proc_0094B208
|
00A0205D   E8A691F4FF             call    0094B208

* Reference to ConnectOptionsForm
|
00A02062   8B45FC                 mov     eax, [ebp-$04]

* Reference to field ConnectOptionsForm.OFFS_031C
|
00A02065   8B801C030000           mov     eax, [eax+$031C]
00A0206B   33D2                   xor     edx, edx

* Reference to: Controls.Proc_0094B208
|
00A0206D   E89691F4FF             call    0094B208

* Reference to ConnectOptionsForm
|
00A02072   8B45FC                 mov     eax, [ebp-$04]

* Reference to field ConnectOptionsForm.OFFS_0320
|
00A02075   8B8020030000           mov     eax, [eax+$0320]
00A0207B   8B803C020000           mov     eax, [eax+$023C]
00A02081   8B10                   mov     edx, [eax]
00A02083   FF5214                 call    dword ptr [edx+$14]
00A02086   85C0                   test    eax, eax
00A02088   7E20                   jle     00A020AA

* Reference to ConnectOptionsForm
|
00A0208A   8B45FC                 mov     eax, [ebp-$04]

* Reference to field ConnectOptionsForm.OFFS_0320
|
00A0208D   8B8020030000           mov     eax, [eax+$0320]
00A02093   B201                   mov     dl, $01
00A02095   8B08                   mov     ecx, [eax]
00A02097   FF5164                 call    dword ptr [ecx+$64]

* Reference to ConnectOptionsForm
|
00A0209A   8B45FC                 mov     eax, [ebp-$04]

* Reference to field ConnectOptionsForm.OFFS_031C
|
00A0209D   8B801C030000           mov     eax, [eax+$031C]
00A020A3   B201                   mov     dl, $01
00A020A5   8B08                   mov     ecx, [eax]
00A020A7   FF5164                 call    dword ptr [ecx+$64]
00A020AA   C3                     ret

*)
end;

procedure TConnectOptionsForm._PROC_00A020F3(Sender : TObject);
begin
(*
00A020F3   005761                 add     [edi+$61], dl
00A020F6   726E                   jb      00A02166
00A020F8   696E6721000000         imul    ebp, [esi+$67], $00000021
00A020FF   00596F                 add     [ecx+$6F], bl
00A02102   7520                   jnz     00A02124
00A02104   6D                     insd
00A02105   7573                   jnz     00A0217A
00A02107   7420                   jz      00A02129
00A02109   7365                   jnb     00A02170
00A0210B   7420                   jz      00A0212D
00A0210D   44                     inc     esp
00A0210E   61                     popa
00A0210F   736F                   jnb     00A02180
00A02111   7572                   jnz     00A02185
00A02113   636520                 arpl    [ebp+$20], sp
00A02116   61                     popa
00A02117   6E                     outsb
00A02118   6420444275             and     fs:[edx+eax*2+$75], al
00A0211D   7365                   jnb     00A02184
00A0211F   7220                   jb      00A02141
00A02121   666972737421           imul    si, word ptr [edx+$73], $2174
00A02127   00C6                   add     dh, al
00A02129   80F801                 cmp     al, $01
00A0212C   0000                   add     [eax], al

00A0212E   01C3                   add     ebx, eax
00A02130   55                     push    ebp
00A02131   8BEC                   mov     ebp, esp
00A02133   6A00                   push    $00
00A02135   53                     push    ebx
00A02136   8BD8                   mov     ebx, eax
00A02138   33C0                   xor     eax, eax
00A0213A   55                     push    ebp
00A0213B   687C21A000             push    $00A0217C
00A02140   64FF30                 push    dword ptr fs:[eax]
00A02143   648920                 mov     fs:[eax], esp
00A02146   8D55FC                 lea     edx, [ebp-$04]
00A02149   8B8320030000           mov     eax, [ebx+$0320]

* Reference to: Controls.Proc_0094B1D8
|
00A0214F   E88490F4FF             call    0094B1D8
00A02154   837DFC00               cmp     dword ptr [ebp-$04], +$00
00A02158   0F95C2                 setnz   dl
00A0215B   8B833C030000           mov     eax, [ebx+$033C]
00A02161   8B08                   mov     ecx, [eax]
00A02163   FF5164                 call    dword ptr [ecx+$64]
00A02166   33C0                   xor     eax, eax
00A02168   5A                     pop     edx
00A02169   59                     pop     ecx
00A0216A   59                     pop     ecx
00A0216B   648910                 mov     fs:[eax], edx

****** FINALLY
|
00A0216E   688321A000             push    $00A02183
00A02173   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
00A02176   E8B926F0FF             call    00904834
00A0217B   C3                     ret

00A0217C   E9FB1FF0FF             jmp     0090417C
00A02181   EBF0                   jmp     00A02173

****** END
|
00A02183   5B                     pop     ebx
00A02184   59                     pop     ecx
00A02185   5D                     pop     ebp
00A02186   C3                     ret

*)
end;

procedure TConnectOptionsForm._PROC_00A02248(Sender : TObject);
begin
(*
00A02248   55                     push    ebp
00A02249   8BEC                   mov     ebp, esp
00A0224B   33C0                   xor     eax, eax
00A0224D   55                     push    ebp
00A0224E   686D22A000             push    $00A0226D
00A02253   64FF30                 push    dword ptr fs:[eax]
00A02256   648920                 mov     fs:[eax], esp
00A02259   FF052021A100           inc     dword ptr [$00A12120]
00A0225F   33C0                   xor     eax, eax
00A02261   5A                     pop     edx
00A02262   59                     pop     ecx
00A02263   59                     pop     ecx
00A02264   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É- !°'
|
00A02267   687422A000             push    $00A02274
00A0226C   C3                     ret

00A0226D   E90A1FF0FF             jmp     0090417C
00A02272   EBF8                   jmp     00A0226C

****** END
|
00A02274   5D                     pop     ebp
00A02275   C3                     ret

*)
end;

procedure TConnectOptionsForm._PROC_00A02278(Sender : TObject);
begin
(*
00A02278   832D2021A10001         sub     dword ptr [$00A12120], +$01
00A0227F   C3                     ret

*)
end;

end.