unit DBPWDlg;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TPasswordDialog=class(TForm)
    GroupBox1: TGroupBox;
    Edit: TEdit;
    AddButton: TButton;
    RemoveButton: TButton;
    RemoveAllButton: TButton;
    OKButton: TButton;
    CancelButton: TButton;
    procedure EditChange(Sender : TObject);
    procedure AddButtonClick(Sender : TObject);
    procedure RemoveButtonClick(Sender : TObject);
    procedure RemoveAllButtonClick(Sender : TObject);
    procedure OKButtonClick(Sender : TObject);
    procedure _PROC_009C89CC(Sender : TObject);
    procedure _PROC_009C8A08(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  PasswordDialog: TPasswordDialog;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TPasswordDialog.EditChange(Sender : TObject);
begin
(*
009C87E8   55                     push    ebp
009C87E9   8BEC                   mov     ebp, esp
009C87EB   6A00                   push    $00
009C87ED   53                     push    ebx
009C87EE   56                     push    esi
009C87EF   8BF0                   mov     esi, eax
009C87F1   33C0                   xor     eax, eax
009C87F3   55                     push    ebp
009C87F4   6862889C00             push    $009C8862
009C87F9   64FF30                 push    dword ptr fs:[eax]
009C87FC   648920                 mov     fs:[eax], esp
009C87FF   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TPasswordDialog.Edit : TEdit
|
009C8802   8B86F4020000           mov     eax, [esi+$02F4]

* Reference to: Controls.Proc_0094B1D8
|
009C8808   E8CB29F8FF             call    0094B1D8
009C880D   837DFC00               cmp     dword ptr [ebp-$04], +$00
009C8811   0F95C3                 setnz   bl
009C8814   8BD3                   mov     edx, ebx

* Reference to control TPasswordDialog.AddButton : TButton
|
009C8816   8B86F8020000           mov     eax, [esi+$02F8]
009C881C   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TButton.OFFS_64
|
009C881E   FF5164                 call    dword ptr [ecx+$64]
009C8821   8BD3                   mov     edx, ebx

* Reference to control TPasswordDialog.RemoveButton : TButton
|
009C8823   8B86FC020000           mov     eax, [esi+$02FC]
009C8829   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TButton.OFFS_64
|
009C882B   FF5164                 call    dword ptr [ecx+$64]
009C882E   84DB                   test    bl, bl
009C8830   750D                   jnz     009C883F

* Reference to field TPasswordDialog.OFFS_030C
|
009C8832   80BE0C03000000         cmp     byte ptr [esi+$030C], $00
009C8839   7504                   jnz     009C883F
009C883B   33D2                   xor     edx, edx
009C883D   EB02                   jmp     009C8841
009C883F   B201                   mov     dl, $01

* Reference to control TPasswordDialog.OKButton : TButton
|
009C8841   8B8604030000           mov     eax, [esi+$0304]
009C8847   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TButton.OFFS_64
|
009C8849   FF5164                 call    dword ptr [ecx+$64]
009C884C   33C0                   xor     eax, eax
009C884E   5A                     pop     edx
009C884F   59                     pop     ecx
009C8850   59                     pop     ecx
009C8851   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]√ã¿UãÏj'
|
009C8854   6869889C00             push    $009C8869
009C8859   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009C885C   E8D3BFF3FF             call    00904834
009C8861   C3                     ret

009C8862   E915B9F3FF             jmp     0090417C
009C8867   EBF0                   jmp     009C8859

****** END
|
009C8869   5E                     pop     esi
009C886A   5B                     pop     ebx
009C886B   59                     pop     ecx
009C886C   5D                     pop     ebp
009C886D   C3                     ret

*)
end;

procedure TPasswordDialog.AddButtonClick(Sender : TObject);
begin
(*
009C8870   55                     push    ebp
009C8871   8BEC                   mov     ebp, esp
009C8873   6A00                   push    $00
009C8875   53                     push    ebx
009C8876   8BD8                   mov     ebx, eax
009C8878   33C0                   xor     eax, eax
009C887A   55                     push    ebp

* Possible String Reference to: 'Èú∏ÛˇÎ[Y]√ã¿UãÏj'
|
009C887B   68DB889C00             push    $009C88DB
009C8880   64FF30                 push    dword ptr fs:[eax]
009C8883   648920                 mov     fs:[eax], esp
009C8886   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TPasswordDialog.Edit : TEdit
|
009C8889   8B83F4020000           mov     eax, [ebx+$02F4]

* Reference to: Controls.Proc_0094B1D8
|
009C888F   E84429F8FF             call    0094B1D8
009C8894   8B55FC                 mov     edx, [ebp-$04]

* Reference to field TPasswordDialog.OFFS_0310
|
009C8897   8B8310030000           mov     eax, [ebx+$0310]
009C889D   8B08                   mov     ecx, [eax]
009C889F   FF510C                 call    dword ptr [ecx+$0C]

* Reference to field TPasswordDialog.OFFS_030C
|
009C88A2   C6830C03000001         mov     byte ptr [ebx+$030C], $01

* Reference to control TPasswordDialog.Edit : TEdit
|
009C88A9   8B83F4020000           mov     eax, [ebx+$02F4]
009C88AF   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00DC
|
009C88B1   FF92DC000000           call    dword ptr [edx+$00DC]

* Reference to control TPasswordDialog.Edit : TEdit
|
009C88B7   8B83F4020000           mov     eax, [ebx+$02F4]
009C88BD   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00C0
|
009C88BF   FF92C0000000           call    dword ptr [edx+$00C0]
009C88C5   33C0                   xor     eax, eax
009C88C7   5A                     pop     edx
009C88C8   59                     pop     ecx
009C88C9   59                     pop     ecx
009C88CA   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√ã¿UãÏj'
|
009C88CD   68E2889C00             push    $009C88E2
009C88D2   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009C88D5   E85ABFF3FF             call    00904834
009C88DA   C3                     ret

009C88DB   E99CB8F3FF             jmp     0090417C
009C88E0   EBF0                   jmp     009C88D2

****** END
|
009C88E2   5B                     pop     ebx
009C88E3   59                     pop     ecx
009C88E4   5D                     pop     ebp
009C88E5   C3                     ret

*)
end;

procedure TPasswordDialog.RemoveButtonClick(Sender : TObject);
begin
(*
009C88E8   55                     push    ebp
009C88E9   8BEC                   mov     ebp, esp
009C88EB   6A00                   push    $00
009C88ED   53                     push    ebx
009C88EE   8BD8                   mov     ebx, eax
009C88F0   33C0                   xor     eax, eax
009C88F2   55                     push    ebp
009C88F3   684C899C00             push    $009C894C
009C88F8   64FF30                 push    dword ptr fs:[eax]
009C88FB   648920                 mov     fs:[eax], esp
009C88FE   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TPasswordDialog.Edit : TEdit
|
009C8901   8B83F4020000           mov     eax, [ebx+$02F4]

* Reference to: Controls.Proc_0094B1D8
|
009C8907   E8CC28F8FF             call    0094B1D8
009C890C   8B55FC                 mov     edx, [ebp-$04]

* Reference to field TPasswordDialog.OFFS_0310
|
009C890F   8B8310030000           mov     eax, [ebx+$0310]
009C8915   8B08                   mov     ecx, [eax]
009C8917   FF5110                 call    dword ptr [ecx+$10]

* Reference to control TPasswordDialog.Edit : TEdit
|
009C891A   8B83F4020000           mov     eax, [ebx+$02F4]
009C8920   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00DC
|
009C8922   FF92DC000000           call    dword ptr [edx+$00DC]

* Reference to control TPasswordDialog.Edit : TEdit
|
009C8928   8B83F4020000           mov     eax, [ebx+$02F4]
009C892E   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00C0
|
009C8930   FF92C0000000           call    dword ptr [edx+$00C0]
009C8936   33C0                   xor     eax, eax
009C8938   5A                     pop     edx
009C8939   59                     pop     ecx
009C893A   59                     pop     ecx
009C893B   648910                 mov     fs:[eax], edx

****** FINALLY
|
009C893E   6853899C00             push    $009C8953
009C8943   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009C8946   E8E9BEF3FF             call    00904834
009C894B   C3                     ret

009C894C   E92BB8F3FF             jmp     0090417C
009C8951   EBF0                   jmp     009C8943

****** END
|
009C8953   5B                     pop     ebx
009C8954   59                     pop     ecx
009C8955   5D                     pop     ebp
009C8956   C3                     ret

*)
end;

procedure TPasswordDialog.RemoveAllButtonClick(Sender : TObject);
begin
(*
009C8958   53                     push    ebx
009C8959   8BD8                   mov     ebx, eax

* Reference to field TPasswordDialog.OFFS_0310
|
009C895B   8B8310030000           mov     eax, [ebx+$0310]
009C8961   8B10                   mov     edx, [eax]
009C8963   FF5214                 call    dword ptr [edx+$14]

* Reference to control TPasswordDialog.Edit : TEdit
|
009C8966   8B83F4020000           mov     eax, [ebx+$02F4]
009C896C   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00C0
|
009C896E   FF92C0000000           call    dword ptr [edx+$00C0]
009C8974   5B                     pop     ebx
009C8975   C3                     ret

*)
end;

procedure TPasswordDialog.OKButtonClick(Sender : TObject);
begin
(*
009C8978   55                     push    ebp
009C8979   8BEC                   mov     ebp, esp
009C897B   6A00                   push    $00
009C897D   53                     push    ebx
009C897E   8BD8                   mov     ebx, eax
009C8980   33C0                   xor     eax, eax
009C8982   55                     push    ebp

* Possible String Reference to: 'È∑∑ÛˇÎ[Y]√êUãÏ3¿Uh¸âú'
|
009C8983   68C0899C00             push    $009C89C0
009C8988   64FF30                 push    dword ptr fs:[eax]
009C898B   648920                 mov     fs:[eax], esp
009C898E   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TPasswordDialog.Edit : TEdit
|
009C8991   8B83F4020000           mov     eax, [ebx+$02F4]

* Reference to: Controls.Proc_0094B1D8
|
009C8997   E83C28F8FF             call    0094B1D8
009C899C   8B55FC                 mov     edx, [ebp-$04]

* Reference to field TPasswordDialog.OFFS_0310
|
009C899F   8B8310030000           mov     eax, [ebx+$0310]
009C89A5   8B08                   mov     ecx, [eax]
009C89A7   FF510C                 call    dword ptr [ecx+$0C]
009C89AA   33C0                   xor     eax, eax
009C89AC   5A                     pop     edx
009C89AD   59                     pop     ecx
009C89AE   59                     pop     ecx
009C89AF   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]√êUãÏ3¿Uh¸âú'
|
009C89B2   68C7899C00             push    $009C89C7
009C89B7   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009C89BA   E875BEF3FF             call    00904834
009C89BF   C3                     ret

009C89C0   E9B7B7F3FF             jmp     0090417C
009C89C5   EBF0                   jmp     009C89B7

****** END
|
009C89C7   5B                     pop     ebx
009C89C8   59                     pop     ecx
009C89C9   5D                     pop     ebp
009C89CA   C3                     ret

*)
end;

procedure TPasswordDialog._PROC_009C89CC(Sender : TObject);
begin
(*
009C89CC   55                     push    ebp
009C89CD   8BEC                   mov     ebp, esp
009C89CF   33C0                   xor     eax, eax
009C89D1   55                     push    ebp

* Possible String Reference to: 'È{∑ÛˇÎ¯]√ç@'
|
009C89D2   68FC899C00             push    $009C89FC
009C89D7   64FF30                 push    dword ptr fs:[eax]
009C89DA   648920                 mov     fs:[eax], esp
009C89DD   FF059C1DA100           inc     dword ptr [$00A11D9C]
009C89E3   7509                   jnz     009C89EE

* Reference to pointer to GlobalVar_00A11C90
|
009C89E5   A1D0FAA000             mov     eax, dword ptr [$00A0FAD0]
009C89EA   33D2                   xor     edx, edx
009C89EC   8910                   mov     [eax], edx
009C89EE   33C0                   xor     eax, eax
009C89F0   5A                     pop     edx
009C89F1   59                     pop     ecx
009C89F2   59                     pop     ecx
009C89F3   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ç@'
|
009C89F6   68038A9C00             push    $009C8A03
009C89FB   C3                     ret

009C89FC   E97BB7F3FF             jmp     0090417C
009C8A01   EBF8                   jmp     009C89FB

****** END
|
009C8A03   5D                     pop     ebp
009C8A04   C3                     ret

*)
end;

procedure TPasswordDialog._PROC_009C8A08(Sender : TObject);
begin
(*
009C8A08   832D9C1DA10001         sub     dword ptr [$00A11D9C], +$01
009C8A0F   730B                   jnb     009C8A1C

* Reference to pointer to GlobalVar_00A11C90
|
009C8A11   A1D0FAA000             mov     eax, dword ptr [$00A0FAD0]
009C8A16   C70074879C00           mov     dword ptr [eax], $009C8774
009C8A1C   C3                     ret

*)
end;

end.