unit DBTransferProgressUnit;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TDBTransferProgressForm=class(TForm)
    Label2: TLabel;
    Gauge1: TGauge;
    ListView1: TListView;
    SpeedButton1: TSpeedButton;
    SpeedButton2: TSpeedButton;
    Label1: TLabel;
    Label3: TLabel;
    procedure FormCreate(Sender : TObject);
    procedure SpeedButton1Click(Sender : TObject);
    procedure FormCloseQuery(Sender : TObject);
    procedure SpeedButton2Click(Sender : TObject);
    procedure _PROC_00A03D68(Sender : TObject);
    procedure _PROC_00A03D98(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DBTransferProgressForm: TDBTransferProgressForm;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TDBTransferProgressForm.FormCreate(Sender : TObject);
begin
(*
00A03D30   53                     push    ebx
00A03D31   8BD8                   mov     ebx, eax
00A03D33   8BC3                   mov     eax, ebx

* Reference to: Controls.Proc_00951A7C
|
00A03D35   E842DDF4FF             call    00951A7C

* Reference to: DBTransferProgressUnit.Proc_00A03D10
|
00A03D3A   E8D1FFFFFF             call    00A03D10
00A03D3F   5B                     pop     ebx
00A03D40   C3                     ret

*)
end;

procedure TDBTransferProgressForm.SpeedButton1Click(Sender : TObject);
begin
(*

* Reference to field TDBTransferProgressForm.OFFS_030C
|
00A03D44   C6800C03000001         mov     byte ptr [eax+$030C], $01

* Reference to : TApplication._PROC_0096912C()
|
00A03D4B   E8DC53F6FF             call    0096912C
00A03D50   C3                     ret

*)
end;

procedure TDBTransferProgressForm.FormCloseQuery(Sender : TObject);
begin
(*

* Reference to field TDBTransferProgressForm.OFFS_030C
|
00A03D54   8A800C030000           mov     al, byte ptr [eax+$030C]
00A03D5A   8801                   mov     [ecx], al
00A03D5C   C3                     ret

*)
end;

procedure TDBTransferProgressForm.SpeedButton2Click(Sender : TObject);
begin
(*

* Reference to field TDBTransferProgressForm.OFFS_030D
|
00A03D60   C6800D03000001         mov     byte ptr [eax+$030D], $01
00A03D67   C3                     ret

*)
end;

procedure TDBTransferProgressForm._PROC_00A03D68(Sender : TObject);
begin
(*
00A03D68   55                     push    ebp
00A03D69   8BEC                   mov     ebp, esp
00A03D6B   33C0                   xor     eax, eax
00A03D6D   55                     push    ebp
00A03D6E   688D3DA000             push    $00A03D8D
00A03D73   64FF30                 push    dword ptr fs:[eax]
00A03D76   648920                 mov     fs:[eax], esp
00A03D79   FF053C21A100           inc     dword ptr [$00A1213C]
00A03D7F   33C0                   xor     eax, eax
00A03D81   5A                     pop     edx
00A03D82   59                     pop     ecx
00A03D83   59                     pop     ecx
00A03D84   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-<!¡'
|
00A03D87   68943DA000             push    $00A03D94
00A03D8C   C3                     ret

00A03D8D   E9EA03F0FF             jmp     0090417C
00A03D92   EBF8                   jmp     00A03D8C

****** END
|
00A03D94   5D                     pop     ebp
00A03D95   C3                     ret

*)
end;

procedure TDBTransferProgressForm._PROC_00A03D98(Sender : TObject);
begin
(*
00A03D98   832D3C21A10001         sub     dword ptr [$00A1213C], +$01
00A03D9F   C3                     ret

*)
end;

end.