{This file is generated by DelphiDecompiler Version 1.1 Copyright (c) 1997-2009 by BitMaker}

Project MuEdit;

Uses
  DataModuleUnit in 'DataModuleUnit.pas' {TDataModule_Main},
  DBLogDlg in 'DBLogDlg.pas' {TLoginDialog},
  DBPWDlg in 'DBPWDlg.pas' {TPasswordDialog},
  NewCharacter in 'NewCharacter.pas' {TNewCharacterForm},
  WareHouseUnit in 'WareHouseUnit.pas' {TWarehouseEditForm},
  CreateItem in 'CreateItem.pas' {TCreateItemForm},
  CharacterBagEditor in 'CharacterBagEditor.pas' {TCharacterBagEditorForm},
  CharacterMarkUnit in 'CharacterMarkUnit.pas' {TCharacterMarkForm},
  top100Unit in 'top100Unit.pas' {TTop100Form},
  DsRankingUnit in 'DsRankingUnit.pas' {TDsRankingForm},
  ShowUsersUnit in 'ShowUsersUnit.pas' {TShowUsersForm},
  ShowGuildsUnit in 'ShowGuildsUnit.pas' {TShowGuildsForm},
  NewAccountUnit in 'NewAccountUnit.pas' {TNewAccountForm},
  EditCharacter in 'EditCharacter.pas' {TEditCharacterForm},
  SmartSearch in 'SmartSearch.pas' {TSmartSearchForm},
  SqlQuery in 'SqlQuery.pas' {TSqlQueryForm},
  ConnectOptions in 'ConnectOptions.pas' {TConnectOptionsForm},
  SkinSelectUnit in 'SkinSelectUnit.pas' {TSkinSelectForm},
  AboutUnit in 'AboutUnit.pas' {TAboutForm},
  DBTransferProgressUnit in 'DBTransferProgressUnit.pas' {TDBTransferProgressForm},
  progressunit in 'progressunit.pas' {TProgressbarform},
  DBMigrationDialog in 'DBMigrationDialog.pas' {TDBMigrationForm},
  BacupUnit in 'BacupUnit.pas' {TBackupForm},
  MainUnit in 'MainUnit.pas' {TMainForm};

{$R *.RES}

begin
{
00A0C754   55                     push    ebp
00A0C755   8BEC                   mov     ebp, esp
00A0C757   B905000000             mov     ecx, $00000005
00A0C75C   6A00                   push    $00
00A0C75E   6A00                   push    $00
00A0C760   49                     dec     ecx
00A0C761   75F9                   jnz     00A0C75C
00A0C763   51                     push    ecx
00A0C764   53                     push    ebx
00A0C765   56                     push    esi
00A0C766   57                     push    edi
00A0C767   B8ACC3A000             mov     eax, $00A0C3AC

* Reference to: SysInit.Proc_00906FD8
|
00A0C76C   E867A8EFFF             call    00906FD8
00A0C771   33C0                   xor     eax, eax
00A0C773   55                     push    ebp

* Possible String Reference to: 'é<sïÿëÞ_^[èúxïÿ'
|
00A0C774   683BCEA000             push    $00A0CE3B
00A0C779   64FF30                 push    dword ptr fs:[eax]
00A0C77C   648920                 mov     fs:[eax], esp

* Reference to pointer to GlobalVar_00A1215C
|
00A0C77F   A13CFCA000             mov     eax, dword ptr [$00A0FC3C]
00A0C784   C60000                 mov     byte ptr [eax], $00

* Reference to TApplication instance
|
00A0C787   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C78C   8B00                   mov     eax, [eax]

* Reference to: Forms.Proc_0096C740
|
00A0C78E   E8ADFFF5FF             call    0096C740

* Reference to TApplication instance
|
00A0C793   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C798   8B00                   mov     eax, [eax]

* Possible String Reference to: 'MuEditor 2.1 - SkyTeam'
|
00A0C79A   BA54CEA000             mov     edx, $00A0CE54

* Reference to: Forms.Proc_0096C34C
|
00A0C79F   E8A8FBF5FF             call    0096C34C

* Reference to TMainForm instance
|
00A0C7A4   8B0D34FCA000           mov     ecx, [$00A0FC34]

* Reference to TApplication instance
|
00A0C7AA   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C7AF   8B00                   mov     eax, [eax]

* Reference to class TMainForm
|
00A0C7B1   8B159869A000           mov     edx, [$00A06998]

* Reference to: Forms.Proc_0096C758
|
00A0C7B7   E89CFFF5FF             call    0096C758

* Reference to TMainForm instance
|
00A0C7BC   A134FCA000             mov     eax, dword ptr [$00A0FC34]
00A0C7C1   8B00                   mov     eax, [eax]

* Reference to: Forms.Proc_009692CC
|
00A0C7C3   E804CBF5FF             call    009692CC

* Reference to TNewCharacterForm instance
|
00A0C7C8   8B0D54FFA000           mov     ecx, [$00A0FF54]

* Reference to TApplication instance
|
00A0C7CE   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C7D3   8B00                   mov     eax, [eax]

* Reference to class TNewCharacterForm
|
00A0C7D5   8B159CF29E00           mov     edx, [$009EF29C]

* Reference to: Forms.Proc_0096C758
|
00A0C7DB   E878FFF5FF             call    0096C758

* Reference to TCharacterBagEditorForm instance
|
00A0C7E0   8B0D40FFA000           mov     ecx, [$00A0FF40]

* Reference to TApplication instance
|
00A0C7E6   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C7EB   8B00                   mov     eax, [eax]

* Reference to class TCharacterBagEditorForm
|
00A0C7ED   8B15F4729F00           mov     edx, [$009F72F4]

* Reference to: Forms.Proc_0096C758
|
00A0C7F3   E860FFF5FF             call    0096C758

* Reference to TCreateItemForm instance
|
00A0C7F8   8B0D74FBA000           mov     ecx, [$00A0FB74]

* Reference to TApplication instance
|
00A0C7FE   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C803   8B00                   mov     eax, [eax]

* Reference to class TCreateItemForm
|
00A0C805   8B15A4449F00           mov     edx, [$009F44A4]

* Reference to: Forms.Proc_0096C758
|
00A0C80B   E848FFF5FF             call    0096C758

* Reference to TTop100Form instance
|
00A0C810   8B0DD8FDA000           mov     ecx, [$00A0FDD8]

* Reference to TApplication instance
|
00A0C816   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C81B   8B00                   mov     eax, [eax]

* Reference to class TTop100Form
|
00A0C81D   8B1534AA9F00           mov     edx, [$009FAA34]

* Reference to: Forms.Proc_0096C758
|
00A0C823   E830FFF5FF             call    0096C758

* Reference to TDsRankingForm instance
|
00A0C828   8B0D5401A100           mov     ecx, [$00A10154]

* Reference to TApplication instance
|
00A0C82E   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C833   8B00                   mov     eax, [eax]

* Reference to class TDsRankingForm
|
00A0C835   8B15FCB89F00           mov     edx, [$009FB8FC]

* Reference to: Forms.Proc_0096C758
|
00A0C83B   E818FFF5FF             call    0096C758

* Reference to TShowUsersForm instance
|
00A0C840   8B0DF0FBA000           mov     ecx, [$00A0FBF0]

* Reference to TApplication instance
|
00A0C846   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C84B   8B00                   mov     eax, [eax]

* Reference to class TShowUsersForm
|
00A0C84D   8B15C0C29F00           mov     edx, [$009FC2C0]

* Reference to: Forms.Proc_0096C758
|
00A0C853   E800FFF5FF             call    0096C758

* Reference to TShowGuildsForm instance
|
00A0C858   8B0D58FFA000           mov     ecx, [$00A0FF58]

* Reference to TApplication instance
|
00A0C85E   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C863   8B00                   mov     eax, [eax]

* Reference to class TShowGuildsForm
|
00A0C865   8B1570CF9F00           mov     edx, [$009FCF70]

* Reference to: Forms.Proc_0096C758
|
00A0C86B   E8E8FEF5FF             call    0096C758

* Reference to TSmartSearchForm instance
|
00A0C870   8B0DE0FFA000           mov     ecx, [$00A0FFE0]

* Reference to TApplication instance
|
00A0C876   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C87B   8B00                   mov     eax, [eax]

* Reference to class TSmartSearchForm
|
00A0C87D   8B15580BA000           mov     edx, [$00A00B58]

* Reference to: Forms.Proc_0096C758
|
00A0C883   E8D0FEF5FF             call    0096C758

* Reference to TNewAccountForm instance
|
00A0C888   8B0D78FFA000           mov     ecx, [$00A0FF78]

* Reference to TApplication instance
|
00A0C88E   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C893   8B00                   mov     eax, [eax]

* Reference to class TNewAccountForm
|
00A0C895   8B1540DA9F00           mov     edx, [$009FDA40]

* Reference to: Forms.Proc_0096C758
|
00A0C89B   E8B8FEF5FF             call    0096C758

* Reference to TWarehouseEditForm instance
|
00A0C8A0   8B0D6801A100           mov     ecx, [$00A10168]

* Reference to TApplication instance
|
00A0C8A6   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C8AB   8B00                   mov     eax, [eax]

* Reference to class TWarehouseEditForm
|
00A0C8AD   8B15BC1A9F00           mov     edx, [$009F1ABC]

* Reference to: Forms.Proc_0096C758
|
00A0C8B3   E8A0FEF5FF             call    0096C758

* Reference to TEditCharacterForm instance
|
00A0C8B8   8B0D58FCA000           mov     ecx, [$00A0FC58]

* Reference to TApplication instance
|
00A0C8BE   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C8C3   8B00                   mov     eax, [eax]

* Reference to class TEditCharacterForm
|
00A0C8C5   8B15B8E99F00           mov     edx, [$009FE9B8]

* Reference to: Forms.Proc_0096C758
|
00A0C8CB   E888FEF5FF             call    0096C758

* Reference to TSqlQueryForm instance
|
00A0C8D0   8B0D90FFA000           mov     ecx, [$00A0FF90]

* Reference to TApplication instance
|
00A0C8D6   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C8DB   8B00                   mov     eax, [eax]

* Reference to class TSqlQueryForm
|
00A0C8DD   8B156014A000           mov     edx, [$00A01460]

* Reference to: Forms.Proc_0096C758
|
00A0C8E3   E870FEF5FF             call    0096C758

* Reference to TConnectOptionsForm instance
|
00A0C8E8   8B0DB8FEA000           mov     ecx, [$00A0FEB8]

* Reference to TApplication instance
|
00A0C8EE   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C8F3   8B00                   mov     eax, [eax]

* Reference to class TConnectOptionsForm
|
00A0C8F5   8B15EC18A000           mov     edx, [$00A018EC]

* Reference to: Forms.Proc_0096C758
|
00A0C8FB   E858FEF5FF             call    0096C758

* Reference to TSkinSelectForm instance
|
00A0C900   8B0D5000A100           mov     ecx, [$00A10050]

* Reference to TApplication instance
|
00A0C906   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C90B   8B00                   mov     eax, [eax]

* Reference to class TSkinSelectForm
|
00A0C90D   8B158022A000           mov     edx, [$00A02280]

* Reference to: Forms.Proc_0096C758
|
00A0C913   E840FEF5FF             call    0096C758

* Reference to TAboutForm instance
|
00A0C918   8B0D7401A100           mov     ecx, [$00A10174]

* Reference to TApplication instance
|
00A0C91E   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C923   8B00                   mov     eax, [eax]

* Reference to class TAboutForm
|
00A0C925   8B15F025A000           mov     edx, [$00A025F0]

* Reference to: Forms.Proc_0096C758
|
00A0C92B   E828FEF5FF             call    0096C758

* Reference to TCharacterMarkForm instance
|
00A0C930   8B0D38FEA000           mov     ecx, [$00A0FE38]

* Reference to TApplication instance
|
00A0C936   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C93B   8B00                   mov     eax, [eax]

* Reference to class TCharacterMarkForm
|
00A0C93D   8B1578A49F00           mov     edx, [$009FA478]

* Reference to: Forms.Proc_0096C758
|
00A0C943   E810FEF5FF             call    0096C758

* Reference to TDataModule_Main instance
|
00A0C948   8B0D8CFBA000           mov     ecx, [$00A0FB8C]

* Reference to TApplication instance
|
00A0C94E   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C953   8B00                   mov     eax, [eax]

* Reference to class TDataModule_Main
|
00A0C955   8B152CA99900           mov     edx, [$0099A92C]

* Reference to: Forms.Proc_0096C758
|
00A0C95B   E8F8FDF5FF             call    0096C758

* Reference to TDBMigrationForm instance
|
00A0C960   8B0D24FCA000           mov     ecx, [$00A0FC24]

* Reference to TApplication instance
|
00A0C966   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C96B   8B00                   mov     eax, [eax]

* Reference to class TDBMigrationForm
|
00A0C96D   8B15703FA000           mov     edx, [$00A03F70]

* Reference to: Forms.Proc_0096C758
|
00A0C973   E8E0FDF5FF             call    0096C758

* Reference to TProgressbarform instance
|
00A0C978   8B0D6401A100           mov     ecx, [$00A10164]

* Reference to TApplication instance
|
00A0C97E   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C983   8B00                   mov     eax, [eax]

* Reference to class TProgressbarform
|
00A0C985   8B15A03DA000           mov     edx, [$00A03DA0]

* Reference to: Forms.Proc_0096C758
|
00A0C98B   E8C8FDF5FF             call    0096C758

* Reference to TBackupForm instance
|
00A0C990   8B0D28FBA000           mov     ecx, [$00A0FB28]

* Reference to TApplication instance
|
00A0C996   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C99B   8B00                   mov     eax, [eax]

* Reference to class TBackupForm
|
00A0C99D   8B151864A000           mov     edx, [$00A06418]

* Reference to: Forms.Proc_0096C758
|
00A0C9A3   E8B0FDF5FF             call    0096C758

* Reference to TApplication instance
|
00A0C9A8   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0C9AD   8B00                   mov     eax, [eax]

* Reference to field TApplication.OFFS_0074
|
00A0C9AF   C74074C0270900         mov     dword ptr [eax+$74], $000927C0

* Reference to TConnectOptionsForm instance
|
00A0C9B6   A1B8FEA000             mov     eax, dword ptr [$00A0FEB8]
00A0C9BB   8B00                   mov     eax, [eax]

* Reference to control TConnectOptionsForm.TabSheet2 : TTabSheet
|
00A0C9BD   8B80F8020000           mov     eax, [eax+$02F8]
00A0C9C3   33D2                   xor     edx, edx

* Reference to: ComCtrls.Proc_009AA4AC
|
00A0C9C5   E8E2DAF9FF             call    009AA4AC

* Reference to: Unit_00A096BC.Proc_00A0B310
|
00A0C9CA   E841E9FFFF             call    00A0B310
00A0C9CF   84C0                   test    al, al
00A0C9D1   0F8592000000           jnz     00A0CA69

* Reference to TMainForm instance
|
00A0C9D7   A134FCA000             mov     eax, dword ptr [$00A0FC34]
00A0C9DC   8B00                   mov     eax, [eax]

* Reference to: MainUnit.Proc_00A08634
|
00A0C9DE   E851BCFFFF             call    00A08634

* Reference to TSkinSelectForm instance
|
00A0C9E3   A15000A100             mov     eax, dword ptr [$00A10050]
00A0C9E8   8B00                   mov     eax, [eax]
00A0C9EA   8B10                   mov     edx, [eax]

* Possible reference to virtual method TSkinSelectForm.OFFS_00E8
|
00A0C9EC   FF92E8000000           call    dword ptr [edx+$00E8]

* Reference to TSkinSelectForm instance
|
00A0C9F2   A15000A100             mov     eax, dword ptr [$00A10050]
00A0C9F7   8B00                   mov     eax, [eax]

* Reference to field TSkinSelectForm.OFFS_0310
|
00A0C9F9   83B81003000000         cmp     dword ptr [eax+$0310], +$00
00A0CA00   741F                   jz      00A0CA21

* Reference to TSkinSelectForm instance
|
00A0CA02   A15000A100             mov     eax, dword ptr [$00A10050]
00A0CA07   8B00                   mov     eax, [eax]

* Reference to field TSkinSelectForm.OFFS_0310
|
00A0CA09   8B9010030000           mov     edx, [eax+$0310]

* Reference to TMainForm instance
|
00A0CA0F   A134FCA000             mov     eax, dword ptr [$00A0FC34]
00A0CA14   8B00                   mov     eax, [eax]

* Reference to control TMainForm.SkinData1 : TSkinData
|
00A0CA16   8B8018030000           mov     eax, [eax+$0318]

* Reference to: WinSkinData.Proc_009EE3DC
|
00A0CA1C   E8BB19FEFF             call    009EE3DC

* Reference to TSkinSelectForm instance
|
00A0CA21   A15000A100             mov     eax, dword ptr [$00A10050]
00A0CA26   8B00                   mov     eax, [eax]

* Reference to field TSkinSelectForm.OFFS_030C
|
00A0CA28   8A900C030000           mov     dl, byte ptr [eax+$030C]

* Reference to TMainForm instance
|
00A0CA2E   A134FCA000             mov     eax, dword ptr [$00A0FC34]
00A0CA33   8B00                   mov     eax, [eax]

* Reference to control TMainForm.SkinData1 : TSkinData
|
00A0CA35   8B8018030000           mov     eax, [eax+$0318]

* Reference to: WinSkinData.Proc_009EF130
|
00A0CA3B   E8F026FEFF             call    009EF130
00A0CA40   33C0                   xor     eax, eax
00A0CA42   EB1B                   jmp     00A0CA5F

* Reference to TConnectOptionsForm instance
|
00A0CA44   A1B8FEA000             mov     eax, dword ptr [$00A0FEB8]
00A0CA49   8B00                   mov     eax, [eax]
00A0CA4B   8B10                   mov     edx, [eax]

* Possible reference to virtual method TConnectOptionsForm.OFFS_00E8
|
00A0CA4D   FF92E8000000           call    dword ptr [edx+$00E8]
00A0CA53   83F803                 cmp     eax, +$03

* Reference to pointer to GlobalVar_00A1215C
|
00A0CA56   8B153CFCA000           mov     edx, [$00A0FC3C]
00A0CA5C   0F9402                 setz    byte ptr [edx]
00A0CA5F   83F801                 cmp     eax, +$01
00A0CA62   7405                   jz      00A0CA69
00A0CA64   83F803                 cmp     eax, +$03
00A0CA67   75DB                   jnz     00A0CA44

* Reference to TMainForm instance
|
00A0CA69   A134FCA000             mov     eax, dword ptr [$00A0FC34]
00A0CA6E   8B00                   mov     eax, [eax]

* Reference to: MainUnit.Proc_00A08634
|
00A0CA70   E8BFBBFFFF             call    00A08634
00A0CA75   C6059821A10000         mov     byte ptr [$00A12198], $00
00A0CA7C   E93F020000             jmp     00A0CCC0
00A0CA81   C6059821A10001         mov     byte ptr [$00A12198], $01

* Possible String Reference to: 'Provider=MSDASQL.1;Password='
|
00A0CA88   6874CEA000             push    $00A0CE74

* Reference to pointer to GlobalVar_00A12184
|
00A0CA8D   A1BCFDA000             mov     eax, dword ptr [$00A0FDBC]
00A0CA92   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Persist Security Info=True;User ID
|                                ='
|
00A0CA94   689CCEA000             push    $00A0CE9C

* Reference to pointer to GlobalVar_00A12188
|
00A0CA99   A140FEA000             mov     eax, dword ptr [$00A0FE40]
00A0CA9E   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Data Source='
|
00A0CAA0   68CCCEA000             push    $00A0CECC

* Reference to pointer to GlobalVar_00A1217C
|
00A0CAA5   A1ACFAA000             mov     eax, dword ptr [$00A0FAAC]
00A0CAAA   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Initial Catalog='
|
00A0CAAC   68E4CEA000             push    $00A0CEE4

* Reference to pointer to GlobalVar_00A1218C
|
00A0CAB1   A188FBA000             mov     eax, dword ptr [$00A0FB88]
00A0CAB6   FF30                   push    dword ptr [eax]

* Reference to pointer to GlobalVar_00A12174
|
00A0CAB8   A178FCA000             mov     eax, dword ptr [$00A0FC78]
00A0CABD   BA08000000             mov     edx, $00000008

* Reference to: System.Proc_00904BAC
|
00A0CAC2   E8E580EFFF             call    00904BAC

* Possible String Reference to: 'Provider=MSDASQL.1;Password='
|
00A0CAC7   6874CEA000             push    $00A0CE74

* Reference to pointer to GlobalVar_00A12184
|
00A0CACC   A1BCFDA000             mov     eax, dword ptr [$00A0FDBC]
00A0CAD1   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Persist Security Info=True;User ID
|                                ='
|
00A0CAD3   689CCEA000             push    $00A0CE9C

* Reference to pointer to GlobalVar_00A12188
|
00A0CAD8   A140FEA000             mov     eax, dword ptr [$00A0FE40]
00A0CADD   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Data Source='
|
00A0CADF   68CCCEA000             push    $00A0CECC

* Reference to pointer to GlobalVar_00A1217C
|
00A0CAE4   A1ACFAA000             mov     eax, dword ptr [$00A0FAAC]
00A0CAE9   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Initial Catalog='
|
00A0CAEB   68E4CEA000             push    $00A0CEE4

* Reference to pointer to GlobalVar_00A12180
|
00A0CAF0   A144FEA000             mov     eax, dword ptr [$00A0FE44]
00A0CAF5   FF30                   push    dword ptr [eax]

* Reference to pointer to GlobalVar_00A12178
|
00A0CAF7   A114FFA000             mov     eax, dword ptr [$00A0FF14]
00A0CAFC   BA08000000             mov     edx, $00000008

* Reference to: System.Proc_00904BAC
|
00A0CB01   E8A680EFFF             call    00904BAC
00A0CB06   33D2                   xor     edx, edx
00A0CB08   55                     push    ebp
00A0CB09   688BCBA000             push    $00A0CB8B
00A0CB0E   64FF32                 push    dword ptr fs:[edx]
00A0CB11   648922                 mov     fs:[edx], esp

* Reference to TDataModule_Main instance
|
00A0CB14   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CB19   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CB1B   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
00A0CB1E   E8999AF7FF             call    009865BC

* Reference to TDataModule_Main instance
|
00A0CB23   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CB28   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CB2A   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
00A0CB2D   E886D8F8FF             call    0099A3B8
00A0CB32   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_44
|
00A0CB34   FF5244                 call    dword ptr [edx+$44]
00A0CB37   8D45EC                 lea     eax, [ebp-$14]

* Reference to pointer to GlobalVar_00A12174
|
00A0CB3A   8B1578FCA000           mov     edx, [$00A0FC78]
00A0CB40   8B12                   mov     edx, [edx]

* Reference to: System.Proc_009050F4
|
00A0CB42   E8AD85EFFF             call    009050F4
00A0CB47   8B55EC                 mov     edx, [ebp-$14]

* Reference to TDataModule_Main instance
|
00A0CB4A   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CB4F   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CB51   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_00998488
|
00A0CB54   E82FB9F8FF             call    00998488

* Reference to TDataModule_Main instance
|
00A0CB59   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CB5E   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CB60   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
00A0CB63   E850D8F8FF             call    0099A3B8

* Possible String Reference to: 'SELECT count(*) FROM  Character'
|
00A0CB68   BA00CFA000             mov     edx, $00A0CF00
00A0CB6D   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_38
|
00A0CB6F   FF5138                 call    dword ptr [ecx+$38]

* Reference to TDataModule_Main instance
|
00A0CB72   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CB77   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CB79   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
00A0CB7C   E82F9AF7FF             call    009865B0
00A0CB81   33C0                   xor     eax, eax
00A0CB83   5A                     pop     edx
00A0CB84   59                     pop     ecx
00A0CB85   59                     pop     ecx
00A0CB86   648910                 mov     fs:[eax], edx
00A0CB89   EB35                   jmp     00A0CBC0
00A0CB8B   E96474EFFF             jmp     00903FF4
00A0CB90   0100                   add     [eax], eax
00A0CB92   0000                   add     [eax], al

00A0CB94   48                     dec     eax
00A0CB95   DD96009CCBA0           fst     qword ptr [esi+$A0CB9C00]
00A0CB9B   00C6                   add     dh, al
00A0CB9D   059821A100             add     eax, +$00A12198
00A0CBA2   006A00                 add     [edx+$00], ch

* Possible String Reference to: 'Error'
|
00A0CBA5   B920CFA000             mov     ecx, $00A0CF20

* Possible String Reference to: 'Check your Settings(muonline databa
|                                se)!!'
|
00A0CBAA   BA28CFA000             mov     edx, $00A0CF28

* Reference to TApplication instance
|
00A0CBAF   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0CBB4   8B00                   mov     eax, [eax]

* Reference to: Forms.Proc_0096C968
|
00A0CBB6   E8ADFDF5FF             call    0096C968

* Reference to: System.Proc_009042F4
|
00A0CBBB   E83477EFFF             call    009042F4

****** END
|
00A0CBC0   803D9821A10000         cmp     byte ptr [$00A12198], $00
00A0CBC7   0F84D0000000           jz      00A0CC9D

* Reference to pointer to GlobalVar_00A12180
|
00A0CBCD   A144FEA000             mov     eax, dword ptr [$00A0FE44]
00A0CBD2   833800                 cmp     dword ptr [eax], +$00
00A0CBD5   0F84C2000000           jz      00A0CC9D
00A0CBDB   33D2                   xor     edx, edx
00A0CBDD   55                     push    ebp
00A0CBDE   6860CCA000             push    $00A0CC60
00A0CBE3   64FF32                 push    dword ptr fs:[edx]
00A0CBE6   648922                 mov     fs:[edx], esp

* Reference to TDataModule_Main instance
|
00A0CBE9   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CBEE   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CBF0   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
00A0CBF3   E8C499F7FF             call    009865BC

* Reference to TDataModule_Main instance
|
00A0CBF8   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CBFD   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CBFF   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
00A0CC02   E8B1D7F8FF             call    0099A3B8
00A0CC07   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_44
|
00A0CC09   FF5244                 call    dword ptr [edx+$44]
00A0CC0C   8D45E8                 lea     eax, [ebp-$18]

* Reference to pointer to GlobalVar_00A12178
|
00A0CC0F   8B1514FFA000           mov     edx, [$00A0FF14]
00A0CC15   8B12                   mov     edx, [edx]

* Reference to: System.Proc_009050F4
|
00A0CC17   E8D884EFFF             call    009050F4
00A0CC1C   8B55E8                 mov     edx, [ebp-$18]

* Reference to TDataModule_Main instance
|
00A0CC1F   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CC24   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CC26   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_00998488
|
00A0CC29   E85AB8F8FF             call    00998488

* Reference to TDataModule_Main instance
|
00A0CC2E   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CC33   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CC35   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
00A0CC38   E87BD7F8FF             call    0099A3B8

* Possible String Reference to: 'SELECT count(*) FROM EVENT_INFO'
|
00A0CC3D   BA5CCFA000             mov     edx, $00A0CF5C
00A0CC42   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_38
|
00A0CC44   FF5138                 call    dword ptr [ecx+$38]

* Reference to TDataModule_Main instance
|
00A0CC47   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CC4C   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CC4E   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
00A0CC51   E85A99F7FF             call    009865B0
00A0CC56   33C0                   xor     eax, eax
00A0CC58   5A                     pop     edx
00A0CC59   59                     pop     ecx
00A0CC5A   59                     pop     ecx
00A0CC5B   648910                 mov     fs:[eax], edx
00A0CC5E   EB3D                   jmp     00A0CC9D
00A0CC60   E98F73EFFF             jmp     00903FF4
00A0CC65   0100                   add     [eax], eax
00A0CC67   0000                   add     [eax], al

00A0CC69   48                     dec     eax
00A0CC6A   DD960071CCA0           fst     qword ptr [esi+$A0CC7100]
00A0CC70   00A144FEA000           add     [ecx+$A0FE44], ah

* Reference to: System.Proc_00904834
|
00A0CC76   E8B97BEFFF             call    00904834

* Reference to: Unit_00A096BC.Proc_00A0B6D4
|
00A0CC7B   E854EAFFFF             call    00A0B6D4
00A0CC80   6A00                   push    $00

* Possible String Reference to: 'Error'
|
00A0CC82   B920CFA000             mov     ecx, $00A0CF20

* Possible String Reference to: 'Check your Settings (Ranking databa
|                                se)!!'
|
00A0CC87   BA7CCFA000             mov     edx, $00A0CF7C

* Reference to TApplication instance
|
00A0CC8C   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0CC91   8B00                   mov     eax, [eax]

* Reference to: Forms.Proc_0096C968
|
00A0CC93   E8D0FCF5FF             call    0096C968

* Reference to: System.Proc_009042F4
|
00A0CC98   E85776EFFF             call    009042F4

****** END
|
00A0CC9D   803D9821A10000         cmp     byte ptr [$00A12198], $00
00A0CCA4   751A                   jnz     00A0CCC0

* Reference to TConnectOptionsForm instance
|
00A0CCA6   A1B8FEA000             mov     eax, dword ptr [$00A0FEB8]
00A0CCAB   8B00                   mov     eax, [eax]
00A0CCAD   8B10                   mov     edx, [eax]

* Possible reference to virtual method TConnectOptionsForm.OFFS_00E8
|
00A0CCAF   FF92E8000000           call    dword ptr [edx+$00E8]
00A0CCB5   83F803                 cmp     eax, +$03

* Reference to pointer to GlobalVar_00A1215C
|
00A0CCB8   A13CFCA000             mov     eax, dword ptr [$00A0FC3C]
00A0CCBD   0F9400                 setz    byte ptr [eax]
00A0CCC0   803D9821A10000         cmp     byte ptr [$00A12198], $00
00A0CCC7   750E                   jnz     00A0CCD7

* Reference to pointer to GlobalVar_00A1215C
|
00A0CCC9   A13CFCA000             mov     eax, dword ptr [$00A0FC3C]
00A0CCCE   803800                 cmp     byte ptr [eax], $00
00A0CCD1   0F84AAFDFFFF           jz      00A0CA81

* Reference to TDataModule_Main instance
|
00A0CCD7   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CCDC   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CCDE   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
00A0CCE1   E8D698F7FF             call    009865BC

* Reference to TDataModule_Main instance
|
00A0CCE6   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CCEB   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CCED   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
00A0CCF0   E8C3D6F8FF             call    0099A3B8
00A0CCF5   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_44
|
00A0CCF7   FF5244                 call    dword ptr [edx+$44]

* Reference to TMainForm instance
|
00A0CCFA   A134FCA000             mov     eax, dword ptr [$00A0FC34]
00A0CCFF   8B00                   mov     eax, [eax]

* Reference to: MainUnit.Proc_00A08594
|
00A0CD01   E88EB8FFFF             call    00A08594

* Reference to TConnectOptionsForm instance
|
00A0CD06   A1B8FEA000             mov     eax, dword ptr [$00A0FEB8]
00A0CD0B   8B00                   mov     eax, [eax]

* Reference to control TConnectOptionsForm.BitBtn1 : TBitBtn
|
00A0CD0D   8B8040030000           mov     eax, [eax+$0340]

* Reference to: Controls.Proc_0094B700
|
00A0CD13   E8E8E9F3FF             call    0094B700

* Possible String Reference to: 'Provider=MSDASQL.1;Password='
|
00A0CD18   6874CEA000             push    $00A0CE74

* Reference to pointer to GlobalVar_00A12184
|
00A0CD1D   A1BCFDA000             mov     eax, dword ptr [$00A0FDBC]
00A0CD22   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Persist Security Info=True;User ID
|                                ='
|
00A0CD24   689CCEA000             push    $00A0CE9C

* Reference to pointer to GlobalVar_00A12188
|
00A0CD29   A140FEA000             mov     eax, dword ptr [$00A0FE40]
00A0CD2E   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Data Source='
|
00A0CD30   68CCCEA000             push    $00A0CECC

* Reference to pointer to GlobalVar_00A1217C
|
00A0CD35   A1ACFAA000             mov     eax, dword ptr [$00A0FAAC]
00A0CD3A   FF30                   push    dword ptr [eax]

* Possible String Reference to: ';Initial Catalog='
|
00A0CD3C   68E4CEA000             push    $00A0CEE4

* Reference to pointer to GlobalVar_00A1218C
|
00A0CD41   A188FBA000             mov     eax, dword ptr [$00A0FB88]
00A0CD46   FF30                   push    dword ptr [eax]

* Reference to pointer to GlobalVar_00A12174
|
00A0CD48   A178FCA000             mov     eax, dword ptr [$00A0FC78]
00A0CD4D   BA08000000             mov     edx, $00000008

* Reference to: System.Proc_00904BAC
|
00A0CD52   E8557EEFFF             call    00904BAC
00A0CD57   8D45E4                 lea     eax, [ebp-$1C]

* Reference to pointer to GlobalVar_00A12174
|
00A0CD5A   8B1578FCA000           mov     edx, [$00A0FC78]
00A0CD60   8B12                   mov     edx, [edx]

* Reference to: System.Proc_009050F4
|
00A0CD62   E88D83EFFF             call    009050F4
00A0CD67   8B55E4                 mov     edx, [ebp-$1C]

* Reference to TDataModule_Main instance
|
00A0CD6A   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CD6F   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A0CD71   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_00998488
|
00A0CD74   E80FB7F8FF             call    00998488

* Possible String Reference to: 'Provider=Microsoft.Jet.OLEDB.4.0;Da
|                                ta Source='
|
00A0CD79   68B0CFA000             push    $00A0CFB0
00A0CD7E   8D55D4                 lea     edx, [ebp-$2C]

* Reference to TApplication instance
|
00A0CD81   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0CD86   8B00                   mov     eax, [eax]

* Reference to: Forms.Proc_0096CDB0
|
00A0CD88   E82300F6FF             call    0096CDB0
00A0CD8D   8B45D4                 mov     eax, [ebp-$2C]
00A0CD90   8D55D8                 lea     edx, [ebp-$28]

* Reference to: Unit_009082C0.Proc_00909888
|
00A0CD93   E8F0CAEFFF             call    00909888
00A0CD98   FF75D8                 push    dword ptr [ebp-$28]

* Possible String Reference to: 'muitem.mdb'
|
00A0CD9B   68E8CFA000             push    $00A0CFE8

* Possible String Reference to: ';Persist Security Info=False'
|
00A0CDA0   68FCCFA000             push    $00A0CFFC
00A0CDA5   8D45DC                 lea     eax, [ebp-$24]
00A0CDA8   BA04000000             mov     edx, $00000004

* Reference to: System.Proc_00904BAC
|
00A0CDAD   E8FA7DEFFF             call    00904BAC
00A0CDB2   8B55DC                 mov     edx, [ebp-$24]
00A0CDB5   8D45E0                 lea     eax, [ebp-$20]

* Reference to: System.Proc_009050F4
|
00A0CDB8   E83783EFFF             call    009050F4
00A0CDBD   8B55E0                 mov     edx, [ebp-$20]

* Reference to TDataModule_Main instance
|
00A0CDC0   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0CDC5   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.itemQuery : TADOQuery
|
00A0CDC7   8B4058                 mov     eax, [eax+$58]

* Reference to: ADODB.Proc_00998488
|
00A0CDCA   E8B9B6F8FF             call    00998488

* Reference to pointer to GlobalVar_00A1215C
|
00A0CDCF   A13CFCA000             mov     eax, dword ptr [$00A0FC3C]
00A0CDD4   803800                 cmp     byte ptr [eax], $00
00A0CDD7   752E                   jnz     00A0CE07

* Reference to TApplication instance
|
00A0CDD9   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0CDDE   8B00                   mov     eax, [eax]

* Reference to field TApplication.OFFS_005B
|
00A0CDE0   C6405B00               mov     byte ptr [eax+$5B], $00

* Reference to TAboutForm instance
|
00A0CDE4   A17401A100             mov     eax, dword ptr [$00A10174]
00A0CDE9   8B00                   mov     eax, [eax]

* Reference to control TAboutForm.SplashTimer : TTimer
|
00A0CDEB   8B80F0020000           mov     eax, [eax+$02F0]
00A0CDF1   B201                   mov     dl, $01

* Reference to: ExtCtrls.Proc_00940D8C
|
00A0CDF3   E8943FF3FF             call    00940D8C

* Reference to TAboutForm instance
|
00A0CDF8   A17401A100             mov     eax, dword ptr [$00A10174]
00A0CDFD   8B00                   mov     eax, [eax]
00A0CDFF   8B10                   mov     edx, [eax]

* Possible reference to virtual method TAboutForm.OFFS_00E8
|
00A0CE01   FF92E8000000           call    dword ptr [edx+$00E8]

* Reference to TApplication instance
|
00A0CE07   A10CFFA000             mov     eax, dword ptr [$00A0FF0C]
00A0CE0C   8B00                   mov     eax, [eax]

* Reference to: Forms.Proc_0096C7D8
|
00A0CE0E   E8C5F9F5FF             call    0096C7D8
00A0CE13   33C0                   xor     eax, eax
00A0CE15   5A                     pop     edx
00A0CE16   59                     pop     ecx
00A0CE17   59                     pop     ecx
00A0CE18   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[èúxïÿ'
|
00A0CE1B   6842CEA000             push    $00A0CE42
00A0CE20   8D45D4                 lea     eax, [ebp-$2C]
00A0CE23   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904858
|
00A0CE28   E82B7AEFFF             call    00904858
00A0CE2D   8D45E0                 lea     eax, [ebp-$20]
00A0CE30   BA04000000             mov     edx, $00000004

* Reference to: System.Proc_00904F70
|
00A0CE35   E83681EFFF             call    00904F70
00A0CE3A   C3                     ret

}
end.
