unit NewAccountUnit;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TNewAccountForm=class(TForm)
    GroupBox3: TGroupBox;
    Label6: TLabel;
    Label4: TLabel;
    Label2: TLabel;
    Label5: TLabel;
    Label3: TLabel;
    Label1: TLabel;
    OkButton: TBitBtn;
    AccAns: TEdit;
    AccName: TEdit;
    AccPass: TEdit;
    AccQue: TEdit;
    AccEmail: TEdit;
    AccID: TEdit;
    idenitych: TCheckBox;
    SetModalResultOK: TButton;
    Label7: TLabel;
    personalid: TEdit;
    BitBtn1: TBitBtn;
    procedure OkButtonClick(Sender : TObject);
    procedure personalidKeyPress(Sender : TObject);
    procedure _PROC_009FE2CA(Sender : TObject);
    procedure _PROC_009FE3B5(Sender : TObject);
    procedure _PROC_009FE852(Sender : TObject);
    procedure _PROC_009FE981(Sender : TObject);
    procedure _PROC_009FE9B0(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  NewAccountForm: TNewAccountForm;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TNewAccountForm.OkButtonClick(Sender : TObject);
begin
(*
009FDD30   55                     push    ebp
009FDD31   8BEC                   mov     ebp, esp
009FDD33   B90F000000             mov     ecx, $0000000F
009FDD38   6A00                   push    $00
009FDD3A   6A00                   push    $00
009FDD3C   49                     dec     ecx
009FDD3D   75F9                   jnz     009FDD38
009FDD3F   53                     push    ebx
009FDD40   56                     push    esi
009FDD41   57                     push    edi
009FDD42   8945FC                 mov     [ebp-$04], eax
009FDD45   33C0                   xor     eax, eax
009FDD47   55                     push    ebp

* Possible String Reference to: 'é÷_ðÿé\ÿÿÿ_^[‹å]Ã'
|
009FDD48   6880E19F00             push    $009FE180
009FDD4D   64FF30                 push    dword ptr fs:[eax]
009FDD50   648920                 mov     fs:[eax], esp
009FDD53   33C0                   xor     eax, eax
009FDD55   55                     push    ebp
009FDD56   68B6E09F00             push    $009FE0B6
009FDD5B   64FF30                 push    dword ptr fs:[eax]
009FDD5E   648920                 mov     fs:[eax], esp
009FDD61   B301                   mov     bl, $01

* Reference to NewAccountForm
|
009FDD63   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TNewAccountForm.OFFS_033C
|
009FDD66   80B83C03000000         cmp     byte ptr [eax+$033C], $00
009FDD6D   0F8438020000           jz      009FDFAB
009FDD73   8D55F0                 lea     edx, [ebp-$10]

* Reference to NewAccountForm
|
009FDD76   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccID : TEdit
|
009FDD79   8B8024030000           mov     eax, [eax+$0324]

* Reference to: Controls.Proc_0094B1D8
|
009FDD7F   E854D4F4FF             call    0094B1D8
009FDD84   837DF000               cmp     dword ptr [ebp-$10], +$00
009FDD88   7511                   jnz     009FDD9B

* Possible String Reference to: 'Insert account ID'
|
009FDD8A   B89CE19F00             mov     eax, $009FE19C

* Reference to : TMessageForm._PROC_00944368()
|
009FDD8F   E8D465F4FF             call    00944368
009FDD94   33DB                   xor     ebx, ebx
009FDD96   E911030000             jmp     009FE0AC
009FDD9B   8D55EC                 lea     edx, [ebp-$14]

* Reference to NewAccountForm
|
009FDD9E   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccPass : TEdit
|
009FDDA1   8B8018030000           mov     eax, [eax+$0318]

* Reference to: Controls.Proc_0094B1D8
|
009FDDA7   E82CD4F4FF             call    0094B1D8
009FDDAC   837DEC00               cmp     dword ptr [ebp-$14], +$00
009FDDB0   7511                   jnz     009FDDC3

* Possible String Reference to: 'Insert account password'
|
009FDDB2   B8B8E19F00             mov     eax, $009FE1B8

* Reference to : TMessageForm._PROC_00944368()
|
009FDDB7   E8AC65F4FF             call    00944368
009FDDBC   33DB                   xor     ebx, ebx
009FDDBE   E9E9020000             jmp     009FE0AC
009FDDC3   8D45E8                 lea     eax, [ebp-$18]

* Reference to pointer to GlobalVar_00A12174
|
009FDDC6   8B1578FCA000           mov     edx, [$00A0FC78]
009FDDCC   8B12                   mov     edx, [edx]

* Reference to: System.Proc_009050F4
|
009FDDCE   E82173F0FF             call    009050F4
009FDDD3   8B55E8                 mov     edx, [ebp-$18]

* Reference to TDataModule_Main instance
|
009FDDD6   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FDDDB   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
009FDDDD   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009927E8
|
009FDDE0   E8034AF9FF             call    009927E8

* Possible String Reference to: 'INSERT INTO MEMB_INFO (memb_guid,me
|                                mb___id,memb__pwd,memb_name,sno__nu
|                                mb ,post_code,addr_info,addr_deta,t
|                                el__numb,mail_addr ,phon_numb,fpas_
|                                ques,fpas_answ,job__code,appl_days 
|                                ,modi_days,out__days,true_days,mail
|                                _chek,bloc_code ,ctl1_code) VALUES 
|                                (1,''
|
009FDDE5   68D8E19F00             push    $009FE1D8
009FDDEA   8D55E4                 lea     edx, [ebp-$1C]

* Reference to NewAccountForm
|
009FDDED   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccID : TEdit
|
009FDDF0   8B8024030000           mov     eax, [eax+$0324]

* Reference to: Controls.Proc_0094B1D8
|
009FDDF6   E8DDD3F4FF             call    0094B1D8
009FDDFB   FF75E4                 push    dword ptr [ebp-$1C]

* Possible String Reference to: '',''
|
009FDDFE   68DCE29F00             push    $009FE2DC
009FDE03   8D55E0                 lea     edx, [ebp-$20]

* Reference to NewAccountForm
|
009FDE06   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccPass : TEdit
|
009FDE09   8B8018030000           mov     eax, [eax+$0318]

* Reference to: Controls.Proc_0094B1D8
|
009FDE0F   E8C4D3F4FF             call    0094B1D8
009FDE14   FF75E0                 push    dword ptr [ebp-$20]

* Possible String Reference to: '',''
|
009FDE17   68DCE29F00             push    $009FE2DC
009FDE1C   8D55DC                 lea     edx, [ebp-$24]

* Reference to NewAccountForm
|
009FDE1F   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccName : TEdit
|
009FDE22   8B8014030000           mov     eax, [eax+$0314]

* Reference to: Controls.Proc_0094B1D8
|
009FDE28   E8ABD3F4FF             call    0094B1D8
009FDE2D   FF75DC                 push    dword ptr [ebp-$24]

* Possible String Reference to: '', 1,1234,11111,''
|
009FDE30   68E8E29F00             push    $009FE2E8
009FDE35   8D55D8                 lea     edx, [ebp-$28]

* Reference to NewAccountForm
|
009FDE38   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.personalid : TEdit
|
009FDE3B   8B8034030000           mov     eax, [eax+$0334]

* Reference to: Controls.Proc_0094B1D8
|
009FDE41   E892D3F4FF             call    0094B1D8
009FDE46   FF75D8                 push    dword ptr [ebp-$28]

* Possible String Reference to: '',12343,''
|
009FDE49   6804E39F00             push    $009FE304
009FDE4E   8D55D4                 lea     edx, [ebp-$2C]

* Reference to NewAccountForm
|
009FDE51   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccEmail : TEdit
|
009FDE54   8B8020030000           mov     eax, [eax+$0320]

* Reference to: Controls.Proc_0094B1D8
|
009FDE5A   E879D3F4FF             call    0094B1D8
009FDE5F   FF75D4                 push    dword ptr [ebp-$2C]

* Possible String Reference to: '','test@test.com',''
|
009FDE62   6818E39F00             push    $009FE318
009FDE67   8D55D0                 lea     edx, [ebp-$30]

* Reference to NewAccountForm
|
009FDE6A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccQue : TEdit
|
009FDE6D   8B801C030000           mov     eax, [eax+$031C]

* Reference to: Controls.Proc_0094B1D8
|
009FDE73   E860D3F4FF             call    0094B1D8
009FDE78   FF75D0                 push    dword ptr [ebp-$30]

* Possible String Reference to: '',''
|
009FDE7B   68DCE29F00             push    $009FE2DC
009FDE80   8D55CC                 lea     edx, [ebp-$34]

* Reference to NewAccountForm
|
009FDE83   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccAns : TEdit
|
009FDE86   8B8010030000           mov     eax, [eax+$0310]

* Reference to: Controls.Proc_0094B1D8
|
009FDE8C   E847D3F4FF             call    0094B1D8
009FDE91   FF75CC                 push    dword ptr [ebp-$34]

* Possible String Reference to: '',1,'2003-01-01','2003-1-1','2003-1
|                                -1','2003-1-1',1,0,1)'
|
009FDE94   6834E39F00             push    $009FE334
009FDE99   8D45F8                 lea     eax, [ebp-$08]
009FDE9C   BA0F000000             mov     edx, $0000000F

* Reference to: System.Proc_00904BAC
|
009FDEA1   E8066DF0FF             call    00904BAC
009FDEA6   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'SET IDENTITY_INSERT MEMB_INFO ON '
|
009FDEA9   BA78E39F00             mov     edx, $009FE378

* Reference to: System.Proc_009048CC
|
009FDEAE   E8196AF0FF             call    009048CC

* Reference to NewAccountForm
|
009FDEB3   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.idenitych : TCheckBox
|
009FDEB6   8B8028030000           mov     eax, [eax+$0328]

* Reference to field TCheckBox.OFFS_0212
|
009FDEBC   80B81202000001         cmp     byte ptr [eax+$0212], $01
009FDEC3   753F                   jnz     009FDF04
009FDEC5   8D45C4                 lea     eax, [ebp-$3C]
009FDEC8   8B4DF8                 mov     ecx, [ebp-$08]
009FDECB   8B55F4                 mov     edx, [ebp-$0C]

* Reference to: System.Proc_00904B38
|
009FDECE   E8656CF0FF             call    00904B38
009FDED3   8B55C4                 mov     edx, [ebp-$3C]
009FDED6   8D45C8                 lea     eax, [ebp-$38]

* Reference to: System.Proc_009050F4
|
009FDED9   E81672F0FF             call    009050F4
009FDEDE   8B55C8                 mov     edx, [ebp-$38]

* Reference to TDataModule_Main instance
|
009FDEE1   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FDEE6   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
009FDEE8   8B405C                 mov     eax, [eax+$5C]
009FDEEB   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TADOCommand.OFFS_38
|
009FDEED   FF5138                 call    dword ptr [ecx+$38]
009FDEF0   8D55C0                 lea     edx, [ebp-$40]

* Reference to TDataModule_Main instance
|
009FDEF3   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FDEF8   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
009FDEFA   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009920D0
|
009FDEFD   E8CE41F9FF             call    009920D0
009FDF02   EB2F                   jmp     009FDF33
009FDF04   8D45BC                 lea     eax, [ebp-$44]
009FDF07   8B55F8                 mov     edx, [ebp-$08]

* Reference to: System.Proc_009050F4
|
009FDF0A   E8E571F0FF             call    009050F4
009FDF0F   8B55BC                 mov     edx, [ebp-$44]

* Reference to TDataModule_Main instance
|
009FDF12   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FDF17   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
009FDF19   8B405C                 mov     eax, [eax+$5C]
009FDF1C   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TADOCommand.OFFS_38
|
009FDF1E   FF5138                 call    dword ptr [ecx+$38]
009FDF21   8D55B8                 lea     edx, [ebp-$48]

* Reference to TDataModule_Main instance
|
009FDF24   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FDF29   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
009FDF2B   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009920D0
|
009FDF2E   E89D41F9FF             call    009920D0

* Possible String Reference to: 'INSERT INTO VI_CURR_INFO (ends_days
|                                ,chek_code,used_time,memb___id,memb
|                                _name ,memb_guid,sno__numb,Bill_Sec
|                                tion,Bill_value,Bill_Hour,Surplus_P
|                                oint,Surplus_Minute,Increase_Days) 
|                                VALUES (2005,1,1234,''
|
009FDF33   68A4E39F00             push    $009FE3A4
009FDF38   8D55B4                 lea     edx, [ebp-$4C]

* Reference to NewAccountForm
|
009FDF3B   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccID : TEdit
|
009FDF3E   8B8024030000           mov     eax, [eax+$0324]

* Reference to: Controls.Proc_0094B1D8
|
009FDF44   E88FD2F4FF             call    0094B1D8
009FDF49   FF75B4                 push    dword ptr [ebp-$4C]

* Possible String Reference to: '',''
|
009FDF4C   68DCE29F00             push    $009FE2DC
009FDF51   8D55B0                 lea     edx, [ebp-$50]

* Reference to NewAccountForm
|
009FDF54   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccName : TEdit
|
009FDF57   8B8014030000           mov     eax, [eax+$0314]

* Reference to: Controls.Proc_0094B1D8
|
009FDF5D   E876D2F4FF             call    0094B1D8
009FDF62   FF75B0                 push    dword ptr [ebp-$50]

* Possible String Reference to: '',1,7,6,3,6,6,2004-1-1,0)'
|
009FDF65   6874E49F00             push    $009FE474
009FDF6A   8D45F8                 lea     eax, [ebp-$08]
009FDF6D   BA05000000             mov     edx, $00000005

* Reference to: System.Proc_00904BAC
|
009FDF72   E8356CF0FF             call    00904BAC
009FDF77   8D45AC                 lea     eax, [ebp-$54]
009FDF7A   8B55F8                 mov     edx, [ebp-$08]

* Reference to: System.Proc_009050F4
|
009FDF7D   E87271F0FF             call    009050F4
009FDF82   8B55AC                 mov     edx, [ebp-$54]

* Reference to TDataModule_Main instance
|
009FDF85   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FDF8A   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
009FDF8C   8B405C                 mov     eax, [eax+$5C]
009FDF8F   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TADOCommand.OFFS_38
|
009FDF91   FF5138                 call    dword ptr [ecx+$38]
009FDF94   8D55A8                 lea     edx, [ebp-$58]

* Reference to TDataModule_Main instance
|
009FDF97   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FDF9C   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
009FDF9E   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009920D0
|
009FDFA1   E82A41F9FF             call    009920D0
009FDFA6   E901010000             jmp     009FE0AC

* Reference to NewAccountForm
|
009FDFAB   8B45FC                 mov     eax, [ebp-$04]

* Reference to field TNewAccountForm.OFFS_0340
|
009FDFAE   83B84003000000         cmp     dword ptr [eax+$0340], +$00
009FDFB5   7507                   jnz     009FDFBE
009FDFB7   33DB                   xor     ebx, ebx
009FDFB9   E9EE000000             jmp     009FE0AC
009FDFBE   8D45A4                 lea     eax, [ebp-$5C]

* Reference to pointer to GlobalVar_00A12174
|
009FDFC1   8B1578FCA000           mov     edx, [$00A0FC78]
009FDFC7   8B12                   mov     edx, [edx]

* Reference to: System.Proc_009050F4
|
009FDFC9   E82671F0FF             call    009050F4
009FDFCE   8B55A4                 mov     edx, [ebp-$5C]

* Reference to TDataModule_Main instance
|
009FDFD1   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FDFD6   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
009FDFD8   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009927E8
|
009FDFDB   E80848F9FF             call    009927E8

* Possible String Reference to: 'update memb_info set memb__pwd=''
|
009FDFE0   6898E49F00             push    $009FE498
009FDFE5   8D55A0                 lea     edx, [ebp-$60]

* Reference to NewAccountForm
|
009FDFE8   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccPass : TEdit
|
009FDFEB   8B8018030000           mov     eax, [eax+$0318]

* Reference to: Controls.Proc_0094B1D8
|
009FDFF1   E8E2D1F4FF             call    0094B1D8
009FDFF6   FF75A0                 push    dword ptr [ebp-$60]

* Possible String Reference to: '' , mail_addr=''
|
009FDFF9   68C4E49F00             push    $009FE4C4
009FDFFE   8D559C                 lea     edx, [ebp-$64]

* Reference to NewAccountForm
|
009FE001   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccEmail : TEdit
|
009FE004   8B8020030000           mov     eax, [eax+$0320]

* Reference to: Controls.Proc_0094B1D8
|
009FE00A   E8C9D1F4FF             call    0094B1D8
009FE00F   FF759C                 push    dword ptr [ebp-$64]

* Possible String Reference to: '',fpas_ques=''
|
009FE012   68DCE49F00             push    $009FE4DC
009FE017   8D5598                 lea     edx, [ebp-$68]

* Reference to NewAccountForm
|
009FE01A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccQue : TEdit
|
009FE01D   8B801C030000           mov     eax, [eax+$031C]

* Reference to: Controls.Proc_0094B1D8
|
009FE023   E8B0D1F4FF             call    0094B1D8
009FE028   FF7598                 push    dword ptr [ebp-$68]

* Possible String Reference to: '',fpas_answ=''
|
009FE02B   68F4E49F00             push    $009FE4F4
009FE030   8D5594                 lea     edx, [ebp-$6C]

* Reference to NewAccountForm
|
009FE033   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.AccAns : TEdit
|
009FE036   8B8010030000           mov     eax, [eax+$0310]

* Reference to: Controls.Proc_0094B1D8
|
009FE03C   E897D1F4FF             call    0094B1D8
009FE041   FF7594                 push    dword ptr [ebp-$6C]

* Possible String Reference to: '', addr_deta=''
|
009FE044   680CE59F00             push    $009FE50C
009FE049   8D5590                 lea     edx, [ebp-$70]

* Reference to NewAccountForm
|
009FE04C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.personalid : TEdit
|
009FE04F   8B8034030000           mov     eax, [eax+$0334]

* Reference to: Controls.Proc_0094B1D8
|
009FE055   E87ED1F4FF             call    0094B1D8
009FE05A   FF7590                 push    dword ptr [ebp-$70]

* Possible String Reference to: '' where memb___id=''
|
009FE05D   6824E59F00             push    $009FE524

* Reference to NewAccountForm
|
009FE062   8B45FC                 mov     eax, [ebp-$04]
009FE065   FFB040030000           push    dword ptr [eax+$0340]

* Possible String Reference to: '' '
|
009FE06B   6840E59F00             push    $009FE540
009FE070   8D45F8                 lea     eax, [ebp-$08]
009FE073   BA0D000000             mov     edx, $0000000D

* Reference to: System.Proc_00904BAC
|
009FE078   E82F6BF0FF             call    00904BAC
009FE07D   8D458C                 lea     eax, [ebp-$74]
009FE080   8B55F8                 mov     edx, [ebp-$08]

* Reference to: System.Proc_009050F4
|
009FE083   E86C70F0FF             call    009050F4
009FE088   8B558C                 mov     edx, [ebp-$74]

* Reference to TDataModule_Main instance
|
009FE08B   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE090   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
009FE092   8B405C                 mov     eax, [eax+$5C]
009FE095   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TADOCommand.OFFS_38
|
009FE097   FF5138                 call    dword ptr [ecx+$38]
009FE09A   8D5588                 lea     edx, [ebp-$78]

* Reference to TDataModule_Main instance
|
009FE09D   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE0A2   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
009FE0A4   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009920D0
|
009FE0A7   E82440F9FF             call    009920D0
009FE0AC   33C0                   xor     eax, eax
009FE0AE   5A                     pop     edx
009FE0AF   59                     pop     ecx
009FE0B0   59                     pop     ecx
009FE0B1   648910                 mov     fs:[eax], edx
009FE0B4   EB0C                   jmp     009FE0C2
009FE0B6   E90D5EF0FF             jmp     00903EC8
009FE0BB   33DB                   xor     ebx, ebx

* Reference to: System.Proc_009042F4
|
009FE0BD   E83262F0FF             call    009042F4

****** END
|
009FE0C2   80FB01                 cmp     bl, $01
009FE0C5   7512                   jnz     009FE0D9

* Reference to NewAccountForm
|
009FE0C7   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TNewAccountForm.SetModalResultOK : TButton
|
009FE0CA   8B802C030000           mov     eax, [eax+$032C]
009FE0D0   66BEEBFF               mov     si, $FFEB

* Reference to: System.Proc_00903BE4
|
009FE0D4   E80B5BF0FF             call    00903BE4
009FE0D9   33C0                   xor     eax, eax
009FE0DB   5A                     pop     edx
009FE0DC   59                     pop     ecx
009FE0DD   59                     pop     ecx
009FE0DE   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[‹å]Ã'
|
009FE0E1   688AE19F00             push    $009FE18A
009FE0E6   8D4588                 lea     eax, [ebp-$78]

* Reference to: System.Proc_0090690C
|
009FE0E9   E81E88F0FF             call    0090690C
009FE0EE   8D458C                 lea     eax, [ebp-$74]

* Reference to: System.Proc_00904F58
|
009FE0F1   E8626EF0FF             call    00904F58
009FE0F6   8D4590                 lea     eax, [ebp-$70]
009FE0F9   BA05000000             mov     edx, $00000005

* Reference to: System.Proc_00904858
|
009FE0FE   E85567F0FF             call    00904858
009FE103   8D45A4                 lea     eax, [ebp-$5C]

* Reference to: System.Proc_00904F58
|
009FE106   E84D6EF0FF             call    00904F58
009FE10B   8D45A8                 lea     eax, [ebp-$58]

* Reference to: System.Proc_0090690C
|
009FE10E   E8F987F0FF             call    0090690C
009FE113   8D45AC                 lea     eax, [ebp-$54]

* Reference to: System.Proc_00904F58
|
009FE116   E83D6EF0FF             call    00904F58
009FE11B   8D45B0                 lea     eax, [ebp-$50]
009FE11E   BA02000000             mov     edx, $00000002

* Reference to: System.Proc_00904858
|
009FE123   E83067F0FF             call    00904858
009FE128   8D45B8                 lea     eax, [ebp-$48]

* Reference to: System.Proc_0090690C
|
009FE12B   E8DC87F0FF             call    0090690C
009FE130   8D45BC                 lea     eax, [ebp-$44]

* Reference to: System.Proc_00904F58
|
009FE133   E8206EF0FF             call    00904F58
009FE138   8D45C0                 lea     eax, [ebp-$40]

* Reference to: System.Proc_0090690C
|
009FE13B   E8CC87F0FF             call    0090690C
009FE140   8D45C4                 lea     eax, [ebp-$3C]

* Reference to: System.Proc_00904834
|
009FE143   E8EC66F0FF             call    00904834
009FE148   8D45C8                 lea     eax, [ebp-$38]

* Reference to: System.Proc_00904F58
|
009FE14B   E8086EF0FF             call    00904F58
009FE150   8D45CC                 lea     eax, [ebp-$34]
009FE153   BA07000000             mov     edx, $00000007

* Reference to: System.Proc_00904858
|
009FE158   E8FB66F0FF             call    00904858
009FE15D   8D45E8                 lea     eax, [ebp-$18]

* Reference to: System.Proc_00904F58
|
009FE160   E8F36DF0FF             call    00904F58
009FE165   8D45EC                 lea     eax, [ebp-$14]
009FE168   BA02000000             mov     edx, $00000002

* Reference to: System.Proc_00904858
|
009FE16D   E8E666F0FF             call    00904858
009FE172   8D45F4                 lea     eax, [ebp-$0C]
009FE175   BA02000000             mov     edx, $00000002

* Reference to: System.Proc_00904858
|
009FE17A   E8D966F0FF             call    00904858
009FE17F   C3                     ret

009FE180   E9F75FF0FF             jmp     0090417C
009FE185   E95CFFFFFF             jmp     009FE0E6

****** END
|
009FE18A   5F                     pop     edi
009FE18B   5E                     pop     esi
009FE18C   5B                     pop     ebx
009FE18D   8BE5                   mov     esp, ebp
009FE18F   5D                     pop     ebp
009FE190   C3                     ret

*)
end;

procedure TNewAccountForm.personalidKeyPress(Sender : TObject);
begin
(*
009FE910   55                     push    ebp
009FE911   8BEC                   mov     ebp, esp
009FE913   6A00                   push    $00
009FE915   53                     push    ebx
009FE916   8BD9                   mov     ebx, ecx
009FE918   33C0                   xor     eax, eax
009FE91A   55                     push    ebp
009FE91B   685FE99F00             push    $009FE95F
009FE920   64FF30                 push    dword ptr fs:[eax]
009FE923   648920                 mov     fs:[eax], esp
009FE926   8D45FC                 lea     eax, [ebp-$04]
009FE929   8A13                   mov     dl, byte ptr [ebx]

* Reference to: System.Proc_00904A14
|
009FE92B   E8E460F0FF             call    00904A14
009FE930   8B45FC                 mov     eax, [ebp-$04]

* Possible String Reference to: '0123456789'
|
009FE933   BA74E99F00             mov     edx, $009FE974

* Reference to: System.Proc_00904E28
|
009FE938   E8EB64F0FF             call    00904E28
009FE93D   85C0                   test    eax, eax
009FE93F   7F08                   jnle    009FE949
009FE941   803B08                 cmp     byte ptr [ebx], $08
009FE944   7403                   jz      009FE949
009FE946   C60300                 mov     byte ptr [ebx], $00
009FE949   33C0                   xor     eax, eax
009FE94B   5A                     pop     edx
009FE94C   59                     pop     ecx
009FE94D   59                     pop     ecx
009FE94E   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[Y]Ã'
|
009FE951   6866E99F00             push    $009FE966
009FE956   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009FE959   E8D65EF0FF             call    00904834
009FE95E   C3                     ret

009FE95F   E91858F0FF             jmp     0090417C
009FE964   EBF0                   jmp     009FE956

****** END
|
009FE966   5B                     pop     ebx
009FE967   59                     pop     ecx
009FE968   5D                     pop     ebp
009FE969   C3                     ret

*)
end;

procedure TNewAccountForm._PROC_009FE2CA(Sender : TObject);
begin
(*
009FE2CA   45                     inc     ebp
009FE2CB   53                     push    ebx
009FE2CC   2028                   and     [eax], ch
009FE2CE   312C27                 xor     [edi], ebp
009FE2D1   0000                   add     [eax], al

*)
end;

procedure TNewAccountForm._PROC_009FE3B5(Sender : TObject);
begin
(*
009FE3B5   52                     push    edx
009FE3B6   52                     push    edx
009FE3B7   5F                     pop     edi
009FE3B8   49                     dec     ecx
009FE3B9   4E                     dec     esi
009FE3BA   46                     inc     esi
009FE3BB   4F                     dec     edi
009FE3BC   2028                   and     [eax], ch
009FE3BE   656E                   outsb
009FE3C0   64735F                 jnb     009FE422
009FE3C3   6461                   popa
009FE3C5   7973                   jns     009FE43A
009FE3C7   2C63                   sub     al, $63
009FE3C9   68656B5F63             push    $635F6B65
009FE3CE   6F                     outsd
009FE3CF   64652C75               sub     al, $75
009FE3D3   7365                   jnb     009FE43A
009FE3D5   645F                   pop     edi
009FE3D7   7469                   jz      009FE442
009FE3D9   6D                     insd
009FE3DA   652C6D                 sub     al, $6D
009FE3DD   656D                   insd
009FE3DF   625F5F                 bound   ebx, qword ptr [edi+$5F]
009FE3E2   5F                     pop     edi
009FE3E3   69642C6D656D625F       imul    esp, [esp+ebp+$6D], $5F626D65
009FE3EB   6E                     outsb
009FE3EC   61                     popa
009FE3ED   6D                     insd
009FE3EE   65202C6D656D625F       and     gs:[$5F626D65+ebp*2], ch
009FE3F6   677569                 jnz     009FE462
009FE3F9   642C73                 sub     al, $73
009FE3FC   6E                     outsb
009FE3FD   6F                     outsd
009FE3FE   5F                     pop     edi
009FE3FF   5F                     pop     edi
009FE400   6E                     outsb
009FE401   756D                   jnz     009FE470
009FE403   622C42                 bound   ebp, qword ptr [edx+eax*2]
009FE406   696C6C5F53656374       imul    ebp, [esp+ebp*2+$5F], $74636553
009FE40E   696F6E2C42696C         imul    ebp, [edi+$6E], $6C69422C
009FE415   6C                     insb
009FE416   5F                     pop     edi
009FE417   7661                   jbe     009FE47A
009FE419   6C                     insb
009FE41A   7565                   jnz     009FE481
009FE41C   2C42                   sub     al, $42
009FE41E   696C6C5F486F7572       imul    ebp, [esp+ebp*2+$5F], $72756F48
009FE426   2C53                   sub     al, $53
009FE428   7572                   jnz     009FE49C
009FE42A   706C                   jo      009FE498
009FE42C   7573                   jnz     009FE4A1
009FE42E   5F                     pop     edi
009FE42F   50                     push    eax
009FE430   6F                     outsd
009FE431   696E742C537572         imul    ebp, [esi+$74], $7275532C
009FE438   706C                   jo      009FE4A6
009FE43A   7573                   jnz     009FE4AF
009FE43C   5F                     pop     edi
009FE43D   4D                     dec     ebp
009FE43E   696E7574652C49         imul    ebp, [esi+$75], $492C6574
009FE445   6E                     outsb
009FE446   637265                 arpl    [edx+$65], si
009FE449   61                     popa
009FE44A   7365                   jnb     009FE4B1
009FE44C   5F                     pop     edi
009FE44D   44                     inc     esp
009FE44E   61                     popa
009FE44F   7973                   jns     009FE4C4
009FE451   2920                   sub     dword ptr [eax], esp
009FE453   56                     push    esi
009FE454   41                     inc     ecx
009FE455   4C                     dec     esp
009FE456   55                     push    ebp
009FE457   45                     inc     ebp
009FE458   53                     push    ebx
009FE459   2028                   and     [eax], ch
009FE45B   3230                   xor     dh, byte ptr [eax]
009FE45D   30352C312C31           xor     [$312C312C], dh
009FE463   3233                   xor     dh, byte ptr [ebx]
009FE465   342C                   xor     al, $2C
009FE467   27                     daa
009FE468   0000                   add     [eax], al

009FE46A   0000                   add     [eax], al

009FE46C   FFFF                   DB  $FF, $FF  //      
009FE46E   FFFF                   DB  $FF, $FF  //      
009FE470   1900                   sbb     [eax], eax
009FE472   0000                   add     [eax], al

009FE474   27                     daa
009FE475   2C31                   sub     al, $31
009FE477   2C37                   sub     al, $37
009FE479   2C36                   sub     al, $36
009FE47B   2C33                   sub     al, $33
009FE47D   2C36                   sub     al, $36
009FE47F   2C36                   sub     al, $36
009FE481   2C32                   sub     al, $32
009FE483   3030                   xor     [eax], dh
009FE485   342D                   xor     al, $2D
009FE487   312D312C3029           xor     [$29302C31], ebp
009FE48D   0000                   add     [eax], al

009FE48F   00FF                   add     bh, bh
009FE491   FFFF                   DB  $FF, $FF  //      
009FE493   FF20                   jmp     dword ptr [eax]
009FE495   0000                   add     [eax], al

009FE497   007570                 add     [ebp+$70], dh
009FE49A   6461                   popa
009FE49C   7465                   jz      009FE503
009FE49E   206D65                 and     [ebp+$65], ch
009FE4A1   6D                     insd
009FE4A2   625F69                 bound   ebx, qword ptr [edi+$69]
009FE4A5   6E                     outsb
009FE4A6   666F                   outsw
009FE4A8   207365                 and     [ebx+$65], dh
009FE4AB   7420                   jz      009FE4CD
009FE4AD   6D                     insd
009FE4AE   656D                   insd
009FE4B0   625F5F                 bound   ebx, qword ptr [edi+$5F]
009FE4B3   7077                   jo      009FE52C
009FE4B5   643D27000000           cmp     eax, $00000027
009FE4BB   00FF                   add     bh, bh
009FE4BD   FFFF                   DB  $FF, $FF  //      
009FE4BF   FF0F                   dec     dword ptr [edi]
009FE4C1   0000                   add     [eax], al

009FE4C3   0027                   add     [edi], ah
009FE4C5   202C20                 and     [eax], ch
009FE4C8   6D                     insd
009FE4C9   61                     popa
009FE4CA   696C5F616464723D       imul    ebp, [edi+ebx*2+$61], $3D726464
009FE4D2   27                     daa
009FE4D3   00FF                   add     bh, bh
009FE4D5   FFFF                   DB  $FF, $FF  //      
009FE4D7   FF0D00000027           dec     dword ptr [$27000000]
009FE4DD   2C66                   sub     al, $66
009FE4DF   7061                   jo      009FE542
009FE4E1   735F                   jnb     009FE542
009FE4E3   7175                   jno     009FE55A
009FE4E5   65733D                 jnb     009FE525
009FE4E8   27                     daa
009FE4E9   0000                   add     [eax], al

009FE4EB   00FF                   add     bh, bh
009FE4ED   FFFF                   DB  $FF, $FF  //      
009FE4EF   FF0D00000027           dec     dword ptr [$27000000]
009FE4F5   2C66                   sub     al, $66
009FE4F7   7061                   jo      009FE55A
009FE4F9   735F                   jnb     009FE55A
009FE4FB   61                     popa
009FE4FC   6E                     outsb
009FE4FD   7377                   jnb     009FE576
009FE4FF   3D27000000             cmp     eax, $00000027
009FE504   FFFF                   DB  $FF, $FF  //      
009FE506   FFFF                   DB  $FF, $FF  //      
009FE508   0E                     push    cs
009FE509   0000                   add     [eax], al

009FE50B   0027                   add     [edi], ah
009FE50D   2C20                   sub     al, $20
009FE50F   61                     popa
009FE510   6464725F               jb      009FE573
009FE514   64657461               jz      009FE579
009FE518   3D270000FF             cmp     eax, $FF000027
009FE51D   FFFF                   DB  $FF, $FF  //      
009FE51F   FF13                   call    dword ptr [ebx]
009FE521   0000                   add     [eax], al

009FE523   0027                   add     [edi], ah
009FE525   207768                 and     [edi+$68], dh
009FE528   657265                 jb      009FE590
009FE52B   206D65                 and     [ebp+$65], ch
009FE52E   6D                     insd
009FE52F   625F5F                 bound   ebx, qword ptr [edi+$5F]
009FE532   5F                     pop     edi
009FE533   69643D2700FFFFFF       imul    esp, [ebp+edi+$27], $FFFFFF00
009FE53B   FF02                   inc     dword ptr [edx]
009FE53D   0000                   add     [eax], al

009FE53F   0027                   add     [edi], ah
009FE541   2000                   and     [eax], al
009FE543   00558B                 add     [ebp-$75], dl
009FE546   EC                     in      al, dx
009FE547   33C9                   xor     ecx, ecx
009FE549   51                     push    ecx
009FE54A   51                     push    ecx
009FE54B   51                     push    ecx
009FE54C   51                     push    ecx
009FE54D   51                     push    ecx
009FE54E   51                     push    ecx
009FE54F   51                     push    ecx
009FE550   51                     push    ecx
009FE551   53                     push    ebx
009FE552   56                     push    esi
009FE553   57                     push    edi
009FE554   8BF8                   mov     edi, eax
009FE556   33C0                   xor     eax, eax
009FE558   55                     push    ebp

* Possible String Reference to: 'é%Yðÿëë‹Ã_^[‹å]Ã'
|
009FE559   6852E89F00             push    $009FE852
009FE55E   64FF30                 push    dword ptr fs:[eax]
009FE561   648920                 mov     fs:[eax], esp
009FE564   33D2                   xor     edx, edx
009FE566   55                     push    ebp
009FE567   682BE89F00             push    $009FE82B
009FE56C   64FF32                 push    dword ptr fs:[edx]
009FE56F   648922                 mov     fs:[edx], esp
009FE572   80BF3C03000000         cmp     byte ptr [edi+$033C], $00
009FE579   747B                   jz      009FE5F6
009FE57B   8B8724030000           mov     eax, [edi+$0324]
009FE581   33D2                   xor     edx, edx

* Reference to: Controls.Proc_0094B208
|
009FE583   E880CCF4FF             call    0094B208
009FE588   8B8718030000           mov     eax, [edi+$0318]
009FE58E   33D2                   xor     edx, edx

* Reference to: Controls.Proc_0094B208
|
009FE590   E873CCF4FF             call    0094B208
009FE595   8B8714030000           mov     eax, [edi+$0314]
009FE59B   33D2                   xor     edx, edx

* Reference to: Controls.Proc_0094B208
|
009FE59D   E866CCF4FF             call    0094B208
009FE5A2   8B8720030000           mov     eax, [edi+$0320]
009FE5A8   33D2                   xor     edx, edx

* Reference to: Controls.Proc_0094B208
|
009FE5AA   E859CCF4FF             call    0094B208
009FE5AF   8B871C030000           mov     eax, [edi+$031C]
009FE5B5   33D2                   xor     edx, edx

* Reference to: Controls.Proc_0094B208
|
009FE5B7   E84CCCF4FF             call    0094B208
009FE5BC   8B8710030000           mov     eax, [edi+$0310]
009FE5C2   33D2                   xor     edx, edx

* Reference to: Controls.Proc_0094B208
|
009FE5C4   E83FCCF4FF             call    0094B208

* Possible String Reference to: 'New Account'
|
009FE5C9   BA6CE89F00             mov     edx, $009FE86C
009FE5CE   8BC7                   mov     eax, edi

* Reference to: Controls.Proc_0094B208
|
009FE5D0   E833CCF4FF             call    0094B208
009FE5D5   8B8724030000           mov     eax, [edi+$0324]
009FE5DB   B201                   mov     dl, $01
009FE5DD   8B08                   mov     ecx, [eax]
009FE5DF   FF5164                 call    dword ptr [ecx+$64]
009FE5E2   B301                   mov     bl, $01
009FE5E4   8B8734030000           mov     eax, [edi+$0334]
009FE5EA   33D2                   xor     edx, edx

* Reference to: Controls.Proc_0094B208
|
009FE5EC   E817CCF4FF             call    0094B208
009FE5F1   E92B020000             jmp     009FE821
009FE5F6   83BF4003000000         cmp     dword ptr [edi+$0340], +$00
009FE5FD   7507                   jnz     009FE606
009FE5FF   33DB                   xor     ebx, ebx
009FE601   E91B020000             jmp     009FE821

* Possible String Reference to: 'Edit Acc'
|
009FE606   BA80E89F00             mov     edx, $009FE880
009FE60B   8BC7                   mov     eax, edi

* Reference to: Controls.Proc_0094B208
|
009FE60D   E8F6CBF4FF             call    0094B208
009FE612   8B8724030000           mov     eax, [edi+$0324]
009FE618   33D2                   xor     edx, edx
009FE61A   8B08                   mov     ecx, [eax]
009FE61C   FF5164                 call    dword ptr [ecx+$64]

* Reference to TDataModule_Main instance
|
009FE61F   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE624   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE626   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FE629   E88E7FF8FF             call    009865BC

* Reference to TDataModule_Main instance
|
009FE62E   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE633   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE635   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FE638   E87BBDF9FF             call    0099A3B8
009FE63D   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_44
|
009FE63F   FF5244                 call    dword ptr [edx+$44]

* Reference to TDataModule_Main instance
|
009FE642   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE647   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE649   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FE64C   E867BDF9FF             call    0099A3B8
009FE651   50                     push    eax

* Possible String Reference to: 'select memb___id,memb__pwd,memb_nam
|                                e,mail_addr,fpas_ques,fpas_answ, ad
|                                dr_deta from memb_info where memb__
|                                _id=''
|
009FE652   6894E89F00             push    $009FE894
009FE657   FFB740030000           push    dword ptr [edi+$0340]
009FE65D   680CE99F00             push    $009FE90C
009FE662   8D45FC                 lea     eax, [ebp-$04]
009FE665   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904BAC
|
009FE66A   E83D65F0FF             call    00904BAC
009FE66F   8B55FC                 mov     edx, [ebp-$04]
009FE672   58                     pop     eax
009FE673   8B08                   mov     ecx, [eax]
009FE675   FF5138                 call    dword ptr [ecx+$38]

* Reference to TDataModule_Main instance
|
009FE678   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE67D   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE67F   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
009FE682   E8297FF8FF             call    009865B0

* Reference to TDataModule_Main instance
|
009FE687   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE68C   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE68E   8B4060                 mov     eax, [eax+$60]
009FE691   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_014C
|
009FE693   FF924C010000           call    dword ptr [edx+$014C]
009FE699   8BF0                   mov     esi, eax
009FE69B   83EE01                 sub     esi, +$01
009FE69E   7105                   jno     009FE6A5

* Reference to: System.Proc_00903928
|
009FE6A0   E88352F0FF             call    00903928
009FE6A5   85F6                   test    esi, esi
009FE6A7   0F8C4F010000           jl      009FE7FC
009FE6AD   46                     inc     esi

* Reference to TDataModule_Main instance
|
009FE6AE   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE6B3   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE6B5   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FE6B8   8B4030                 mov     eax, [eax+$30]
009FE6BB   33D2                   xor     edx, edx

* Reference to: DB.Proc_0097CB48
|
009FE6BD   E886E4F7FF             call    0097CB48
009FE6C2   8D55F8                 lea     edx, [ebp-$08]
009FE6C5   8B08                   mov     ecx, [eax]
009FE6C7   FF5160                 call    dword ptr [ecx+$60]
009FE6CA   8B55F8                 mov     edx, [ebp-$08]
009FE6CD   8B8724030000           mov     eax, [edi+$0324]

* Reference to: Controls.Proc_0094B208
|
009FE6D3   E830CBF4FF             call    0094B208

* Reference to TDataModule_Main instance
|
009FE6D8   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE6DD   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE6DF   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FE6E2   8B4030                 mov     eax, [eax+$30]
009FE6E5   BA01000000             mov     edx, $00000001

* Reference to: DB.Proc_0097CB48
|
009FE6EA   E859E4F7FF             call    0097CB48
009FE6EF   8D55F4                 lea     edx, [ebp-$0C]
009FE6F2   8B08                   mov     ecx, [eax]
009FE6F4   FF5160                 call    dword ptr [ecx+$60]
009FE6F7   8B55F4                 mov     edx, [ebp-$0C]
009FE6FA   8B8718030000           mov     eax, [edi+$0318]

* Reference to: Controls.Proc_0094B208
|
009FE700   E803CBF4FF             call    0094B208

* Reference to TDataModule_Main instance
|
009FE705   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE70A   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE70C   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FE70F   8B4030                 mov     eax, [eax+$30]
009FE712   BA02000000             mov     edx, $00000002

* Reference to: DB.Proc_0097CB48
|
009FE717   E82CE4F7FF             call    0097CB48
009FE71C   8D55F0                 lea     edx, [ebp-$10]
009FE71F   8B08                   mov     ecx, [eax]
009FE721   FF5160                 call    dword ptr [ecx+$60]
009FE724   8B55F0                 mov     edx, [ebp-$10]
009FE727   8B8714030000           mov     eax, [edi+$0314]

* Reference to: Controls.Proc_0094B208
|
009FE72D   E8D6CAF4FF             call    0094B208

* Reference to TDataModule_Main instance
|
009FE732   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE737   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE739   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FE73C   8B4030                 mov     eax, [eax+$30]
009FE73F   BA03000000             mov     edx, $00000003

* Reference to: DB.Proc_0097CB48
|
009FE744   E8FFE3F7FF             call    0097CB48
009FE749   8D55EC                 lea     edx, [ebp-$14]
009FE74C   8B08                   mov     ecx, [eax]
009FE74E   FF5160                 call    dword ptr [ecx+$60]
009FE751   8B55EC                 mov     edx, [ebp-$14]
009FE754   8B8720030000           mov     eax, [edi+$0320]

* Reference to: Controls.Proc_0094B208
|
009FE75A   E8A9CAF4FF             call    0094B208

* Reference to TDataModule_Main instance
|
009FE75F   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE764   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE766   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FE769   8B4030                 mov     eax, [eax+$30]
009FE76C   BA04000000             mov     edx, $00000004

* Reference to: DB.Proc_0097CB48
|
009FE771   E8D2E3F7FF             call    0097CB48
009FE776   8D55E8                 lea     edx, [ebp-$18]
009FE779   8B08                   mov     ecx, [eax]
009FE77B   FF5160                 call    dword ptr [ecx+$60]
009FE77E   8B55E8                 mov     edx, [ebp-$18]
009FE781   8B871C030000           mov     eax, [edi+$031C]

* Reference to: Controls.Proc_0094B208
|
009FE787   E87CCAF4FF             call    0094B208

* Reference to TDataModule_Main instance
|
009FE78C   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE791   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE793   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FE796   8B4030                 mov     eax, [eax+$30]
009FE799   BA05000000             mov     edx, $00000005

* Reference to: DB.Proc_0097CB48
|
009FE79E   E8A5E3F7FF             call    0097CB48
009FE7A3   8D55E4                 lea     edx, [ebp-$1C]
009FE7A6   8B08                   mov     ecx, [eax]
009FE7A8   FF5160                 call    dword ptr [ecx+$60]
009FE7AB   8B55E4                 mov     edx, [ebp-$1C]
009FE7AE   8B8710030000           mov     eax, [edi+$0310]

* Reference to: Controls.Proc_0094B208
|
009FE7B4   E84FCAF4FF             call    0094B208

* Reference to TDataModule_Main instance
|
009FE7B9   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE7BE   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE7C0   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FE7C3   8B4030                 mov     eax, [eax+$30]
009FE7C6   BA06000000             mov     edx, $00000006

* Reference to: DB.Proc_0097CB48
|
009FE7CB   E878E3F7FF             call    0097CB48
009FE7D0   8D55E0                 lea     edx, [ebp-$20]
009FE7D3   8B08                   mov     ecx, [eax]
009FE7D5   FF5160                 call    dword ptr [ecx+$60]
009FE7D8   8B55E0                 mov     edx, [ebp-$20]
009FE7DB   8B8734030000           mov     eax, [edi+$0334]

* Reference to: Controls.Proc_0094B208
|
009FE7E1   E822CAF4FF             call    0094B208

* Reference to TDataModule_Main instance
|
009FE7E6   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE7EB   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE7ED   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_00988BD0
|
009FE7F0   E8DBA3F8FF             call    00988BD0
009FE7F5   4E                     dec     esi
009FE7F6   0F85B2FEFFFF           jnz     009FE6AE
009FE7FC   B301                   mov     bl, $01

* Reference to TDataModule_Main instance
|
009FE7FE   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE803   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE805   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FE808   E8AF7DF8FF             call    009865BC

* Reference to TDataModule_Main instance
|
009FE80D   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FE812   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FE814   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FE817   E89CBBF9FF             call    0099A3B8
009FE81C   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_44
|
009FE81E   FF5244                 call    dword ptr [edx+$44]
009FE821   33C0                   xor     eax, eax
009FE823   5A                     pop     edx
009FE824   59                     pop     ecx
009FE825   59                     pop     ecx
009FE826   648910                 mov     fs:[eax], edx
009FE829   EB0C                   jmp     009FE837
009FE82B   E99856F0FF             jmp     00903EC8
009FE830   33DB                   xor     ebx, ebx

* Reference to: System.Proc_009042F4
|
009FE832   E8BD5AF0FF             call    009042F4

****** END
|
009FE837   33C0                   xor     eax, eax
009FE839   5A                     pop     edx
009FE83A   59                     pop     ecx
009FE83B   59                     pop     ecx
009FE83C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '‹Ã_^[‹å]Ã'
|
009FE83F   6859E89F00             push    $009FE859
009FE844   8D45E0                 lea     eax, [ebp-$20]
009FE847   BA08000000             mov     edx, $00000008

* Reference to: System.Proc_00904858
|
009FE84C   E80760F0FF             call    00904858
009FE851   C3                     ret

*)
end;

procedure TNewAccountForm._PROC_009FE852(Sender : TObject);
begin
(*
009FE852   E92559F0FF             jmp     0090417C
009FE857   EBEB                   jmp     009FE844
009FE859   8BC3                   mov     eax, ebx
009FE85B   5F                     pop     edi
009FE85C   5E                     pop     esi
009FE85D   5B                     pop     ebx
009FE85E   8BE5                   mov     esp, ebp
009FE860   5D                     pop     ebp
009FE861   C3                     ret

*)
end;

procedure TNewAccountForm._PROC_009FE981(Sender : TObject);
begin
(*
009FE981   8BEC                   mov     ebp, esp
009FE983   33C0                   xor     eax, eax
009FE985   55                     push    ebp

* Possible String Reference to: 'éÒWðÿëø]Ã‹Àƒ-ì ¡'
|
009FE986   68A5E99F00             push    $009FE9A5
009FE98B   64FF30                 push    dword ptr fs:[eax]
009FE98E   648920                 mov     fs:[eax], esp
009FE991   FF05EC20A100           inc     dword ptr [$00A120EC]
009FE997   33C0                   xor     eax, eax
009FE999   5A                     pop     edx
009FE99A   59                     pop     ecx
009FE99B   59                     pop     ecx
009FE99C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-ì ¡'
|
009FE99F   68ACE99F00             push    $009FE9AC
009FE9A4   C3                     ret

009FE9A5   E9D257F0FF             jmp     0090417C
009FE9AA   EBF8                   jmp     009FE9A4

****** END
|
009FE9AC   5D                     pop     ebp
009FE9AD   C3                     ret

*)
end;

procedure TNewAccountForm._PROC_009FE9B0(Sender : TObject);
begin
(*
009FE9B0   832DEC20A10001         sub     dword ptr [$00A120EC], +$01
009FE9B7   C3                     ret

*)
end;

end.