unit progressunit;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TProgressbarform=class(TForm)
    Progress: TGauge;
    procedure _PROC_00A03F68(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Progressbarform: TProgressbarform;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TProgressbarform._PROC_00A03F68(Sender : TObject);
begin
(*
00A03F68   832D4421A10001         sub     dword ptr [$00A12144], +$01
00A03F6F   C3                     ret

*)
end;

end.