unit ShowUsersUnit;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TShowUsersForm=class(TForm)
    Label39: TLabel;
    CUListBox: TListBox;
    ServerNameEdit: TLabeledEdit;
    ConTMEdit: TLabeledEdit;
    DiscnTMEdit: TLabeledEdit;
    IPEdit: TLabeledEdit;
    ShowAll: TCheckBox;
    CharacterShow: TLabeledEdit;
    addToRemembered: TSpeedButton;
    BitBtn1: TBitBtn;
    SpeedButton1: TSpeedButton;
    procedure CUListBoxClick(Sender : TObject);
    procedure FormKeyPress(Sender : TObject);
    procedure addToRememberedClick(Sender : TObject);
    procedure BitBtn1Click(Sender : TObject);
    procedure SpeedButton1Click(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure _PROC_009FCE3D(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  ShowUsersForm: TShowUsersForm;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TShowUsersForm.CUListBoxClick(Sender : TObject);
begin
(*
009FC858   55                     push    ebp
009FC859   8BEC                   mov     ebp, esp
009FC85B   B906000000             mov     ecx, $00000006
009FC860   6A00                   push    $00
009FC862   6A00                   push    $00
009FC864   49                     dec     ecx
009FC865   75F9                   jnz     009FC860
009FC867   51                     push    ecx
009FC868   53                     push    ebx
009FC869   56                     push    esi
009FC86A   57                     push    edi
009FC86B   8BD8                   mov     ebx, eax

* Reference to TDataModule_Main instance
|
009FC86D   8B358CFBA000           mov     esi, [$00A0FB8C]
009FC873   33C0                   xor     eax, eax
009FC875   55                     push    ebp

* Possible String Reference to: 'é uðÿëë_^[‹å]Ã'
|
009FC876   68D7CB9F00             push    $009FCBD7
009FC87B   64FF30                 push    dword ptr fs:[eax]
009FC87E   648920                 mov     fs:[eax], esp

* Reference to control TShowUsersForm.CUListBox : TListBox
|
009FC881   8B83F4020000           mov     eax, [ebx+$02F4]
009FC887   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FC889   FF92C8000000           call    dword ptr [edx+$00C8]
009FC88F   85C0                   test    eax, eax
009FC891   0F9DC2                 setnl   dl

* Reference to control TShowUsersForm.addToRemembered : TSpeedButton
|
009FC894   8B8310030000           mov     eax, [ebx+$0310]
009FC89A   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TSpeedButton.OFFS_64
|
009FC89C   FF5164                 call    dword ptr [ecx+$64]
009FC89F   8B06                   mov     eax, [esi]
009FC8A1   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FC8A4   E8139DF8FF             call    009865BC
009FC8A9   8B06                   mov     eax, [esi]
009FC8AB   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FC8AE   E805DBF9FF             call    0099A3B8
009FC8B3   8B10                   mov     edx, [eax]
009FC8B5   FF5244                 call    dword ptr [edx+$44]

* Possible String Reference to: 'select ServerName, IP, ConnectTM, D
|                                isconnectTM, GameIDC from MEMB_STAT
|                                 full join AccountCharacter on memb
|                                ___id = Id full join Character on N
|                                ame = GameIDC where (ConnectStat = 
|                                '1') and (memb___id=''
|
009FC8B8   68F0CB9F00             push    $009FCBF0

* Reference to control TShowUsersForm.CUListBox : TListBox
|
009FC8BD   8B83F4020000           mov     eax, [ebx+$02F4]
009FC8C3   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FC8C5   FF92C8000000           call    dword ptr [edx+$00C8]
009FC8CB   8BD0                   mov     edx, eax
009FC8CD   8D4DF8                 lea     ecx, [ebp-$08]

* Reference to control TShowUsersForm.CUListBox : TListBox
|
009FC8D0   8B83F4020000           mov     eax, [ebx+$02F4]

* Reference to field TListBox.OFFS_0218
|
009FC8D6   8B8018020000           mov     eax, [eax+$0218]
009FC8DC   8B38                   mov     edi, [eax]
009FC8DE   FF570C                 call    dword ptr [edi+$0C]
009FC8E1   FF75F8                 push    dword ptr [ebp-$08]

* Possible String Reference to: '') order by cLevel desc'
|
009FC8E4   68C0CC9F00             push    $009FCCC0
009FC8E9   8D45FC                 lea     eax, [ebp-$04]
009FC8EC   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904BAC
|
009FC8F1   E8B682F0FF             call    00904BAC
009FC8F6   8B45FC                 mov     eax, [ebp-$04]
009FC8F9   50                     push    eax
009FC8FA   8B06                   mov     eax, [esi]
009FC8FC   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FC8FF   E8B4DAF9FF             call    0099A3B8
009FC904   5A                     pop     edx
009FC905   8B08                   mov     ecx, [eax]
009FC907   FF5138                 call    dword ptr [ecx+$38]
009FC90A   8B06                   mov     eax, [esi]
009FC90C   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
009FC90F   E89C9CF8FF             call    009865B0
009FC914   8B06                   mov     eax, [esi]
009FC916   8B4060                 mov     eax, [eax+$60]
009FC919   8B10                   mov     edx, [eax]
009FC91B   FF924C010000           call    dword ptr [edx+$014C]
009FC921   85C0                   test    eax, eax
009FC923   0F8E16010000           jle     009FCA3F
009FC929   8B06                   mov     eax, [esi]
009FC92B   8B4060                 mov     eax, [eax+$60]
009FC92E   8B10                   mov     edx, [eax]
009FC930   FF924C010000           call    dword ptr [edx+$014C]
009FC936   8BF8                   mov     edi, eax
009FC938   83EF01                 sub     edi, +$01
009FC93B   7105                   jno     009FC942

* Reference to: System.Proc_00903928
|
009FC93D   E8E66FF0FF             call    00903928
009FC942   85FF                   test    edi, edi
009FC944   0F8CD7000000           jl      009FCA21
009FC94A   47                     inc     edi
009FC94B   8B06                   mov     eax, [esi]
009FC94D   8B4060                 mov     eax, [eax+$60]
009FC950   8B4030                 mov     eax, [eax+$30]
009FC953   33D2                   xor     edx, edx

* Reference to: DB.Proc_0097CB48
|
009FC955   E8EE01F8FF             call    0097CB48
009FC95A   8D55F4                 lea     edx, [ebp-$0C]
009FC95D   8B08                   mov     ecx, [eax]
009FC95F   FF5160                 call    dword ptr [ecx+$60]
009FC962   8B55F4                 mov     edx, [ebp-$0C]

* Reference to control TShowUsersForm.ServerNameEdit : TLabeledEdit
|
009FC965   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to: Controls.Proc_0094B208
|
009FC96B   E898E8F4FF             call    0094B208
009FC970   8B06                   mov     eax, [esi]
009FC972   8B4060                 mov     eax, [eax+$60]
009FC975   8B4030                 mov     eax, [eax+$30]
009FC978   BA01000000             mov     edx, $00000001

* Reference to: DB.Proc_0097CB48
|
009FC97D   E8C601F8FF             call    0097CB48
009FC982   8D55F0                 lea     edx, [ebp-$10]
009FC985   8B08                   mov     ecx, [eax]
009FC987   FF5160                 call    dword ptr [ecx+$60]
009FC98A   8B55F0                 mov     edx, [ebp-$10]

* Reference to control TShowUsersForm.IPEdit : TLabeledEdit
|
009FC98D   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Controls.Proc_0094B208
|
009FC993   E870E8F4FF             call    0094B208
009FC998   8B06                   mov     eax, [esi]
009FC99A   8B4060                 mov     eax, [eax+$60]
009FC99D   8B4030                 mov     eax, [eax+$30]
009FC9A0   BA02000000             mov     edx, $00000002

* Reference to: DB.Proc_0097CB48
|
009FC9A5   E89E01F8FF             call    0097CB48
009FC9AA   8D55EC                 lea     edx, [ebp-$14]
009FC9AD   8B08                   mov     ecx, [eax]
009FC9AF   FF5160                 call    dword ptr [ecx+$60]
009FC9B2   8B55EC                 mov     edx, [ebp-$14]

* Reference to control TShowUsersForm.ConTMEdit : TLabeledEdit
|
009FC9B5   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to: Controls.Proc_0094B208
|
009FC9BB   E848E8F4FF             call    0094B208
009FC9C0   8B06                   mov     eax, [esi]
009FC9C2   8B4060                 mov     eax, [eax+$60]
009FC9C5   8B4030                 mov     eax, [eax+$30]
009FC9C8   BA03000000             mov     edx, $00000003

* Reference to: DB.Proc_0097CB48
|
009FC9CD   E87601F8FF             call    0097CB48
009FC9D2   8D55E8                 lea     edx, [ebp-$18]
009FC9D5   8B08                   mov     ecx, [eax]
009FC9D7   FF5160                 call    dword ptr [ecx+$60]
009FC9DA   8B55E8                 mov     edx, [ebp-$18]

* Reference to control TShowUsersForm.DiscnTMEdit : TLabeledEdit
|
009FC9DD   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: Controls.Proc_0094B208
|
009FC9E3   E820E8F4FF             call    0094B208
009FC9E8   8B06                   mov     eax, [esi]
009FC9EA   8B4060                 mov     eax, [eax+$60]
009FC9ED   8B4030                 mov     eax, [eax+$30]
009FC9F0   BA04000000             mov     edx, $00000004

* Reference to: DB.Proc_0097CB48
|
009FC9F5   E84E01F8FF             call    0097CB48
009FC9FA   8D55E4                 lea     edx, [ebp-$1C]
009FC9FD   8B08                   mov     ecx, [eax]
009FC9FF   FF5160                 call    dword ptr [ecx+$60]
009FCA02   8B55E4                 mov     edx, [ebp-$1C]

* Reference to control TShowUsersForm.CharacterShow : TLabeledEdit
|
009FCA05   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.Proc_0094B208
|
009FCA0B   E8F8E7F4FF             call    0094B208
009FCA10   8B06                   mov     eax, [esi]
009FCA12   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_00988BD0
|
009FCA15   E8B6C1F8FF             call    00988BD0
009FCA1A   4F                     dec     edi
009FCA1B   0F852AFFFFFF           jnz     009FC94B
009FCA21   8B06                   mov     eax, [esi]
009FCA23   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FCA26   E8919BF8FF             call    009865BC
009FCA2B   8B06                   mov     eax, [esi]
009FCA2D   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FCA30   E883D9F9FF             call    0099A3B8
009FCA35   8B10                   mov     edx, [eax]
009FCA37   FF5244                 call    dword ptr [edx+$44]
009FCA3A   E97D010000             jmp     009FCBBC

* Possible String Reference to: 'Not Conected'
|
009FCA3F   BAE0CC9F00             mov     edx, $009FCCE0

* Reference to control TShowUsersForm.CharacterShow : TLabeledEdit
|
009FCA44   8B830C030000           mov     eax, [ebx+$030C]

* Reference to: Controls.Proc_0094B208
|
009FCA4A   E8B9E7F4FF             call    0094B208
009FCA4F   8B06                   mov     eax, [esi]
009FCA51   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FCA54   E8639BF8FF             call    009865BC
009FCA59   8B06                   mov     eax, [esi]
009FCA5B   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FCA5E   E855D9F9FF             call    0099A3B8
009FCA63   8B10                   mov     edx, [eax]
009FCA65   FF5244                 call    dword ptr [edx+$44]
009FCA68   8B06                   mov     eax, [esi]
009FCA6A   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FCA6D   E846D9F9FF             call    0099A3B8
009FCA72   8B10                   mov     edx, [eax]
009FCA74   FF5244                 call    dword ptr [edx+$44]

* Possible String Reference to: 'select ServerName,IP,ConnectTM,Disc
|                                onnectTM from memb_stat where memb_
|                                __id=''
|
009FCA77   68F8CC9F00             push    $009FCCF8

* Reference to control TShowUsersForm.CUListBox : TListBox
|
009FCA7C   8B83F4020000           mov     eax, [ebx+$02F4]
009FCA82   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FCA84   FF92C8000000           call    dword ptr [edx+$00C8]
009FCA8A   8BD0                   mov     edx, eax
009FCA8C   8D4DDC                 lea     ecx, [ebp-$24]

* Reference to control TShowUsersForm.CUListBox : TListBox
|
009FCA8F   8B83F4020000           mov     eax, [ebx+$02F4]

* Reference to field TListBox.OFFS_0218
|
009FCA95   8B8018020000           mov     eax, [eax+$0218]
009FCA9B   8B38                   mov     edi, [eax]
009FCA9D   FF570C                 call    dword ptr [edi+$0C]
009FCAA0   FF75DC                 push    dword ptr [ebp-$24]

* Possible String Reference to: '' '
|
009FCAA3   6850CD9F00             push    $009FCD50
009FCAA8   8D45E0                 lea     eax, [ebp-$20]
009FCAAB   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904BAC
|
009FCAB0   E8F780F0FF             call    00904BAC
009FCAB5   8B45E0                 mov     eax, [ebp-$20]
009FCAB8   50                     push    eax
009FCAB9   8B06                   mov     eax, [esi]
009FCABB   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FCABE   E8F5D8F9FF             call    0099A3B8
009FCAC3   5A                     pop     edx
009FCAC4   8B08                   mov     ecx, [eax]
009FCAC6   FF5138                 call    dword ptr [ecx+$38]
009FCAC9   8B06                   mov     eax, [esi]
009FCACB   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
009FCACE   E8DD9AF8FF             call    009865B0
009FCAD3   8B06                   mov     eax, [esi]
009FCAD5   8B4060                 mov     eax, [eax+$60]
009FCAD8   8B10                   mov     edx, [eax]
009FCADA   FF924C010000           call    dword ptr [edx+$014C]
009FCAE0   8BF8                   mov     edi, eax
009FCAE2   83EF01                 sub     edi, +$01
009FCAE5   7105                   jno     009FCAEC

* Reference to: System.Proc_00903928
|
009FCAE7   E83C6EF0FF             call    00903928
009FCAEC   85FF                   test    edi, edi
009FCAEE   0F8CAF000000           jl      009FCBA3
009FCAF4   47                     inc     edi
009FCAF5   8B06                   mov     eax, [esi]
009FCAF7   8B4060                 mov     eax, [eax+$60]
009FCAFA   8B4030                 mov     eax, [eax+$30]
009FCAFD   33D2                   xor     edx, edx

* Reference to: DB.Proc_0097CB48
|
009FCAFF   E84400F8FF             call    0097CB48
009FCB04   8D55D8                 lea     edx, [ebp-$28]
009FCB07   8B08                   mov     ecx, [eax]
009FCB09   FF5160                 call    dword ptr [ecx+$60]
009FCB0C   8B55D8                 mov     edx, [ebp-$28]

* Reference to control TShowUsersForm.ServerNameEdit : TLabeledEdit
|
009FCB0F   8B83F8020000           mov     eax, [ebx+$02F8]

* Reference to: Controls.Proc_0094B208
|
009FCB15   E8EEE6F4FF             call    0094B208
009FCB1A   8B06                   mov     eax, [esi]
009FCB1C   8B4060                 mov     eax, [eax+$60]
009FCB1F   8B4030                 mov     eax, [eax+$30]
009FCB22   BA01000000             mov     edx, $00000001

* Reference to: DB.Proc_0097CB48
|
009FCB27   E81C00F8FF             call    0097CB48
009FCB2C   8D55D4                 lea     edx, [ebp-$2C]
009FCB2F   8B08                   mov     ecx, [eax]
009FCB31   FF5160                 call    dword ptr [ecx+$60]
009FCB34   8B55D4                 mov     edx, [ebp-$2C]

* Reference to control TShowUsersForm.IPEdit : TLabeledEdit
|
009FCB37   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Controls.Proc_0094B208
|
009FCB3D   E8C6E6F4FF             call    0094B208
009FCB42   8B06                   mov     eax, [esi]
009FCB44   8B4060                 mov     eax, [eax+$60]
009FCB47   8B4030                 mov     eax, [eax+$30]
009FCB4A   BA02000000             mov     edx, $00000002

* Reference to: DB.Proc_0097CB48
|
009FCB4F   E8F4FFF7FF             call    0097CB48
009FCB54   8D55D0                 lea     edx, [ebp-$30]
009FCB57   8B08                   mov     ecx, [eax]
009FCB59   FF5160                 call    dword ptr [ecx+$60]
009FCB5C   8B55D0                 mov     edx, [ebp-$30]

* Reference to control TShowUsersForm.ConTMEdit : TLabeledEdit
|
009FCB5F   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to: Controls.Proc_0094B208
|
009FCB65   E89EE6F4FF             call    0094B208
009FCB6A   8B06                   mov     eax, [esi]
009FCB6C   8B4060                 mov     eax, [eax+$60]
009FCB6F   8B4030                 mov     eax, [eax+$30]
009FCB72   BA03000000             mov     edx, $00000003

* Reference to: DB.Proc_0097CB48
|
009FCB77   E8CCFFF7FF             call    0097CB48
009FCB7C   8D55CC                 lea     edx, [ebp-$34]
009FCB7F   8B08                   mov     ecx, [eax]
009FCB81   FF5160                 call    dword ptr [ecx+$60]
009FCB84   8B55CC                 mov     edx, [ebp-$34]

* Reference to control TShowUsersForm.DiscnTMEdit : TLabeledEdit
|
009FCB87   8B8300030000           mov     eax, [ebx+$0300]

* Reference to: Controls.Proc_0094B208
|
009FCB8D   E876E6F4FF             call    0094B208
009FCB92   8B06                   mov     eax, [esi]
009FCB94   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_00988BD0
|
009FCB97   E834C0F8FF             call    00988BD0
009FCB9C   4F                     dec     edi
009FCB9D   0F8552FFFFFF           jnz     009FCAF5
009FCBA3   8B06                   mov     eax, [esi]
009FCBA5   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FCBA8   E80F9AF8FF             call    009865BC
009FCBAD   8B06                   mov     eax, [esi]
009FCBAF   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FCBB2   E801D8F9FF             call    0099A3B8
009FCBB7   8B10                   mov     edx, [eax]
009FCBB9   FF5244                 call    dword ptr [edx+$44]
009FCBBC   33C0                   xor     eax, eax
009FCBBE   5A                     pop     edx
009FCBBF   59                     pop     ecx
009FCBC0   59                     pop     ecx
009FCBC1   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[‹å]Ã'
|
009FCBC4   68DECB9F00             push    $009FCBDE
009FCBC9   8D45CC                 lea     eax, [ebp-$34]
009FCBCC   BA0D000000             mov     edx, $0000000D

* Reference to: System.Proc_00904858
|
009FCBD1   E8827CF0FF             call    00904858
009FCBD6   C3                     ret

009FCBD7   E9A075F0FF             jmp     0090417C
009FCBDC   EBEB                   jmp     009FCBC9

****** END
|
009FCBDE   5F                     pop     edi
009FCBDF   5E                     pop     esi
009FCBE0   5B                     pop     ebx
009FCBE1   8BE5                   mov     esp, ebp
009FCBE3   5D                     pop     ebp
009FCBE4   C3                     ret

*)
end;

procedure TShowUsersForm.FormKeyPress(Sender : TObject);
begin
(*
009FCD54   80391B                 cmp     byte ptr [ecx], $1B
009FCD57   7505                   jnz     009FCD5E

* Reference to : TApplication._PROC_0096912C()
|
009FCD59   E8CEC3F6FF             call    0096912C
009FCD5E   C3                     ret

*)
end;

procedure TShowUsersForm.addToRememberedClick(Sender : TObject);
begin
(*
009FCD60   55                     push    ebp
009FCD61   8BEC                   mov     ebp, esp
009FCD63   6A00                   push    $00
009FCD65   53                     push    ebx
009FCD66   56                     push    esi
009FCD67   8BD8                   mov     ebx, eax
009FCD69   33C0                   xor     eax, eax
009FCD6B   55                     push    ebp

* Possible String Reference to: 'é»sðÿëð^[Y]ÃèË÷ÿÿÃ‹ÀSV‹Ø‹5Œû '
|
009FCD6C   68BCCD9F00             push    $009FCDBC
009FCD71   64FF30                 push    dword ptr fs:[eax]
009FCD74   648920                 mov     fs:[eax], esp

* Reference to control TShowUsersForm.CUListBox : TListBox
|
009FCD77   8BB3F4020000           mov     esi, [ebx+$02F4]
009FCD7D   8BC6                   mov     eax, esi
009FCD7F   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FCD81   FF92C8000000           call    dword ptr [edx+$00C8]
009FCD87   8BD0                   mov     edx, eax
009FCD89   8D4DFC                 lea     ecx, [ebp-$04]

* Reference to field TListBox.OFFS_0218
|
009FCD8C   8B8618020000           mov     eax, [esi+$0218]
009FCD92   8B18                   mov     ebx, [eax]
009FCD94   FF530C                 call    dword ptr [ebx+$0C]
009FCD97   8B55FC                 mov     edx, [ebp-$04]

* Reference to TCharacterMarkForm instance
|
009FCD9A   A138FEA000             mov     eax, dword ptr [$00A0FE38]
009FCD9F   8B00                   mov     eax, [eax]

* Reference to : TCharacterMarkForm._PROC_009FA7F4()
|
009FCDA1   E84EDAFFFF             call    009FA7F4
009FCDA6   33C0                   xor     eax, eax
009FCDA8   5A                     pop     edx
009FCDA9   59                     pop     ecx
009FCDAA   59                     pop     ecx
009FCDAB   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]ÃèË÷ÿÿÃ‹ÀSV‹Ø‹5Œû '
|
009FCDAE   68C3CD9F00             push    $009FCDC3
009FCDB3   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009FCDB6   E8797AF0FF             call    00904834
009FCDBB   C3                     ret

009FCDBC   E9BB73F0FF             jmp     0090417C
009FCDC1   EBF0                   jmp     009FCDB3

****** END
|
009FCDC3   5E                     pop     esi
009FCDC4   5B                     pop     ebx
009FCDC5   59                     pop     ecx
009FCDC6   5D                     pop     ebp
009FCDC7   C3                     ret

*)
end;

procedure TShowUsersForm.BitBtn1Click(Sender : TObject);
begin
(*

* Reference to: ShowUsersUnit.Proc_009FC598
|
009FCDC8   E8CBF7FFFF             call    009FC598
009FCDCD   C3                     ret

*)
end;

procedure TShowUsersForm.SpeedButton1Click(Sender : TObject);
begin
(*
009FCDD0   53                     push    ebx
009FCDD1   56                     push    esi
009FCDD2   8BD8                   mov     ebx, eax

* Reference to TDataModule_Main instance
|
009FCDD4   8B358CFBA000           mov     esi, [$00A0FB8C]
009FCDDA   8B06                   mov     eax, [esi]
009FCDDC   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FCDDF   E8D897F8FF             call    009865BC
009FCDE4   8B06                   mov     eax, [esi]
009FCDE6   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FCDE9   E8CAD5F9FF             call    0099A3B8
009FCDEE   8B10                   mov     edx, [eax]
009FCDF0   FF5244                 call    dword ptr [edx+$44]
009FCDF3   8B06                   mov     eax, [esi]
009FCDF5   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FCDF8   E8BBD5F9FF             call    0099A3B8

* Possible String Reference to: 'UPDATE memb_stat SET ConnectStat = 
|                                0 WHERE ConnectStat = 1'
|
009FCDFD   BA3CCE9F00             mov     edx, $009FCE3C
009FCE02   8B08                   mov     ecx, [eax]
009FCE04   FF5138                 call    dword ptr [ecx+$38]
009FCE07   8B06                   mov     eax, [esi]
009FCE09   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
009FCE0C   E89F97F8FF             call    009865B0
009FCE11   8B06                   mov     eax, [esi]
009FCE13   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FCE16   E8A197F8FF             call    009865BC
009FCE1B   8B06                   mov     eax, [esi]
009FCE1D   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FCE20   E893D5F9FF             call    0099A3B8
009FCE25   8B10                   mov     edx, [eax]
009FCE27   FF5244                 call    dword ptr [edx+$44]
009FCE2A   8BC3                   mov     eax, ebx

* Reference to: ShowUsersUnit.Proc_009FC598
|
009FCE2C   E867F7FFFF             call    009FC598
009FCE31   5E                     pop     esi
009FCE32   5B                     pop     ebx
009FCE33   C3                     ret

*)
end;

procedure TShowUsersForm.FormCreate(Sender : TObject);
begin
(*
009FCE78   53                     push    ebx
009FCE79   8BD8                   mov     ebx, eax

* Possible String Reference to: 'Set "ConnectStat = 0" to all'
|
009FCE7B   BAACCE9F00             mov     edx, $009FCEAC

* Reference to control TShowUsersForm.SpeedButton1 : TSpeedButton
|
009FCE80   8B8318030000           mov     eax, [ebx+$0318]

* Reference to: Controls.Proc_0094B208
|
009FCE86   E87DE3F4FF             call    0094B208

* Reference to control TShowUsersForm.SpeedButton1 : TSpeedButton
|
009FCE8B   8B8318030000           mov     eax, [ebx+$0318]
009FCE91   0580000000             add     eax, +$00000080

* Possible String Reference to: 'sometime after server shutdown peop
|                                les left online.press this button t
|                                o take offline all users.'
|
009FCE96   BAD4CE9F00             mov     edx, $009FCED4

* Reference to: System.Proc_00904888
|
009FCE9B   E8E879F0FF             call    00904888
009FCEA0   5B                     pop     ebx
009FCEA1   C3                     ret

*)
end;

procedure TShowUsersForm._PROC_009FCE3D(Sender : TObject);
begin
(*
009FCE3D   50                     push    eax
009FCE3E   44                     inc     esp
009FCE3F   41                     inc     ecx
009FCE40   54                     push    esp
009FCE41   45                     inc     ebp
009FCE42   206D65                 and     [ebp+$65], ch
009FCE45   6D                     insd
009FCE46   625F73                 bound   ebx, qword ptr [edi+$73]
009FCE49   7461                   jz      009FCEAC
009FCE4B   7420                   jz      009FCE6D
009FCE4D   53                     push    ebx
009FCE4E   45                     inc     ebp
009FCE4F   54                     push    esp
009FCE50   20436F                 and     [ebx+$6F], al
009FCE53   6E                     outsb
009FCE54   6E                     outsb
009FCE55   6563745374             arpl    gs:[ebx+edx*2+$74], si
009FCE5A   61                     popa
009FCE5B   7420                   jz      009FCE7D
009FCE5D   3D20302057             cmp     eax, $57203020
009FCE62   48                     dec     eax
009FCE63   45                     inc     ebp
009FCE64   52                     push    edx
009FCE65   45                     inc     ebp
009FCE66   20436F                 and     [ebx+$6F], al
009FCE69   6E                     outsb
009FCE6A   6E                     outsb
009FCE6B   6563745374             arpl    gs:[ebx+edx*2+$74], si
009FCE70   61                     popa
009FCE71   7420                   jz      009FCE93
009FCE73   3D20310000             cmp     eax, $00003120
009FCE78   53                     push    ebx
009FCE79   8BD8                   mov     ebx, eax

* Possible String Reference to: 'Set "ConnectStat = 0" to all'
|
009FCE7B   BAACCE9F00             mov     edx, $009FCEAC
009FCE80   8B8318030000           mov     eax, [ebx+$0318]

* Reference to: Controls.Proc_0094B208
|
009FCE86   E87DE3F4FF             call    0094B208
009FCE8B   8B8318030000           mov     eax, [ebx+$0318]
009FCE91   0580000000             add     eax, +$00000080

* Possible String Reference to: 'sometime after server shutdown peop
|                                les left online.press this button t
|                                o take offline all users.'
|
009FCE96   BAD4CE9F00             mov     edx, $009FCED4

* Reference to: System.Proc_00904888
|
009FCE9B   E8E879F0FF             call    00904888
009FCEA0   5B                     pop     ebx
009FCEA1   C3                     ret

009FCEA2   0000                   add     [eax], al

009FCEA4   FFFF                   DB  $FF, $FF  //      
009FCEA6   FFFF                   DB  $FF, $FF  //      
009FCEA8   1E                     push    ds
009FCEA9   0000                   add     [eax], al

009FCEAB   005365                 add     [ebx+$65], dl
009FCEAE   7420                   jz      009FCED0
009FCEB0   0D22436F6E             or      eax, $6E6F4322
009FCEB5   6E                     outsb
009FCEB6   6563745374             arpl    gs:[ebx+edx*2+$74], si
009FCEBB   61                     popa
009FCEBC   7420                   jz      009FCEDE
009FCEBE   3D2030220D             cmp     eax, $0D223020
009FCEC3   20746F20               and     [edi+ebp*2+$20], dh
009FCEC7   61                     popa
009FCEC8   6C                     insb
009FCEC9   6C                     insb
009FCECA   0000                   add     [eax], al

009FCECC   FFFF                   DB  $FF, $FF  //      
009FCECE   FFFF                   DB  $FF, $FF  //      
009FCED0   60                     pusha
009FCED1   0000                   add     [eax], al

009FCED3   00736F                 add     [ebx+$6F], dh
009FCED6   6D                     insd
009FCED7   657469                 jz      009FCF43
009FCEDA   6D                     insd
009FCEDB   65206166               and     gs:[ecx+$66], ah
009FCEDF   7465                   jz      009FCF46
009FCEE1   7220                   jb      009FCF03
009FCEE3   7365                   jnb     009FCF4A
009FCEE5   7276                   jb      009FCF5D
009FCEE7   657220                 jb      009FCF0A
009FCEEA   7368                   jnb     009FCF54
009FCEEC   7574                   jnz     009FCF62
009FCEEE   646F                   outsd
009FCEF0   776E                   jnbe    009FCF60
009FCEF2   207065                 and     [eax+$65], dh
009FCEF5   6F                     outsd
009FCEF6   706C                   jo      009FCF64
009FCEF8   657320                 jnb     009FCF1B
009FCEFB   6C                     insb
009FCEFC   65667420               jz      009FCF20
009FCF00   6F                     outsd
009FCF01   6E                     outsb
009FCF02   6C                     insb
009FCF03   696E652E0D7072         imul    ebp, [esi+$65], $72700D2E
009FCF0A   657373                 jnb     009FCF80
009FCF0D   20746869               and     [eax+ebp*2+$69], dh
009FCF11   7320                   jnb     009FCF33
009FCF13   627574                 bound   esi, qword ptr [ebp+$74]
009FCF16   746F                   jz      009FCF87
009FCF18   6E                     outsb
009FCF19   20746F20               and     [edi+ebp*2+$20], dh
009FCF1D   7461                   jz      009FCF80
009FCF1F   6B65206F               imul    esp, [ebp+$20], $6F
009FCF23   66666C                 insb
009FCF26   696E6520616C6C         imul    ebp, [esi+$65], $6C6C6120
009FCF2D   207573                 and     [ebp+$73], dh
009FCF30   657273                 jb      009FCFA6
009FCF33   2E0000                 add     cs:[eax], al
009FCF36   0000                   add     [eax], al

009FCF38   55                     push    ebp
009FCF39   8BEC                   mov     ebp, esp
009FCF3B   33C0                   xor     eax, eax
009FCF3D   55                     push    ebp
009FCF3E   685DCF9F00             push    $009FCF5D
009FCF43   64FF30                 push    dword ptr fs:[eax]
009FCF46   648920                 mov     fs:[eax], esp
009FCF49   FF05D820A100           inc     dword ptr [$00A120D8]
009FCF4F   33C0                   xor     eax, eax
009FCF51   5A                     pop     edx
009FCF52   59                     pop     ecx
009FCF53   59                     pop     ecx
009FCF54   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-Ø ¡'
|
009FCF57   6864CF9F00             push    $009FCF64
009FCF5C   C3                     ret

009FCF5D   E91A72F0FF             jmp     0090417C
009FCF62   EBF8                   jmp     009FCF5C

****** END
|
009FCF64   5D                     pop     ebp
009FCF65   C3                     ret

009FCF66   8BC0                   mov     eax, eax
009FCF68   832DD820A10001         sub     dword ptr [$00A120D8], +$01
009FCF6F   C3                     ret

009FCF70   BCCF9F0000             mov     esp, $00009FCF
009FCF75   0000                   add     [eax], al

009FCF77   0000                   add     [eax], al

009FCF79   0000                   add     [eax], al

009FCF7B   0000                   add     [eax], al

009FCF7D   0000                   add     [eax], al

009FCF7F   00E0                   add     al, ah
009FCF81   D19F00ACD09F           rcr     dword ptr [edi+$9FD0AC00], 1
009FCF87   005CD19F               add     [ecx+edx*8-$61], bl
009FCF8B   0000                   add     [eax], al

*)
end;

end.