unit ShowGuildsUnit;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TShowGuildsForm=class(TForm)
    GroupBox9: TGroupBox;
    Label40: TLabel;
    Label49: TLabel;
    Label50: TLabel;
    Label54: TLabel;
    guildbox: TListBox;
    guildmaster: TEdit;
    guildscore: TEdit;
    guildnotice: TRichEdit;
    PaintBox1: TPaintBox;
    BitBtn1: TBitBtn;
    procedure guildboxClick(Sender : TObject);
    procedure PaintBox1Paint(Sender : TObject);
    procedure FormKeyPress(Sender : TObject);
    procedure BitBtn1Click(Sender : TObject);
    procedure _PROC_009FD38D(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  ShowGuildsForm: TShowGuildsForm;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TShowGuildsForm.guildboxClick(Sender : TObject);
begin
(*
009FD630   55                     push    ebp
009FD631   8BEC                   mov     ebp, esp
009FD633   B904000000             mov     ecx, $00000004
009FD638   6A00                   push    $00
009FD63A   6A00                   push    $00
009FD63C   49                     dec     ecx
009FD63D   75F9                   jnz     009FD638
009FD63F   51                     push    ecx
009FD640   53                     push    ebx
009FD641   56                     push    esi
009FD642   8945FC                 mov     [ebp-$04], eax
009FD645   33C0                   xor     eax, eax
009FD647   55                     push    ebp

* Possible String Reference to: 'éøhðÿëÝ^[‹å]ÃÿÿÿÿA'
|
009FD648   687FD89F00             push    $009FD87F
009FD64D   64FF30                 push    dword ptr fs:[eax]
009FD650   648920                 mov     fs:[eax], esp

* Reference to TDataModule_Main instance
|
009FD653   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD658   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD65A   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FD65D   E85A8FF8FF             call    009865BC

* Reference to TDataModule_Main instance
|
009FD662   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD667   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD669   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FD66C   E847CDF9FF             call    0099A3B8
009FD671   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_44
|
009FD673   FF5244                 call    dword ptr [edx+$44]

* Possible String Reference to: 'select G_Score,G_Master,G_Notice,G_
|                                Mark from Guild where G_Name=''
|
009FD676   6894D89F00             push    $009FD894

* Reference to ShowGuildsForm
|
009FD67B   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TShowGuildsForm.guildbox : TListBox
|
009FD67E   8B9804030000           mov     ebx, [eax+$0304]
009FD684   8BC3                   mov     eax, ebx
009FD686   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FD688   FF92C8000000           call    dword ptr [edx+$00C8]
009FD68E   8BD0                   mov     edx, eax
009FD690   8D4DF0                 lea     ecx, [ebp-$10]

* Reference to field TListBox.OFFS_0218
|
009FD693   8B8318020000           mov     eax, [ebx+$0218]
009FD699   8B18                   mov     ebx, [eax]
009FD69B   FF530C                 call    dword ptr [ebx+$0C]
009FD69E   FF75F0                 push    dword ptr [ebp-$10]

* Possible String Reference to: '' '
|
009FD6A1   68E0D89F00             push    $009FD8E0
009FD6A6   8D45F4                 lea     eax, [ebp-$0C]
009FD6A9   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904BAC
|
009FD6AE   E8F974F0FF             call    00904BAC
009FD6B3   8B45F4                 mov     eax, [ebp-$0C]
009FD6B6   50                     push    eax

* Reference to TDataModule_Main instance
|
009FD6B7   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD6BC   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD6BE   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FD6C1   E8F2CCF9FF             call    0099A3B8
009FD6C6   5A                     pop     edx
009FD6C7   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_38
|
009FD6C9   FF5138                 call    dword ptr [ecx+$38]

* Reference to TDataModule_Main instance
|
009FD6CC   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD6D1   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD6D3   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
009FD6D6   E8D58EF8FF             call    009865B0

* Reference to TDataModule_Main instance
|
009FD6DB   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD6E0   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD6E2   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FD6E5   8B4030                 mov     eax, [eax+$30]
009FD6E8   BA01000000             mov     edx, $00000001

* Reference to: DB.Proc_0097CB48
|
009FD6ED   E856F4F7FF             call    0097CB48
009FD6F2   8D55EC                 lea     edx, [ebp-$14]
009FD6F5   8B08                   mov     ecx, [eax]
009FD6F7   FF5160                 call    dword ptr [ecx+$60]
009FD6FA   8B55EC                 mov     edx, [ebp-$14]

* Reference to ShowGuildsForm
|
009FD6FD   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TShowGuildsForm.guildmaster : TEdit
|
009FD700   8B8008030000           mov     eax, [eax+$0308]

* Reference to: Controls.Proc_0094B208
|
009FD706   E8FDDAF4FF             call    0094B208

* Reference to TDataModule_Main instance
|
009FD70B   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD710   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD712   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FD715   8B4030                 mov     eax, [eax+$30]
009FD718   33D2                   xor     edx, edx

* Reference to: DB.Proc_0097CB48
|
009FD71A   E829F4F7FF             call    0097CB48
009FD71F   8D55E8                 lea     edx, [ebp-$18]
009FD722   8B08                   mov     ecx, [eax]
009FD724   FF5160                 call    dword ptr [ecx+$60]
009FD727   8B55E8                 mov     edx, [ebp-$18]

* Reference to ShowGuildsForm
|
009FD72A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TShowGuildsForm.guildscore : TEdit
|
009FD72D   8B800C030000           mov     eax, [eax+$030C]

* Reference to: Controls.Proc_0094B208
|
009FD733   E8D0DAF4FF             call    0094B208

* Reference to TDataModule_Main instance
|
009FD738   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD73D   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD73F   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FD742   8B4030                 mov     eax, [eax+$30]
009FD745   BA02000000             mov     edx, $00000002

* Reference to: DB.Proc_0097CB48
|
009FD74A   E8F9F3F7FF             call    0097CB48
009FD74F   8D55E4                 lea     edx, [ebp-$1C]
009FD752   8B08                   mov     ecx, [eax]
009FD754   FF5160                 call    dword ptr [ecx+$60]
009FD757   8B55E4                 mov     edx, [ebp-$1C]

* Reference to ShowGuildsForm
|
009FD75A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TShowGuildsForm.guildnotice : TRichEdit
|
009FD75D   8B8010030000           mov     eax, [eax+$0310]

* Reference to: Controls.Proc_0094B208
|
009FD763   E8A0DAF4FF             call    0094B208

* Reference to TDataModule_Main instance
|
009FD768   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD76D   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD76F   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FD772   8B4030                 mov     eax, [eax+$30]
009FD775   BA03000000             mov     edx, $00000003

* Reference to: DB.Proc_0097CB48
|
009FD77A   E8C9F3F7FF             call    0097CB48
009FD77F   8B10                   mov     edx, [eax]
009FD781   FF5270                 call    dword ptr [edx+$70]
009FD784   50                     push    eax
009FD785   8D45F8                 lea     eax, [ebp-$08]
009FD788   B901000000             mov     ecx, $00000001

* Reference to object .3
|
009FD78D   8B1508D69F00           mov     edx, [$009FD608]

* Reference to: System.Proc_00906134
|
009FD793   E89C89F0FF             call    00906134
009FD798   83C404                 add     esp, +$04

* Reference to TDataModule_Main instance
|
009FD79B   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD7A0   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD7A2   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FD7A5   8B4030                 mov     eax, [eax+$30]
009FD7A8   BA03000000             mov     edx, $00000003

* Reference to: DB.Proc_0097CB48
|
009FD7AD   E896F3F7FF             call    0097CB48
009FD7B2   B101                   mov     cl, $01
009FD7B4   8B55F8                 mov     edx, [ebp-$08]

* Reference to: DB.Proc_0097D6B0
|
009FD7B7   E8F4FEF7FF             call    0097D6B0
009FD7BC   B8E020A100             mov     eax, $00A120E0

* Reference to: System.Proc_00904834
|
009FD7C1   E86E70F0FF             call    00904834
009FD7C6   8B45F8                 mov     eax, [ebp-$08]

* Reference to: System.Proc_00905F80
|
009FD7C9   E8B287F0FF             call    00905F80
009FD7CE   8BD8                   mov     ebx, eax
009FD7D0   83EB02                 sub     ebx, +$02
009FD7D3   7C3E                   jl      009FD813
009FD7D5   43                     inc     ebx
009FD7D6   BE02000000             mov     esi, $00000002
009FD7DB   8B45F8                 mov     eax, [ebp-$08]
009FD7DE   85C0                   test    eax, eax
009FD7E0   7405                   jz      009FD7E7
009FD7E2   3B70FC                 cmp     esi, [eax-$04]
009FD7E5   7205                   jb      009FD7EC

* Reference to: System.Proc_00903920
|
009FD7E7   E83461F0FF             call    00903920
009FD7EC   8A0430                 mov     al, byte ptr [eax+esi]
009FD7EF   8D55DC                 lea     edx, [ebp-$24]

* Reference to: Unit_00A096BC.Proc_00A0B9D8
|
009FD7F2   E8E1E10000             call    00A0B9D8
009FD7F7   8B45DC                 mov     eax, [ebp-$24]
009FD7FA   8D55E0                 lea     edx, [ebp-$20]

* Reference to: Unit_009082C0.Proc_00908F9C
|
009FD7FD   E89AB7F0FF             call    00908F9C
009FD802   8B55E0                 mov     edx, [ebp-$20]
009FD805   B8E020A100             mov     eax, $00A120E0

* Reference to: System.Proc_00904AF4
|
009FD80A   E8E572F0FF             call    00904AF4
009FD80F   46                     inc     esi
009FD810   4B                     dec     ebx
009FD811   75C8                   jnz     009FD7DB

* Reference to TDataModule_Main instance
|
009FD813   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD818   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD81A   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_00988BD0
|
009FD81D   E8AEB3F8FF             call    00988BD0

* Reference to ShowGuildsForm
|
009FD822   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TShowGuildsForm.PaintBox1 : TPaintBox
|
009FD825   8B8014030000           mov     eax, [eax+$0314]
009FD82B   8B10                   mov     edx, [eax]

* Possible reference to virtual method TPaintBox.OFFS_0080
|
009FD82D   FF9280000000           call    dword ptr [edx+$0080]

* Reference to TDataModule_Main instance
|
009FD833   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD838   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD83A   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FD83D   E87A8DF8FF             call    009865BC

* Reference to TDataModule_Main instance
|
009FD842   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FD847   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FD849   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FD84C   E867CBF9FF             call    0099A3B8
009FD851   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_44
|
009FD853   FF5244                 call    dword ptr [edx+$44]
009FD856   33C0                   xor     eax, eax
009FD858   5A                     pop     edx
009FD859   59                     pop     ecx
009FD85A   59                     pop     ecx
009FD85B   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]ÃÿÿÿÿA'
|
009FD85E   6886D89F00             push    $009FD886
009FD863   8D45DC                 lea     eax, [ebp-$24]
009FD866   BA07000000             mov     edx, $00000007

* Reference to: System.Proc_00904858
|
009FD86B   E8E86FF0FF             call    00904858
009FD870   8D45F8                 lea     eax, [ebp-$08]

* Reference to object .3
|
009FD873   8B1508D69F00           mov     edx, [$009FD608]

* Reference to: System.Proc_00906254
|
009FD879   E8D689F0FF             call    00906254
009FD87E   C3                     ret

009FD87F   E9F868F0FF             jmp     0090417C
009FD884   EBDD                   jmp     009FD863

****** END
|
009FD886   5E                     pop     esi
009FD887   5B                     pop     ebx
009FD888   8BE5                   mov     esp, ebp
009FD88A   5D                     pop     ebp
009FD88B   C3                     ret

*)
end;

procedure TShowGuildsForm.PaintBox1Paint(Sender : TObject);
begin
(*
009FD8E4   55                     push    ebp
009FD8E5   8BEC                   mov     ebp, esp
009FD8E7   6A00                   push    $00
009FD8E9   53                     push    ebx
009FD8EA   56                     push    esi
009FD8EB   57                     push    edi
009FD8EC   8BF8                   mov     edi, eax
009FD8EE   33C0                   xor     eax, eax
009FD8F0   55                     push    ebp
009FD8F1   68DBD99F00             push    $009FD9DB
009FD8F6   64FF30                 push    dword ptr fs:[eax]
009FD8F9   648920                 mov     fs:[eax], esp
009FD8FC   A1E020A100             mov     eax, dword ptr [$00A120E0]

* Reference to: System.Proc_00904AEC
|
009FD901   E8E671F0FF             call    00904AEC
009FD906   85C0                   test    eax, eax
009FD908   0F8EB7000000           jle     009FD9C5
009FD90E   33F6                   xor     esi, esi
009FD910   33DB                   xor     ebx, ebx
009FD912   8D45FC                 lea     eax, [ebp-$04]
009FD915   6BD308                 imul    edx, ebx, $08
009FD918   7105                   jno     009FD91F

* Reference to: System.Proc_00903928
|
009FD91A   E80960F0FF             call    00903928
009FD91F   03D6                   add     edx, esi
009FD921   7105                   jno     009FD928

* Reference to: System.Proc_00903928
|
009FD923   E80060F0FF             call    00903928
009FD928   83C201                 add     edx, +$01
009FD92B   7105                   jno     009FD932

* Reference to: System.Proc_00903928
|
009FD92D   E8F65FF0FF             call    00903928
009FD932   8B0DE020A100           mov     ecx, [$00A120E0]
009FD938   4A                     dec     edx
009FD939   85C9                   test    ecx, ecx
009FD93B   7405                   jz      009FD942
009FD93D   3B51FC                 cmp     edx, [ecx-$04]
009FD940   7205                   jb      009FD947

* Reference to: System.Proc_00903920
|
009FD942   E8D95FF0FF             call    00903920
009FD947   42                     inc     edx
009FD948   8A5411FF               mov     dl, byte ptr [ecx+edx-$01]

* Reference to: System.Proc_00904A14
|
009FD94C   E8C370F0FF             call    00904A14
009FD951   8B45FC                 mov     eax, [ebp-$04]

* Reference to: ShowGuildsUnit.Proc_009FD38C
|
009FD954   E833FAFFFF             call    009FD38C
009FD959   8BD0                   mov     edx, eax
009FD95B   8B8714030000           mov     eax, [edi+$0314]
009FD961   8B8060010000           mov     eax, [eax+$0160]
009FD967   8B4014                 mov     eax, [eax+$14]

* Reference to : TIcon._PROC_00925360()
|
009FD96A   E8F179F2FF             call    00925360
009FD96F   6BC60A                 imul    eax, esi, $0A
009FD972   7105                   jno     009FD979

* Reference to: System.Proc_00903928
|
009FD974   E8AF5FF0FF             call    00903928
009FD979   8BC8                   mov     ecx, eax
009FD97B   83C10A                 add     ecx, +$0A
009FD97E   7105                   jno     009FD985

* Reference to: System.Proc_00903928
|
009FD980   E8A35FF0FF             call    00903928
009FD985   51                     push    ecx
009FD986   6BD30A                 imul    edx, ebx, $0A
009FD989   7105                   jno     009FD990

* Reference to: System.Proc_00903928
|
009FD98B   E8985FF0FF             call    00903928
009FD990   8BCA                   mov     ecx, edx
009FD992   83C10A                 add     ecx, +$0A
009FD995   7105                   jno     009FD99C

* Reference to: System.Proc_00903928
|
009FD997   E88C5FF0FF             call    00903928
009FD99C   51                     push    ecx
009FD99D   52                     push    edx
009FD99E   8B9714030000           mov     edx, [edi+$0314]
009FD9A4   8B9260010000           mov     edx, [edx+$0160]
009FD9AA   92                     xchg    eax, edx
009FD9AB   59                     pop     ecx

* Reference to: Graphics.Proc_00925934
|
009FD9AC   E8837FF2FF             call    00925934
009FD9B1   43                     inc     ebx
009FD9B2   83FB08                 cmp     ebx, +$08
009FD9B5   0F8557FFFFFF           jnz     009FD912
009FD9BB   46                     inc     esi
009FD9BC   83FE08                 cmp     esi, +$08
009FD9BF   0F854BFFFFFF           jnz     009FD910
009FD9C5   33C0                   xor     eax, eax
009FD9C7   5A                     pop     edx
009FD9C8   59                     pop     ecx
009FD9C9   59                     pop     ecx
009FD9CA   648910                 mov     fs:[eax], edx

****** FINALLY
|
009FD9CD   68E2D99F00             push    $009FD9E2
009FD9D2   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009FD9D5   E85A6EF0FF             call    00904834
009FD9DA   C3                     ret

009FD9DB   E99C67F0FF             jmp     0090417C
009FD9E0   EBF0                   jmp     009FD9D2

****** END
|
009FD9E2   5F                     pop     edi
009FD9E3   5E                     pop     esi
009FD9E4   5B                     pop     ebx
009FD9E5   59                     pop     ecx
009FD9E6   5D                     pop     ebp
009FD9E7   C3                     ret

*)
end;

procedure TShowGuildsForm.FormKeyPress(Sender : TObject);
begin
(*
009FD9E8   80391B                 cmp     byte ptr [ecx], $1B
009FD9EB   7505                   jnz     009FD9F2

* Reference to : TApplication._PROC_0096912C()
|
009FD9ED   E83AB7F6FF             call    0096912C
009FD9F2   C3                     ret

*)
end;

procedure TShowGuildsForm.BitBtn1Click(Sender : TObject);
begin
(*

* Reference to: ShowGuildsUnit.Proc_009FD20C
|
009FD9F4   E813F8FFFF             call    009FD20C
009FD9F9   C3                     ret

*)
end;

procedure TShowGuildsForm._PROC_009FD38D(Sender : TObject);
begin
(*
009FD38D   8BEC                   mov     ebp, esp
009FD38F   51                     push    ecx
009FD390   53                     push    ebx
009FD391   8945FC                 mov     [ebp-$04], eax

* Reference to ShowGuildsForm
|
009FD394   8B45FC                 mov     eax, [ebp-$04]

* Reference to: System.Proc_00904CD4
|
009FD397   E83879F0FF             call    00904CD4
009FD39C   33C0                   xor     eax, eax
009FD39E   55                     push    ebp

* Possible String Reference to: 'é?lðÿëð‹Ã[Y]Ã'
|
009FD39F   6838D59F00             push    $009FD538
009FD3A4   64FF30                 push    dword ptr fs:[eax]
009FD3A7   648920                 mov     fs:[eax], esp
009FD3AA   33DB                   xor     ebx, ebx

* Reference to ShowGuildsForm
|
009FD3AC   8B45FC                 mov     eax, [ebp-$04]
009FD3AF   BA50D59F00             mov     edx, $009FD550

* Reference to: System.Proc_00904C30
|
009FD3B4   E87778F0FF             call    00904C30
009FD3B9   7507                   jnz     009FD3C2
009FD3BB   33DB                   xor     ebx, ebx
009FD3BD   E960010000             jmp     009FD522

* Reference to ShowGuildsForm
|
009FD3C2   8B45FC                 mov     eax, [ebp-$04]
009FD3C5   BA5CD59F00             mov     edx, $009FD55C

* Reference to: System.Proc_00904C30
|
009FD3CA   E86178F0FF             call    00904C30
009FD3CF   7507                   jnz     009FD3D8
009FD3D1   33DB                   xor     ebx, ebx
009FD3D3   E94A010000             jmp     009FD522

* Reference to ShowGuildsForm
|
009FD3D8   8B45FC                 mov     eax, [ebp-$04]
009FD3DB   BA68D59F00             mov     edx, $009FD568

* Reference to: System.Proc_00904C30
|
009FD3E0   E84B78F0FF             call    00904C30
009FD3E5   750A                   jnz     009FD3F1
009FD3E7   BB8A8A8A00             mov     ebx, $008A8A8A
009FD3EC   E931010000             jmp     009FD522

* Reference to ShowGuildsForm
|
009FD3F1   8B45FC                 mov     eax, [ebp-$04]
009FD3F4   BA74D59F00             mov     edx, $009FD574

* Reference to: System.Proc_00904C30
|
009FD3F9   E83278F0FF             call    00904C30
009FD3FE   750A                   jnz     009FD40A
009FD400   BBFFFFFF00             mov     ebx, $00FFFFFF
009FD405   E918010000             jmp     009FD522

* Reference to ShowGuildsForm
|
009FD40A   8B45FC                 mov     eax, [ebp-$04]
009FD40D   BA80D59F00             mov     edx, $009FD580

* Reference to: System.Proc_00904C30
|
009FD412   E81978F0FF             call    00904C30
009FD417   750A                   jnz     009FD423
009FD419   BB0000FF00             mov     ebx, $00FF0000
009FD41E   E9FF000000             jmp     009FD522

* Reference to ShowGuildsForm
|
009FD423   8B45FC                 mov     eax, [ebp-$04]
009FD426   BA8CD59F00             mov     edx, $009FD58C

* Reference to: System.Proc_00904C30
|
009FD42B   E80078F0FF             call    00904C30
009FD430   750A                   jnz     009FD43C
009FD432   BB0487FF00             mov     ebx, $00FF8704
009FD437   E9E6000000             jmp     009FD522

* Reference to ShowGuildsForm
|
009FD43C   8B45FC                 mov     eax, [ebp-$04]
009FD43F   BA98D59F00             mov     edx, $009FD598

* Reference to: System.Proc_00904C30
|
009FD444   E8E777F0FF             call    00904C30
009FD449   750A                   jnz     009FD455
009FD44B   BB00FEFF00             mov     ebx, $00FFFE00
009FD450   E9CD000000             jmp     009FD522

* Reference to ShowGuildsForm
|
009FD455   8B45FC                 mov     eax, [ebp-$04]
009FD458   BAA4D59F00             mov     edx, $009FD5A4

* Reference to: System.Proc_00904C30
|
009FD45D   E8CE77F0FF             call    00904C30
009FD462   750A                   jnz     009FD46E
009FD464   BB00FF8600             mov     ebx, $0086FF00
009FD469   E9B4000000             jmp     009FD522

* Reference to ShowGuildsForm
|
009FD46E   8B45FC                 mov     eax, [ebp-$04]
009FD471   BAB0D59F00             mov     edx, $009FD5B0

* Reference to: System.Proc_00904C30
|
009FD476   E8B577F0FF             call    00904C30
009FD47B   750A                   jnz     009FD487
009FD47D   BB00FF0000             mov     ebx, $0000FF00
009FD482   E99B000000             jmp     009FD522

* Reference to ShowGuildsForm
|
009FD487   8B45FC                 mov     eax, [ebp-$04]
009FD48A   BABCD59F00             mov     edx, $009FD5BC

* Reference to: System.Proc_00904C30
|
009FD48F   E89C77F0FF             call    00904C30
009FD494   750A                   jnz     009FD4A0
009FD496   BB8BFF0000             mov     ebx, $0000FF8B
009FD49B   E982000000             jmp     009FD522

* Reference to ShowGuildsForm
|
009FD4A0   8B45FC                 mov     eax, [ebp-$04]
009FD4A3   BAC8D59F00             mov     edx, $009FD5C8

* Reference to: System.Proc_00904C30
|
009FD4A8   E88377F0FF             call    00904C30
009FD4AD   7507                   jnz     009FD4B6
009FD4AF   BBFFFF0000             mov     ebx, $0000FFFF
009FD4B4   EB6C                   jmp     009FD522

* Reference to ShowGuildsForm
|
009FD4B6   8B45FC                 mov     eax, [ebp-$04]
009FD4B9   BAD4D59F00             mov     edx, $009FD5D4

* Reference to: System.Proc_00904C30
|
009FD4BE   E86D77F0FF             call    00904C30
009FD4C3   7507                   jnz     009FD4CC
009FD4C5   BBFF860000             mov     ebx, $000086FF
009FD4CA   EB56                   jmp     009FD522

* Reference to ShowGuildsForm
|
009FD4CC   8B45FC                 mov     eax, [ebp-$04]
009FD4CF   BAE0D59F00             mov     edx, $009FD5E0

* Reference to: System.Proc_00904C30
|
009FD4D4   E85777F0FF             call    00904C30
009FD4D9   7507                   jnz     009FD4E2
009FD4DB   BBFF000000             mov     ebx, $000000FF
009FD4E0   EB40                   jmp     009FD522

* Reference to ShowGuildsForm
|
009FD4E2   8B45FC                 mov     eax, [ebp-$04]
009FD4E5   BAECD59F00             mov     edx, $009FD5EC

* Reference to: System.Proc_00904C30
|
009FD4EA   E84177F0FF             call    00904C30
009FD4EF   7507                   jnz     009FD4F8
009FD4F1   BBFF008800             mov     ebx, $008800FF
009FD4F6   EB2A                   jmp     009FD522

* Reference to ShowGuildsForm
|
009FD4F8   8B45FC                 mov     eax, [ebp-$04]
009FD4FB   BAF8D59F00             mov     edx, $009FD5F8

* Reference to: System.Proc_00904C30
|
009FD500   E82B77F0FF             call    00904C30
009FD505   7507                   jnz     009FD50E
009FD507   BBFF00FF00             mov     ebx, $00FF00FF
009FD50C   EB14                   jmp     009FD522

* Reference to ShowGuildsForm
|
009FD50E   8B45FC                 mov     eax, [ebp-$04]
009FD511   BA04D69F00             mov     edx, $009FD604

* Reference to: System.Proc_00904C30
|
009FD516   E81577F0FF             call    00904C30
009FD51B   7505                   jnz     009FD522
009FD51D   BB8700FF00             mov     ebx, $00FF0087
009FD522   33C0                   xor     eax, eax
009FD524   5A                     pop     edx
009FD525   59                     pop     ecx
009FD526   59                     pop     ecx
009FD527   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '‹Ã[Y]Ã'
|
009FD52A   683FD59F00             push    $009FD53F
009FD52F   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009FD532   E8FD72F0FF             call    00904834
009FD537   C3                     ret

009FD538   E93F6CF0FF             jmp     0090417C
009FD53D   EBF0                   jmp     009FD52F

****** END
|
009FD53F   8BC3                   mov     eax, ebx
009FD541   5B                     pop     ebx
009FD542   59                     pop     ecx
009FD543   5D                     pop     ebp
009FD544   C3                     ret

*)
end;

end.