unit SkinSelectUnit;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TSkinSelectForm=class(TForm)
    Label1: TLabel;
    Label2: TLabel;
    CheckBox1: TCheckBox;
    Button1: TSpeedButton;
    Label3: TLabel;
    SpeedButton1: TSpeedButton;
    OpenSkin: TOpenDialog;
    procedure SpeedButton1Click(Sender : TObject);
    procedure Button1Click(Sender : TObject);
    procedure FormCreate(Sender : TObject);
    procedure FormClose(Sender : TObject);
    procedure _PROC_00A025B8(Sender : TObject);
    procedure _PROC_00A025E8(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  SkinSelectForm: TSkinSelectForm;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TSkinSelectForm.SpeedButton1Click(Sender : TObject);
begin
(*
00A024E0   55                     push    ebp
00A024E1   8BEC                   mov     ebp, esp
00A024E3   6A00                   push    $00
00A024E5   6A00                   push    $00
00A024E7   53                     push    ebx
00A024E8   8BD8                   mov     ebx, eax
00A024EA   33C0                   xor     eax, eax
00A024EC   55                     push    ebp
00A024ED   686125A000             push    $00A02561
00A024F2   64FF30                 push    dword ptr fs:[eax]
00A024F5   648920                 mov     fs:[eax], esp

* Reference to control TSkinSelectForm.OpenSkin : TOpenDialog
|
00A024F8   8B8308030000           mov     eax, [ebx+$0308]
00A024FE   8B10                   mov     edx, [eax]

* Possible reference to virtual method TOpenDialog.OFFS_3C
|
00A02500   FF523C                 call    dword ptr [edx+$3C]
00A02503   84C0                   test    al, al
00A02505   743F                   jz      00A02546
00A02507   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TSkinSelectForm.OpenSkin : TOpenDialog
|
00A0250A   8B8308030000           mov     eax, [ebx+$0308]

* Reference to : TSaveDialog._PROC_00943540()
|
00A02510   E82B10F4FF             call    00943540
00A02515   8B55FC                 mov     edx, [ebp-$04]

* Reference to TMainForm instance
|
00A02518   A134FCA000             mov     eax, dword ptr [$00A0FC34]
00A0251D   8B00                   mov     eax, [eax]

* Reference to control TMainForm.SkinData1 : TSkinData
|
00A0251F   8B8018030000           mov     eax, [eax+$0318]

* Reference to: WinSkinData.Proc_009EE3DC
|
00A02525   E8B2BEFEFF             call    009EE3DC
00A0252A   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TSkinSelectForm.OpenSkin : TOpenDialog
|
00A0252D   8B8308030000           mov     eax, [ebx+$0308]

* Reference to : TSaveDialog._PROC_00943540()
|
00A02533   E80810F4FF             call    00943540
00A02538   8B55F8                 mov     edx, [ebp-$08]

* Reference to field TSkinSelectForm.OFFS_0310
|
00A0253B   8D8310030000           lea     eax, [ebx+$0310]

* Reference to: System.Proc_00904888
|
00A02541   E84223F0FF             call    00904888
00A02546   33C0                   xor     eax, eax
00A02548   5A                     pop     edx
00A02549   59                     pop     ecx
00A0254A   59                     pop     ecx
00A0254B   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[YY]√ç@'
|
00A0254E   686825A000             push    $00A02568
00A02553   8D45F8                 lea     eax, [ebp-$08]
00A02556   BA02000000             mov     edx, $00000002

* Reference to: System.Proc_00904858
|
00A0255B   E8F822F0FF             call    00904858
00A02560   C3                     ret

00A02561   E9161CF0FF             jmp     0090417C
00A02566   EBEB                   jmp     00A02553

****** END
|
00A02568   5B                     pop     ebx
00A02569   59                     pop     ecx
00A0256A   59                     pop     ecx
00A0256B   5D                     pop     ebp
00A0256C   C3                     ret

*)
end;

procedure TSkinSelectForm.Button1Click(Sender : TObject);
begin
(*
00A02570   53                     push    ebx
00A02571   8BD8                   mov     ebx, eax

* Reference to control TSkinSelectForm.CheckBox1 : TCheckBox
|
00A02573   8B83F8020000           mov     eax, [ebx+$02F8]
00A02579   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00C4
|
00A0257B   FF92C4000000           call    dword ptr [edx+$00C4]

* Reference to field TSkinSelectForm.OFFS_030C
|
00A02581   88830C030000           mov     [ebx+$030C], al
00A02587   5B                     pop     ebx
00A02588   C3                     ret

*)
end;

procedure TSkinSelectForm.FormCreate(Sender : TObject);
begin
(*
00A0258C   53                     push    ebx
00A0258D   8BD8                   mov     ebx, eax

* Reference to field TSkinSelectForm.OFFS_0310
|
00A0258F   8D8310030000           lea     eax, [ebx+$0310]

* Reference to: System.Proc_00904834
|
00A02595   E89A22F0FF             call    00904834
00A0259A   5B                     pop     ebx
00A0259B   C3                     ret

*)
end;

procedure TSkinSelectForm.FormClose(Sender : TObject);
begin
(*
00A0259C   53                     push    ebx
00A0259D   8BD8                   mov     ebx, eax

* Reference to control TSkinSelectForm.CheckBox1 : TCheckBox
|
00A0259F   8B83F8020000           mov     eax, [ebx+$02F8]
00A025A5   8B10                   mov     edx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00C4
|
00A025A7   FF92C4000000           call    dword ptr [edx+$00C4]

* Reference to field TSkinSelectForm.OFFS_030C
|
00A025AD   88830C030000           mov     [ebx+$030C], al
00A025B3   5B                     pop     ebx
00A025B4   C3                     ret

*)
end;

procedure TSkinSelectForm._PROC_00A025B8(Sender : TObject);
begin
(*
00A025B8   55                     push    ebp
00A025B9   8BEC                   mov     ebp, esp
00A025BB   33C0                   xor     eax, eax
00A025BD   55                     push    ebp
00A025BE   68DD25A000             push    $00A025DD
00A025C3   64FF30                 push    dword ptr fs:[eax]
00A025C6   648920                 mov     fs:[eax], esp
00A025C9   FF052821A100           inc     dword ptr [$00A12128]
00A025CF   33C0                   xor     eax, eax
00A025D1   5A                     pop     edx
00A025D2   59                     pop     ecx
00A025D3   59                     pop     ecx
00A025D4   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']√ã¿É-(!°'
|
00A025D7   68E425A000             push    $00A025E4
00A025DC   C3                     ret

00A025DD   E99A1BF0FF             jmp     0090417C
00A025E2   EBF8                   jmp     00A025DC

****** END
|
00A025E4   5D                     pop     ebp
00A025E5   C3                     ret

*)
end;

procedure TSkinSelectForm._PROC_00A025E8(Sender : TObject);
begin
(*
00A025E8   832D2821A10001         sub     dword ptr [$00A12128], +$01
00A025EF   C3                     ret

*)
end;

end.