unit SmartSearch;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TSmartSearchForm=class(TForm)
    SearchString: TEdit;
    SearchButton: TSpeedButton;
    SearchResult: TListBox;
    SearchWith: TRadioGroup;
    OkButton: TBitBtn;
    CancelButton: TBitBtn;
    procedure SearchStringKeyPress(Sender : TObject);
    procedure SearchButtonClick(Sender : TObject);
    procedure OkButtonClick(Sender : TObject);
    procedure SearchResultKeyPress(Sender : TObject);
    procedure SearchStringKeyDown(Sender : TObject);
    procedure SearchResultDblClick(Sender : TObject);
    procedure _PROC_00A013A0(Sender : TObject);
    procedure _PROC_00A01428(Sender : TObject);
    procedure _PROC_00A01458(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  SmartSearchForm: TSmartSearchForm;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TSmartSearchForm.SearchStringKeyPress(Sender : TObject);
begin
(*
00A00E10   53                     push    ebx
00A00E11   56                     push    esi
00A00E12   57                     push    edi
00A00E13   8BF9                   mov     edi, ecx
00A00E15   8BD8                   mov     ebx, eax
00A00E17   803F0D                 cmp     byte ptr [edi], $0D
00A00E1A   750F                   jnz     00A00E2B

* Reference to control TSmartSearchForm.SearchButton : TSpeedButton
|
00A00E1C   8B83F4020000           mov     eax, [ebx+$02F4]
00A00E22   66BEEBFF               mov     si, $FFEB

* Reference to: System.Proc_00903BE4
|
00A00E26   E8B92DF0FF             call    00903BE4
00A00E2B   803F1B                 cmp     byte ptr [edi], $1B
00A00E2E   750F                   jnz     00A00E3F

* Reference to control TSmartSearchForm.CancelButton : TBitBtn
|
00A00E30   8B8304030000           mov     eax, [ebx+$0304]
00A00E36   66BEEBFF               mov     si, $FFEB

* Reference to: System.Proc_00903BE4
|
00A00E3A   E8A52DF0FF             call    00903BE4
00A00E3F   5F                     pop     edi
00A00E40   5E                     pop     esi
00A00E41   5B                     pop     ebx
00A00E42   C3                     ret

*)
end;

procedure TSmartSearchForm.SearchButtonClick(Sender : TObject);
begin
(*
00A00E44   55                     push    ebp
00A00E45   8BEC                   mov     ebp, esp
00A00E47   33C9                   xor     ecx, ecx
00A00E49   51                     push    ecx
00A00E4A   51                     push    ecx
00A00E4B   51                     push    ecx
00A00E4C   51                     push    ecx
00A00E4D   51                     push    ecx
00A00E4E   51                     push    ecx
00A00E4F   53                     push    ebx
00A00E50   56                     push    esi
00A00E51   57                     push    edi
00A00E52   8945FC                 mov     [ebp-$04], eax

* Reference to TDataModule_Main instance
|
00A00E55   8B358CFBA000           mov     esi, [$00A0FB8C]
00A00E5B   33C0                   xor     eax, eax
00A00E5D   55                     push    ebp

* Possible String Reference to: 'éí0ðÿëÓ_^[‹å]Ãÿÿÿÿ-'
|
00A00E5E   688A10A000             push    $00A0108A
00A00E63   64FF30                 push    dword ptr fs:[eax]
00A00E66   648920                 mov     fs:[eax], esp
00A00E69   33D2                   xor     edx, edx
00A00E6B   55                     push    ebp
00A00E6C   684510A000             push    $00A01045
00A00E71   64FF32                 push    dword ptr fs:[edx]
00A00E74   648922                 mov     fs:[edx], esp

* Reference to SmartSearchForm
|
00A00E77   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A00E7A   8B80F8020000           mov     eax, [eax+$02F8]
00A00E80   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00D4
|
00A00E82   FF92D4000000           call    dword ptr [edx+$00D4]

* Reference to SmartSearchForm
|
00A00E88   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSmartSearchForm.OkButton : TBitBtn
|
00A00E8B   8B8000030000           mov     eax, [eax+$0300]
00A00E91   33D2                   xor     edx, edx
00A00E93   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TBitBtn.OFFS_64
|
00A00E95   FF5164                 call    dword ptr [ecx+$64]

* Reference to SmartSearchForm
|
00A00E98   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSmartSearchForm.SearchWith : TRadioGroup
|
00A00E9B   8B80FC020000           mov     eax, [eax+$02FC]

* Reference to field TRadioGroup.OFFS_0218
|
00A00EA1   8B8018020000           mov     eax, [eax+$0218]

* Reference to SmartSearchForm
|
00A00EA7   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A00EAA   8B92F8020000           mov     edx, [edx+$02F8]

* Reference to field TListBox.OFFS_000C
|
00A00EB0   89420C                 mov     [edx+$0C], eax
00A00EB3   8D45F4                 lea     eax, [ebp-$0C]

* Reference to pointer to GlobalVar_00A12174
|
00A00EB6   8B1578FCA000           mov     edx, [$00A0FC78]
00A00EBC   8B12                   mov     edx, [edx]

* Reference to: System.Proc_009050F4
|
00A00EBE   E83142F0FF             call    009050F4
00A00EC3   8B55F4                 mov     edx, [ebp-$0C]
00A00EC6   8B06                   mov     eax, [esi]
00A00EC8   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009927E8
|
00A00ECB   E81819F9FF             call    009927E8
00A00ED0   8B06                   mov     eax, [esi]
00A00ED2   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
00A00ED5   E8E256F8FF             call    009865BC
00A00EDA   8B06                   mov     eax, [esi]
00A00EDC   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
00A00EDF   E8D494F9FF             call    0099A3B8
00A00EE4   8B10                   mov     edx, [eax]
00A00EE6   FF5244                 call    dword ptr [edx+$44]

* Reference to SmartSearchForm
|
00A00EE9   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A00EEC   8B80F8020000           mov     eax, [eax+$02F8]

* Reference to field TListBox.OFFS_000C
|
00A00EF2   83780C00               cmp     dword ptr [eax+$0C], +$00
00A00EF6   752D                   jnz     00A00F25

* Possible String Reference to: 'select name from character where na
|                                me like('%'
|
00A00EF8   68A010A000             push    $00A010A0
00A00EFD   8D55F0                 lea     edx, [ebp-$10]

* Reference to SmartSearchForm
|
00A00F00   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSmartSearchForm.SearchString : TEdit
|
00A00F03   8B80F0020000           mov     eax, [eax+$02F0]

* Reference to: Controls.Proc_0094B1D8
|
00A00F09   E8CAA2F4FF             call    0094B1D8
00A00F0E   FF75F0                 push    dword ptr [ebp-$10]

* Possible String Reference to: '%') ORDER BY name'
|
00A00F11   68D810A000             push    $00A010D8
00A00F16   8D45F8                 lea     eax, [ebp-$08]
00A00F19   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904BAC
|
00A00F1E   E8893CF0FF             call    00904BAC
00A00F23   EB2B                   jmp     00A00F50

* Possible String Reference to: 'select memb___id from MEMB_INFO whe
|                                re memb___id like('%'
|
00A00F25   68F410A000             push    $00A010F4
00A00F2A   8D55EC                 lea     edx, [ebp-$14]

* Reference to SmartSearchForm
|
00A00F2D   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSmartSearchForm.SearchString : TEdit
|
00A00F30   8B80F0020000           mov     eax, [eax+$02F0]

* Reference to: Controls.Proc_0094B1D8
|
00A00F36   E89DA2F4FF             call    0094B1D8
00A00F3B   FF75EC                 push    dword ptr [ebp-$14]

* Possible String Reference to: '%') ORDER BY memb___id'
|
00A00F3E   683411A000             push    $00A01134
00A00F43   8D45F8                 lea     eax, [ebp-$08]
00A00F46   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904BAC
|
00A00F4B   E85C3CF0FF             call    00904BAC
00A00F50   8B06                   mov     eax, [esi]
00A00F52   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
00A00F55   E85E94F9FF             call    0099A3B8
00A00F5A   8B55F8                 mov     edx, [ebp-$08]
00A00F5D   8B08                   mov     ecx, [eax]
00A00F5F   FF5138                 call    dword ptr [ecx+$38]
00A00F62   8B06                   mov     eax, [esi]
00A00F64   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
00A00F67   E84456F8FF             call    009865B0
00A00F6C   8B06                   mov     eax, [esi]
00A00F6E   8B4060                 mov     eax, [eax+$60]
00A00F71   8B10                   mov     edx, [eax]
00A00F73   FF924C010000           call    dword ptr [edx+$014C]
00A00F79   85C0                   test    eax, eax
00A00F7B   7E10                   jle     00A00F8D

* Reference to SmartSearchForm
|
00A00F7D   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSmartSearchForm.OkButton : TBitBtn
|
00A00F80   8B8000030000           mov     eax, [eax+$0300]
00A00F86   B201                   mov     dl, $01
00A00F88   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TBitBtn.OFFS_64
|
00A00F8A   FF5164                 call    dword ptr [ecx+$64]
00A00F8D   8B06                   mov     eax, [esi]
00A00F8F   8B4060                 mov     eax, [eax+$60]
00A00F92   8B10                   mov     edx, [eax]
00A00F94   FF924C010000           call    dword ptr [edx+$014C]
00A00F9A   8BD8                   mov     ebx, eax
00A00F9C   83EB01                 sub     ebx, +$01
00A00F9F   7105                   jno     00A00FA6

* Reference to: System.Proc_00903928
|
00A00FA1   E88229F0FF             call    00903928
00A00FA6   85DB                   test    ebx, ebx
00A00FA8   7C3C                   jl      00A00FE6
00A00FAA   43                     inc     ebx
00A00FAB   8B06                   mov     eax, [esi]
00A00FAD   8B4060                 mov     eax, [eax+$60]
00A00FB0   8B4030                 mov     eax, [eax+$30]
00A00FB3   33D2                   xor     edx, edx

* Reference to: DB.Proc_0097CB48
|
00A00FB5   E88EBBF7FF             call    0097CB48
00A00FBA   8D55E8                 lea     edx, [ebp-$18]
00A00FBD   8B08                   mov     ecx, [eax]
00A00FBF   FF5160                 call    dword ptr [ecx+$60]
00A00FC2   8B55E8                 mov     edx, [ebp-$18]

* Reference to SmartSearchForm
|
00A00FC5   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A00FC8   8B80F8020000           mov     eax, [eax+$02F8]

* Reference to field TListBox.OFFS_0218
|
00A00FCE   8B8018020000           mov     eax, [eax+$0218]
00A00FD4   8B08                   mov     ecx, [eax]
00A00FD6   FF5138                 call    dword ptr [ecx+$38]
00A00FD9   8B06                   mov     eax, [esi]
00A00FDB   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_00988BD0
|
00A00FDE   E8ED7BF8FF             call    00988BD0
00A00FE3   4B                     dec     ebx
00A00FE4   75C5                   jnz     00A00FAB
00A00FE6   8B06                   mov     eax, [esi]
00A00FE8   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
00A00FEB   E8CC55F8FF             call    009865BC
00A00FF0   8B06                   mov     eax, [esi]
00A00FF2   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
00A00FF5   E8BE93F9FF             call    0099A3B8
00A00FFA   8B10                   mov     edx, [eax]
00A00FFC   FF5244                 call    dword ptr [edx+$44]

* Reference to SmartSearchForm
|
00A00FFF   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A01002   8B80F8020000           mov     eax, [eax+$02F8]
00A01008   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C0
|
00A0100A   FF92C0000000           call    dword ptr [edx+$00C0]

* Reference to SmartSearchForm
|
00A01010   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A01013   8B80F8020000           mov     eax, [eax+$02F8]

* Reference to field TListBox.OFFS_0218
|
00A01019   8B8018020000           mov     eax, [eax+$0218]
00A0101F   8B10                   mov     edx, [eax]
00A01021   FF5214                 call    dword ptr [edx+$14]
00A01024   85C0                   test    eax, eax
00A01026   7E13                   jle     00A0103B

* Reference to SmartSearchForm
|
00A01028   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A0102B   8B80F8020000           mov     eax, [eax+$02F8]
00A01031   33D2                   xor     edx, edx
00A01033   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TListBox.OFFS_00CC
|
00A01035   FF91CC000000           call    dword ptr [ecx+$00CC]
00A0103B   33C0                   xor     eax, eax
00A0103D   5A                     pop     edx
00A0103E   59                     pop     ecx
00A0103F   59                     pop     ecx
00A01040   648910                 mov     fs:[eax], edx
00A01043   EB12                   jmp     00A01057
00A01045   E97E2EF0FF             jmp     00903EC8

* Reference to SmartSearchForm
|
00A0104A   8B45FC                 mov     eax, [ebp-$04]

* Reference to : TApplication._PROC_0096912C()
|
00A0104D   E8DA80F6FF             call    0096912C

* Reference to: System.Proc_009042F4
|
00A01052   E89D32F0FF             call    009042F4

****** END
|
00A01057   33C0                   xor     eax, eax
00A01059   5A                     pop     edx
00A0105A   59                     pop     ecx
00A0105B   59                     pop     ecx
00A0105C   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[‹å]Ãÿÿÿÿ-'
|
00A0105F   689110A000             push    $00A01091
00A01064   8D45E8                 lea     eax, [ebp-$18]

* Reference to: System.Proc_00904834
|
00A01067   E8C837F0FF             call    00904834
00A0106C   8D45EC                 lea     eax, [ebp-$14]
00A0106F   BA02000000             mov     edx, $00000002

* Reference to: System.Proc_00904858
|
00A01074   E8DF37F0FF             call    00904858
00A01079   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.Proc_00904F58
|
00A0107C   E8D73EF0FF             call    00904F58
00A01081   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.Proc_00904834
|
00A01084   E8AB37F0FF             call    00904834
00A01089   C3                     ret

00A0108A   E9ED30F0FF             jmp     0090417C
00A0108F   EBD3                   jmp     00A01064

****** END
|
00A01091   5F                     pop     edi
00A01092   5E                     pop     esi
00A01093   5B                     pop     ebx
00A01094   8BE5                   mov     esp, ebp
00A01096   5D                     pop     ebp
00A01097   C3                     ret

*)
end;

procedure TSmartSearchForm.OkButtonClick(Sender : TObject);
begin
(*
00A0114C   55                     push    ebp
00A0114D   8BEC                   mov     ebp, esp
00A0114F   33C9                   xor     ecx, ecx
00A01151   51                     push    ecx
00A01152   51                     push    ecx
00A01153   51                     push    ecx
00A01154   51                     push    ecx
00A01155   51                     push    ecx
00A01156   53                     push    ebx
00A01157   56                     push    esi
00A01158   8BF0                   mov     esi, eax
00A0115A   33C0                   xor     eax, eax
00A0115C   55                     push    ebp

* Possible String Reference to: 'él.ðÿëÛ^[‹å]Ãÿÿÿÿ-'
|
00A0115D   680B13A000             push    $00A0130B
00A01162   64FF30                 push    dword ptr fs:[eax]
00A01165   648920                 mov     fs:[eax], esp

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A01168   8B86F8020000           mov     eax, [esi+$02F8]
00A0116E   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
00A01170   FF92C8000000           call    dword ptr [edx+$00C8]
00A01176   85C0                   test    eax, eax
00A01178   0F8C5A010000           jl      00A012D8

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A0117E   8B9EF8020000           mov     ebx, [esi+$02F8]

* Reference to field TListBox.OFFS_000C
|
00A01184   837B0C00               cmp     dword ptr [ebx+$0C], +$00
00A01188   0F8501010000           jnz     00A0128F
00A0118E   8BC3                   mov     eax, ebx
00A01190   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
00A01192   FF92C8000000           call    dword ptr [edx+$00C8]
00A01198   8BD0                   mov     edx, eax
00A0119A   8D4DFC                 lea     ecx, [ebp-$04]

* Reference to field TListBox.OFFS_0218
|
00A0119D   8B8318020000           mov     eax, [ebx+$0218]
00A011A3   8B18                   mov     ebx, [eax]
00A011A5   FF530C                 call    dword ptr [ebx+$0C]
00A011A8   8B55FC                 mov     edx, [ebp-$04]

* Reference to field TSmartSearchForm.OFFS_0308
|
00A011AB   8D8608030000           lea     eax, [esi+$0308]

* Reference to: System.Proc_00904888
|
00A011B1   E8D236F0FF             call    00904888
00A011B6   8D45F8                 lea     eax, [ebp-$08]

* Reference to pointer to GlobalVar_00A12174
|
00A011B9   8B1578FCA000           mov     edx, [$00A0FC78]
00A011BF   8B12                   mov     edx, [edx]

* Reference to: System.Proc_009050F4
|
00A011C1   E82E3FF0FF             call    009050F4
00A011C6   8B55F8                 mov     edx, [ebp-$08]

* Reference to TDataModule_Main instance
|
00A011C9   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A011CE   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
00A011D0   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009927E8
|
00A011D3   E81016F9FF             call    009927E8

* Reference to TDataModule_Main instance
|
00A011D8   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A011DD   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A011DF   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
00A011E2   E8D553F8FF             call    009865BC

* Reference to TDataModule_Main instance
|
00A011E7   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A011EC   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A011EE   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
00A011F1   E8C291F9FF             call    0099A3B8
00A011F6   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_44
|
00A011F8   FF5244                 call    dword ptr [edx+$44]

* Reference to TDataModule_Main instance
|
00A011FB   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A01200   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A01202   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
00A01205   E8AE91F9FF             call    0099A3B8
00A0120A   50                     push    eax

* Possible String Reference to: 'select AccountId from Character whe
|                                re name =''
|
00A0120B   682013A000             push    $00A01320
00A01210   FFB608030000           push    dword ptr [esi+$0308]
00A01216   685813A000             push    $00A01358
00A0121B   8D45F4                 lea     eax, [ebp-$0C]
00A0121E   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904BAC
|
00A01223   E88439F0FF             call    00904BAC
00A01228   8B55F4                 mov     edx, [ebp-$0C]
00A0122B   58                     pop     eax
00A0122C   8B08                   mov     ecx, [eax]
00A0122E   FF5138                 call    dword ptr [ecx+$38]

* Reference to TDataModule_Main instance
|
00A01231   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A01236   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A01238   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
00A0123B   E87053F8FF             call    009865B0

* Reference to TDataModule_Main instance
|
00A01240   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A01245   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A01247   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
00A0124A   8B4030                 mov     eax, [eax+$30]
00A0124D   33D2                   xor     edx, edx

* Reference to: DB.Proc_0097CB48
|
00A0124F   E8F4B8F7FF             call    0097CB48
00A01254   8D55F0                 lea     edx, [ebp-$10]
00A01257   8B08                   mov     ecx, [eax]
00A01259   FF5160                 call    dword ptr [ecx+$60]
00A0125C   8B55F0                 mov     edx, [ebp-$10]

* Reference to field TSmartSearchForm.OFFS_030C
|
00A0125F   8D860C030000           lea     eax, [esi+$030C]

* Reference to: System.Proc_00904888
|
00A01265   E81E36F0FF             call    00904888

* Reference to TDataModule_Main instance
|
00A0126A   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0126F   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A01271   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
00A01274   E84353F8FF             call    009865BC

* Reference to TDataModule_Main instance
|
00A01279   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A0127E   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
00A01280   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
00A01283   E83091F9FF             call    0099A3B8
00A01288   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_44
|
00A0128A   FF5244                 call    dword ptr [edx+$44]
00A0128D   EB39                   jmp     00A012C8

* Reference to field TSmartSearchForm.OFFS_0308
|
00A0128F   8D8608030000           lea     eax, [esi+$0308]

* Reference to: System.Proc_00904834
|
00A01295   E89A35F0FF             call    00904834

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A0129A   8B9EF8020000           mov     ebx, [esi+$02F8]
00A012A0   8BC3                   mov     eax, ebx
00A012A2   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
00A012A4   FF92C8000000           call    dword ptr [edx+$00C8]
00A012AA   8BD0                   mov     edx, eax
00A012AC   8D4DEC                 lea     ecx, [ebp-$14]

* Reference to field TListBox.OFFS_0218
|
00A012AF   8B8318020000           mov     eax, [ebx+$0218]
00A012B5   8B18                   mov     ebx, [eax]
00A012B7   FF530C                 call    dword ptr [ebx+$0C]
00A012BA   8B55EC                 mov     edx, [ebp-$14]

* Reference to field TSmartSearchForm.OFFS_030C
|
00A012BD   8D860C030000           lea     eax, [esi+$030C]

* Reference to: System.Proc_00904888
|
00A012C3   E8C035F0FF             call    00904888

* Reference to control TSmartSearchForm.SearchString : TEdit
|
00A012C8   8B86F0020000           mov     eax, [esi+$02F0]
00A012CE   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00C0
|
00A012D0   FF92C0000000           call    dword ptr [edx+$00C0]
00A012D6   EB08                   jmp     00A012E0
00A012D8   33C0                   xor     eax, eax

* Reference to field TSmartSearchForm.OFFS_024C
|
00A012DA   89864C020000           mov     [esi+$024C], eax
00A012E0   33C0                   xor     eax, eax
00A012E2   5A                     pop     edx
00A012E3   59                     pop     ecx
00A012E4   59                     pop     ecx
00A012E5   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[‹å]Ãÿÿÿÿ-'
|
00A012E8   681213A000             push    $00A01312
00A012ED   8D45EC                 lea     eax, [ebp-$14]
00A012F0   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904858
|
00A012F5   E85E35F0FF             call    00904858
00A012FA   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.Proc_00904F58
|
00A012FD   E8563CF0FF             call    00904F58
00A01302   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
00A01305   E82A35F0FF             call    00904834
00A0130A   C3                     ret

00A0130B   E96C2EF0FF             jmp     0090417C
00A01310   EBDB                   jmp     00A012ED

****** END
|
00A01312   5E                     pop     esi
00A01313   5B                     pop     ebx
00A01314   8BE5                   mov     esp, ebp
00A01316   5D                     pop     ebp
00A01317   C3                     ret

*)
end;

procedure TSmartSearchForm.SearchResultKeyPress(Sender : TObject);
begin
(*
00A0135C   53                     push    ebx
00A0135D   56                     push    esi
00A0135E   57                     push    edi
00A0135F   8BF9                   mov     edi, ecx
00A01361   8BD8                   mov     ebx, eax
00A01363   803F0D                 cmp     byte ptr [edi], $0D
00A01366   7521                   jnz     00A01389

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A01368   8B83F8020000           mov     eax, [ebx+$02F8]
00A0136E   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
00A01370   FF92C8000000           call    dword ptr [edx+$00C8]
00A01376   85C0                   test    eax, eax
00A01378   7C0F                   jl      00A01389

* Reference to control TSmartSearchForm.OkButton : TBitBtn
|
00A0137A   8B8300030000           mov     eax, [ebx+$0300]
00A01380   66BEEBFF               mov     si, $FFEB

* Reference to: System.Proc_00903BE4
|
00A01384   E85B28F0FF             call    00903BE4
00A01389   803F1B                 cmp     byte ptr [edi], $1B
00A0138C   750E                   jnz     00A0139C

* Reference to control TSmartSearchForm.SearchString : TEdit
|
00A0138E   8B83F0020000           mov     eax, [ebx+$02F0]
00A01394   8B10                   mov     edx, [eax]

* Possible reference to virtual method TEdit.OFFS_00C0
|
00A01396   FF92C0000000           call    dword ptr [edx+$00C0]
00A0139C   5F                     pop     edi
00A0139D   5E                     pop     esi
00A0139E   5B                     pop     ebx
00A0139F   C3                     ret

*)
end;

procedure TSmartSearchForm.SearchStringKeyDown(Sender : TObject);
begin
(*
00A013DC   55                     push    ebp
00A013DD   8BEC                   mov     ebp, esp
00A013DF   53                     push    ebx
00A013E0   56                     push    esi
00A013E1   8BF1                   mov     esi, ecx
00A013E3   8BD8                   mov     ebx, eax
00A013E5   66833E26               cmp     word ptr [esi], +$26
00A013E9   750D                   jnz     00A013F8
00A013EB   33D2                   xor     edx, edx

* Reference to control TSmartSearchForm.SearchWith : TRadioGroup
|
00A013ED   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to : TGroupButton._PROC_00941ACC()
|
00A013F3   E8D406F4FF             call    00941ACC
00A013F8   66833E28               cmp     word ptr [esi], +$28
00A013FC   7510                   jnz     00A0140E
00A013FE   BA01000000             mov     edx, $00000001

* Reference to control TSmartSearchForm.SearchWith : TRadioGroup
|
00A01403   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to : TGroupButton._PROC_00941ACC()
|
00A01409   E8BE06F4FF             call    00941ACC
00A0140E   5E                     pop     esi
00A0140F   5B                     pop     ebx
00A01410   5D                     pop     ebp
00A01411   C20400                 ret     $0004

*)
end;

procedure TSmartSearchForm.SearchResultDblClick(Sender : TObject);
begin
(*
00A01414   56                     push    esi

* Reference to control TSmartSearchForm.OkButton : TBitBtn
|
00A01415   8B8000030000           mov     eax, [eax+$0300]
00A0141B   66BEEBFF               mov     si, $FFEB

* Reference to: System.Proc_00903BE4
|
00A0141F   E8C027F0FF             call    00903BE4
00A01424   5E                     pop     esi
00A01425   C3                     ret

*)
end;

procedure TSmartSearchForm._PROC_00A013A0(Sender : TObject);
begin
(*
00A013A0   53                     push    ebx
00A013A1   8BD8                   mov     ebx, eax

* Reference to control TSmartSearchForm.SearchResult : TListBox
|
00A013A3   8B83F8020000           mov     eax, [ebx+$02F8]
00A013A9   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00D4
|
00A013AB   FF92D4000000           call    dword ptr [edx+$00D4]
00A013B1   33D2                   xor     edx, edx

* Reference to control TSmartSearchForm.SearchString : TEdit
|
00A013B3   8B83F0020000           mov     eax, [ebx+$02F0]

* Reference to: Controls.Proc_0094B208
|
00A013B9   E84A9EF4FF             call    0094B208
00A013BE   33D2                   xor     edx, edx

* Reference to control TSmartSearchForm.SearchWith : TRadioGroup
|
00A013C0   8B83FC020000           mov     eax, [ebx+$02FC]

* Reference to : TGroupButton._PROC_00941ACC()
|
00A013C6   E80107F4FF             call    00941ACC
00A013CB   33D2                   xor     edx, edx

* Reference to control TSmartSearchForm.OkButton : TBitBtn
|
00A013CD   8B8300030000           mov     eax, [ebx+$0300]
00A013D3   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TBitBtn.OFFS_64
|
00A013D5   FF5164                 call    dword ptr [ecx+$64]
00A013D8   B001                   mov     al, $01
00A013DA   5B                     pop     ebx
00A013DB   C3                     ret

*)
end;

procedure TSmartSearchForm._PROC_00A01428(Sender : TObject);
begin
(*
00A01428   55                     push    ebp
00A01429   8BEC                   mov     ebp, esp
00A0142B   33C0                   xor     eax, eax
00A0142D   55                     push    ebp
00A0142E   684D14A000             push    $00A0144D
00A01433   64FF30                 push    dword ptr fs:[eax]
00A01436   648920                 mov     fs:[eax], esp
00A01439   FF051021A100           inc     dword ptr [$00A12110]
00A0143F   33C0                   xor     eax, eax
00A01441   5A                     pop     edx
00A01442   59                     pop     ecx
00A01443   59                     pop     ecx
00A01444   648910                 mov     fs:[eax], edx

****** FINALLY
|
00A01447   685414A000             push    $00A01454
00A0144C   C3                     ret

00A0144D   E92A2DF0FF             jmp     0090417C
00A01452   EBF8                   jmp     00A0144C

****** END
|
00A01454   5D                     pop     ebp
00A01455   C3                     ret

*)
end;

procedure TSmartSearchForm._PROC_00A01458(Sender : TObject);
begin
(*
00A01458   832D1021A10001         sub     dword ptr [$00A12110], +$01
00A0145F   C3                     ret

*)
end;

end.