unit SqlQuery;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TSqlQueryForm=class(TForm)
    GroupBox12: TGroupBox;
    query: TMemo;
    SqlQueryApply: TButton;
    SqlQueryClear: TButton;
    GroupBox13: TGroupBox;
    columnname: TLabeledEdit;
    tablename: TLabeledEdit;
    GenerateSqlScrypt: TButton;
    procedure GenerateSqlScryptClick(Sender : TObject);
    procedure SqlQueryApplyClick(Sender : TObject);
    procedure SqlQueryClearClick(Sender : TObject);
    procedure _PROC_00A018B5(Sender : TObject);
    procedure _PROC_00A018E4(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  SqlQueryForm: TSqlQueryForm;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TSqlQueryForm.GenerateSqlScryptClick(Sender : TObject);
begin
(*
00A016CC   55                     push    ebp
00A016CD   8BEC                   mov     ebp, esp
00A016CF   33C9                   xor     ecx, ecx
00A016D1   51                     push    ecx
00A016D2   51                     push    ecx
00A016D3   51                     push    ecx
00A016D4   51                     push    ecx
00A016D5   53                     push    ebx
00A016D6   8BD8                   mov     ebx, eax
00A016D8   33C0                   xor     eax, eax
00A016DA   55                     push    ebp
00A016DB   686517A000             push    $00A01765
00A016E0   64FF30                 push    dword ptr fs:[eax]
00A016E3   648920                 mov     fs:[eax], esp
00A016E6   8D55FC                 lea     edx, [ebp-$04]

* Reference to control TSqlQueryForm.tablename : TLabeledEdit
|
00A016E9   8B8308030000           mov     eax, [ebx+$0308]

* Reference to: Controls.Proc_0094B1D8
|
00A016EF   E8E49AF4FF             call    0094B1D8
00A016F4   8D55F8                 lea     edx, [ebp-$08]

* Reference to control TSqlQueryForm.columnname : TLabeledEdit
|
00A016F7   8B8304030000           mov     eax, [ebx+$0304]

* Reference to: Controls.Proc_0094B1D8
|
00A016FD   E8D69AF4FF             call    0094B1D8
00A01702   8D45F4                 lea     eax, [ebp-$0C]

* Possible String Reference to: 'smallint'
|
00A01705   BA7C17A000             mov     edx, $00A0177C

* Reference to: System.Proc_009048CC
|
00A0170A   E8BD31F0FF             call    009048CC

* Possible String Reference to: 'ALTER TABLE '
|
00A0170F   689017A000             push    $00A01790
00A01714   FF75FC                 push    dword ptr [ebp-$04]

* Possible String Reference to: ' ADD '
|
00A01717   68A817A000             push    $00A017A8
00A0171C   FF75F8                 push    dword ptr [ebp-$08]
00A0171F   68B817A000             push    $00A017B8
00A01724   FF75F4                 push    dword ptr [ebp-$0C]
00A01727   6A00                   push    $00
00A01729   8D45F0                 lea     eax, [ebp-$10]
00A0172C   BA07000000             mov     edx, $00000007

* Reference to: System.Proc_00904BAC
|
00A01731   E87634F0FF             call    00904BAC
00A01736   8B55F0                 mov     edx, [ebp-$10]

* Reference to control TSqlQueryForm.query : TMemo
|
00A01739   8B83F4020000           mov     eax, [ebx+$02F4]

* Reference to field TMemo.OFFS_0220
|
00A0173F   8B8020020000           mov     eax, [eax+$0220]
00A01745   8B08                   mov     ecx, [eax]
00A01747   FF5138                 call    dword ptr [ecx+$38]
00A0174A   33C0                   xor     eax, eax
00A0174C   5A                     pop     edx
00A0174D   59                     pop     ecx
00A0174E   59                     pop     ecx
00A0174F   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[‹å]Ã'
|
00A01752   686C17A000             push    $00A0176C
00A01757   8D45F0                 lea     eax, [ebp-$10]
00A0175A   BA04000000             mov     edx, $00000004

* Reference to: System.Proc_00904858
|
00A0175F   E8F430F0FF             call    00904858
00A01764   C3                     ret

00A01765   E9122AF0FF             jmp     0090417C
00A0176A   EBEB                   jmp     00A01757

****** END
|
00A0176C   5B                     pop     ebx
00A0176D   8BE5                   mov     esp, ebp
00A0176F   5D                     pop     ebp
00A01770   C3                     ret

*)
end;

procedure TSqlQueryForm.SqlQueryApplyClick(Sender : TObject);
begin
(*
00A017BC   55                     push    ebp
00A017BD   8BEC                   mov     ebp, esp
00A017BF   33C9                   xor     ecx, ecx
00A017C1   51                     push    ecx
00A017C2   51                     push    ecx
00A017C3   51                     push    ecx
00A017C4   51                     push    ecx
00A017C5   51                     push    ecx
00A017C6   53                     push    ebx
00A017C7   8BD8                   mov     ebx, eax
00A017C9   33C0                   xor     eax, eax
00A017CB   55                     push    ebp

* Possible String Reference to: 'éñ(ðÿëÐ[‹å]Ã'
|
00A017CC   688618A000             push    $00A01886
00A017D1   64FF30                 push    dword ptr fs:[eax]
00A017D4   648920                 mov     fs:[eax], esp
00A017D7   8D45F8                 lea     eax, [ebp-$08]

* Reference to pointer to GlobalVar_00A12174
|
00A017DA   8B1578FCA000           mov     edx, [$00A0FC78]
00A017E0   8B12                   mov     edx, [edx]

* Reference to: System.Proc_009050F4
|
00A017E2   E80D39F0FF             call    009050F4
00A017E7   8B55F8                 mov     edx, [ebp-$08]

* Reference to TDataModule_Main instance
|
00A017EA   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A017EF   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
00A017F1   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009927E8
|
00A017F4   E8EF0FF9FF             call    009927E8
00A017F9   689C18A000             push    $00A0189C
00A017FE   8D55F4                 lea     edx, [ebp-$0C]

* Reference to control TSqlQueryForm.query : TMemo
|
00A01801   8B83F4020000           mov     eax, [ebx+$02F4]

* Reference to: Controls.Proc_0094B1D8
|
00A01807   E8CC99F4FF             call    0094B1D8
00A0180C   FF75F4                 push    dword ptr [ebp-$0C]
00A0180F   689C18A000             push    $00A0189C
00A01814   8D45FC                 lea     eax, [ebp-$04]
00A01817   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904BAC
|
00A0181C   E88B33F0FF             call    00904BAC
00A01821   8D45F0                 lea     eax, [ebp-$10]
00A01824   8B55FC                 mov     edx, [ebp-$04]

* Reference to: System.Proc_009050F4
|
00A01827   E8C838F0FF             call    009050F4
00A0182C   8B55F0                 mov     edx, [ebp-$10]

* Reference to TDataModule_Main instance
|
00A0182F   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A01834   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
00A01836   8B405C                 mov     eax, [eax+$5C]
00A01839   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TADOCommand.OFFS_38
|
00A0183B   FF5138                 call    dword ptr [ecx+$38]
00A0183E   8D55EC                 lea     edx, [ebp-$14]

* Reference to TDataModule_Main instance
|
00A01841   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
00A01846   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.cmtDB : TADOCommand
|
00A01848   8B405C                 mov     eax, [eax+$5C]

* Reference to: ADODB.Proc_009920D0
|
00A0184B   E88008F9FF             call    009920D0
00A01850   33C0                   xor     eax, eax
00A01852   5A                     pop     edx
00A01853   59                     pop     ecx
00A01854   59                     pop     ecx
00A01855   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '[‹å]Ã'
|
00A01858   688D18A000             push    $00A0188D
00A0185D   8D45EC                 lea     eax, [ebp-$14]

* Reference to: System.Proc_0090690C
|
00A01860   E8A750F0FF             call    0090690C
00A01865   8D45F0                 lea     eax, [ebp-$10]

* Reference to: System.Proc_00904F58
|
00A01868   E8EB36F0FF             call    00904F58
00A0186D   8D45F4                 lea     eax, [ebp-$0C]

* Reference to: System.Proc_00904834
|
00A01870   E8BF2FF0FF             call    00904834
00A01875   8D45F8                 lea     eax, [ebp-$08]

* Reference to: System.Proc_00904F58
|
00A01878   E8DB36F0FF             call    00904F58
00A0187D   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
00A01880   E8AF2FF0FF             call    00904834
00A01885   C3                     ret

00A01886   E9F128F0FF             jmp     0090417C
00A0188B   EBD0                   jmp     00A0185D

****** END
|
00A0188D   5B                     pop     ebx
00A0188E   8BE5                   mov     esp, ebp
00A01890   5D                     pop     ebp
00A01891   C3                     ret

*)
end;

procedure TSqlQueryForm.SqlQueryClearClick(Sender : TObject);
begin
(*

* Reference to control TSqlQueryForm.query : TMemo
|
00A018A0   8B80F4020000           mov     eax, [eax+$02F4]

* Reference to field TMemo.OFFS_0220
|
00A018A6   8B8020020000           mov     eax, [eax+$0220]
00A018AC   8B10                   mov     edx, [eax]
00A018AE   FF5244                 call    dword ptr [edx+$44]
00A018B1   C3                     ret

*)
end;

procedure TSqlQueryForm._PROC_00A018B5(Sender : TObject);
begin
(*
00A018B5   8BEC                   mov     ebp, esp
00A018B7   33C0                   xor     eax, eax
00A018B9   55                     push    ebp
00A018BA   68D918A000             push    $00A018D9
00A018BF   64FF30                 push    dword ptr fs:[eax]
00A018C2   648920                 mov     fs:[eax], esp
00A018C5   FF051821A100           inc     dword ptr [$00A12118]
00A018CB   33C0                   xor     eax, eax
00A018CD   5A                     pop     edx
00A018CE   59                     pop     ecx
00A018CF   59                     pop     ecx
00A018D0   648910                 mov     fs:[eax], edx

****** FINALLY
|
00A018D3   68E018A000             push    $00A018E0
00A018D8   C3                     ret

00A018D9   E99E28F0FF             jmp     0090417C
00A018DE   EBF8                   jmp     00A018D8

****** END
|
00A018E0   5D                     pop     ebp
00A018E1   C3                     ret

*)
end;

procedure TSqlQueryForm._PROC_00A018E4(Sender : TObject);
begin
(*
00A018E4   832D1821A10001         sub     dword ptr [$00A12118], +$01
00A018EB   C3                     ret

*)
end;

end.