unit top100Unit;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls
type
  TTop100Form=class(TForm)
    GroupBox7: TGroupBox;
    level: TLabel;
    toplevel: TLabel;
    Strength: TLabel;
    strengla: TLabel;
    Agility: TLabel;
    agilla: TLabel;
    Vitality: TLabel;
    vitalla: TLabel;
    Energy: TLabel;
    energyla: TLabel;
    Label65: TLabel;
    otherla: TLabel;
    classcap: TLabel;
    Classla: TLabel;
    Label62: TLabel;
    Label70: TLabel;
    toplist: TListBox;
    reschecker: TCheckBox;
    addToRemembered: TSpeedButton;
    BitBtn1: TBitBtn;
    procedure toplistClick(Sender : TObject);
    procedure FormKeyPress(Sender : TObject);
    procedure addToRememberedClick(Sender : TObject);
    procedure BitBtn1Click(Sender : TObject);
    procedure _PROC_009FAD74(Sender : TObject);
    procedure _PROC_009FB82B(Sender : TObject);
    procedure _PROC_009FB8C4(Sender : TObject);
    procedure _PROC_009FB8F4(Sender : TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Top100Form: TTop100Form;

{This file is generated by DelphiDecompiler version 1.1 Copyright (c) 1997-2009 BitMaker}

implementation

{$R *.DFM}

procedure TTop100Form.toplistClick(Sender : TObject);
begin
(*
009FAF30   55                     push    ebp
009FAF31   8BEC                   mov     ebp, esp
009FAF33   B90C000000             mov     ecx, $0000000C
009FAF38   6A00                   push    $00
009FAF3A   6A00                   push    $00
009FAF3C   49                     dec     ecx
009FAF3D   75F9                   jnz     009FAF38
009FAF3F   51                     push    ecx
009FAF40   53                     push    ebx
009FAF41   56                     push    esi
009FAF42   57                     push    edi
009FAF43   8945FC                 mov     [ebp-$04], eax

* Reference to TDataModule_Main instance
|
009FAF46   8B1D8CFBA000           mov     ebx, [$00A0FB8C]
009FAF4C   33C0                   xor     eax, eax
009FAF4E   55                     push    ebp

* Possible String Reference to: 'éú‹ðÿëë_^[‹å]Ã'
|
009FAF4F   687DB59F00             push    $009FB57D
009FAF54   64FF30                 push    dword ptr fs:[eax]
009FAF57   648920                 mov     fs:[eax], esp
009FAF5A   33D2                   xor     edx, edx
009FAF5C   55                     push    ebp
009FAF5D   6835B59F00             push    $009FB535
009FAF62   64FF32                 push    dword ptr fs:[edx]
009FAF65   648922                 mov     fs:[edx], esp
009FAF68   C645FB00               mov     byte ptr [ebp-$05], $00

* Reference to Top100Form
|
009FAF6C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.toplist : TListBox
|
009FAF6F   8B8034030000           mov     eax, [eax+$0334]
009FAF75   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FAF77   FF92C8000000           call    dword ptr [edx+$00C8]
009FAF7D   85C0                   test    eax, eax
009FAF7F   0F9DC2                 setnl   dl

* Reference to Top100Form
|
009FAF82   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.addToRemembered : TSpeedButton
|
009FAF85   8B803C030000           mov     eax, [eax+$033C]
009FAF8B   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TSpeedButton.OFFS_64
|
009FAF8D   FF5164                 call    dword ptr [ecx+$64]

* Reference to Top100Form
|
009FAF90   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.reschecker : TCheckBox
|
009FAF93   8B8038030000           mov     eax, [eax+$0338]

* Reference to field TCheckBox.OFFS_0212
|
009FAF99   80B81202000001         cmp     byte ptr [eax+$0212], $01
009FAFA0   0F85A3000000           jnz     009FB049
009FAFA6   C645FB01               mov     byte ptr [ebp-$05], $01
009FAFAA   8B03                   mov     eax, [ebx]

* Reference to field TCheckBox.OFFS_0060
|
009FAFAC   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FAFAF   E808B6F8FF             call    009865BC
009FAFB4   8B03                   mov     eax, [ebx]
009FAFB6   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FAFB9   E8FAF3F9FF             call    0099A3B8
009FAFBE   8B10                   mov     edx, [eax]
009FAFC0   FF5244                 call    dword ptr [edx+$44]

* Possible String Reference to: 'select ch.cLevel,ch.Strength,ch.Vit
|                                ality,ch.Dexterity,ch.Energy,ch.Ctl
|                                Code,ch.Class,rt.'
|
009FAFC3   6894B59F00             push    $009FB594

* Reference to pointer to GlobalVar_00A12168
|
009FAFC8   A1D8FFA000             mov     eax, dword ptr [$00A0FFD8]
009FAFCD   FF30                   push    dword ptr [eax]

* Possible String Reference to: ' from Character ch, '
|
009FAFCF   68F4B59F00             push    $009FB5F4

* Reference to pointer to GlobalVar_00A1216C
|
009FAFD4   A14CFDA000             mov     eax, dword ptr [$00A0FD4C]
009FAFD9   FF30                   push    dword ptr [eax]

* Possible String Reference to: ' rt where (ch.Name=''
|
009FAFDB   6814B69F00             push    $009FB614

* Reference to Top100Form
|
009FAFE0   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.toplist : TListBox
|
009FAFE3   8BB034030000           mov     esi, [eax+$0334]
009FAFE9   8BC6                   mov     eax, esi
009FAFEB   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FAFED   FF92C8000000           call    dword ptr [edx+$00C8]
009FAFF3   8BD0                   mov     edx, eax
009FAFF5   8D4DF0                 lea     ecx, [ebp-$10]

* Reference to field TListBox.OFFS_0218
|
009FAFF8   8B8618020000           mov     eax, [esi+$0218]
009FAFFE   8B30                   mov     esi, [eax]
009FB000   FF560C                 call    dword ptr [esi+$0C]
009FB003   FF75F0                 push    dword ptr [ebp-$10]

* Possible String Reference to: '') and  ch.name = rt.'
|
009FB006   6834B69F00             push    $009FB634

* Reference to pointer to GlobalVar_00A12170
|
009FB00B   A194FBA000             mov     eax, dword ptr [$00A0FB94]
009FB010   FF30                   push    dword ptr [eax]

* Possible String Reference to: ' order by rt.'
|
009FB012   6854B69F00             push    $009FB654

* Reference to pointer to GlobalVar_00A12168
|
009FB017   A1D8FFA000             mov     eax, dword ptr [$00A0FFD8]
009FB01C   FF30                   push    dword ptr [eax]
009FB01E   8D45F4                 lea     eax, [ebp-$0C]
009FB021   BA0A000000             mov     edx, $0000000A

* Reference to: System.Proc_00904BAC
|
009FB026   E8819BF0FF             call    00904BAC
009FB02B   8B45F4                 mov     eax, [ebp-$0C]
009FB02E   50                     push    eax
009FB02F   8B03                   mov     eax, [ebx]
009FB031   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FB034   E87FF3F9FF             call    0099A3B8
009FB039   5A                     pop     edx
009FB03A   8B08                   mov     ecx, [eax]
009FB03C   FF5138                 call    dword ptr [ecx+$38]
009FB03F   8B03                   mov     eax, [ebx]
009FB041   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
009FB044   E867B5F8FF             call    009865B0

* Reference to Top100Form
|
009FB049   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.reschecker : TCheckBox
|
009FB04C   8B8038030000           mov     eax, [eax+$0338]

* Reference to field TCheckBox.OFFS_0212
|
009FB052   80B81202000001         cmp     byte ptr [eax+$0212], $01
009FB059   7511                   jnz     009FB06C
009FB05B   8B03                   mov     eax, [ebx]

* Reference to field TCheckBox.OFFS_0060
|
009FB05D   8B4060                 mov     eax, [eax+$60]
009FB060   8B10                   mov     edx, [eax]
009FB062   FF924C010000           call    dword ptr [edx+$014C]
009FB068   85C0                   test    eax, eax
009FB06A   7F78                   jnle    009FB0E4
009FB06C   C645FB00               mov     byte ptr [ebp-$05], $00
009FB070   8B03                   mov     eax, [ebx]
009FB072   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FB075   E842B5F8FF             call    009865BC
009FB07A   8B03                   mov     eax, [ebx]
009FB07C   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FB07F   E834F3F9FF             call    0099A3B8
009FB084   8B10                   mov     edx, [eax]
009FB086   FF5244                 call    dword ptr [edx+$44]

* Possible String Reference to: 'select cLevel,Strength,Vitality,Dex
|                                terity,Energy,CtlCode,Class from Ch
|                                aracter where Name=''
|
009FB089   686CB69F00             push    $009FB66C

* Reference to Top100Form
|
009FB08E   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.toplist : TListBox
|
009FB091   8BB034030000           mov     esi, [eax+$0334]
009FB097   8BC6                   mov     eax, esi
009FB099   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FB09B   FF92C8000000           call    dword ptr [edx+$00C8]
009FB0A1   8BD0                   mov     edx, eax
009FB0A3   8D4DE8                 lea     ecx, [ebp-$18]

* Reference to field TListBox.OFFS_0218
|
009FB0A6   8B8618020000           mov     eax, [esi+$0218]
009FB0AC   8B30                   mov     esi, [eax]
009FB0AE   FF560C                 call    dword ptr [esi+$0C]
009FB0B1   FF75E8                 push    dword ptr [ebp-$18]

* Possible String Reference to: '' '
|
009FB0B4   68D0B69F00             push    $009FB6D0
009FB0B9   8D45EC                 lea     eax, [ebp-$14]
009FB0BC   BA03000000             mov     edx, $00000003

* Reference to: System.Proc_00904BAC
|
009FB0C1   E8E69AF0FF             call    00904BAC
009FB0C6   8B45EC                 mov     eax, [ebp-$14]
009FB0C9   50                     push    eax
009FB0CA   8B03                   mov     eax, [ebx]
009FB0CC   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FB0CF   E8E4F2F9FF             call    0099A3B8
009FB0D4   5A                     pop     edx
009FB0D5   8B08                   mov     ecx, [eax]
009FB0D7   FF5138                 call    dword ptr [ecx+$38]
009FB0DA   8B03                   mov     eax, [ebx]
009FB0DC   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
009FB0DF   E8CCB4F8FF             call    009865B0
009FB0E4   8B03                   mov     eax, [ebx]
009FB0E6   8B4060                 mov     eax, [eax+$60]
009FB0E9   8B10                   mov     edx, [eax]
009FB0EB   FF924C010000           call    dword ptr [edx+$014C]
009FB0F1   8BF0                   mov     esi, eax
009FB0F3   85F6                   test    esi, esi
009FB0F5   7C2C                   jl      009FB123
009FB0F7   46                     inc     esi
009FB0F8   8B03                   mov     eax, [ebx]
009FB0FA   8B4060                 mov     eax, [eax+$60]
009FB0FD   8B4030                 mov     eax, [eax+$30]
009FB100   33D2                   xor     edx, edx

* Reference to: DB.Proc_0097CB48
|
009FB102   E8411AF8FF             call    0097CB48
009FB107   8D55E4                 lea     edx, [ebp-$1C]
009FB10A   8B08                   mov     ecx, [eax]
009FB10C   FF5160                 call    dword ptr [ecx+$60]
009FB10F   8B55E4                 mov     edx, [ebp-$1C]

* Reference to Top100Form
|
009FB112   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.toplevel : TLabel
|
009FB115   8B80F8020000           mov     eax, [eax+$02F8]

* Reference to: Controls.Proc_0094B208
|
009FB11B   E8E800F5FF             call    0094B208
009FB120   4E                     dec     esi
009FB121   75D5                   jnz     009FB0F8
009FB123   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB125   8B4060                 mov     eax, [eax+$60]
009FB128   8B4030                 mov     eax, [eax+$30]
009FB12B   BA06000000             mov     edx, $00000006

* Reference to: DB.Proc_0097CB48
|
009FB130   E8131AF8FF             call    0097CB48
009FB135   8D55E0                 lea     edx, [ebp-$20]
009FB138   8B08                   mov     ecx, [eax]
009FB13A   FF5160                 call    dword ptr [ecx+$60]
009FB13D   8B45E0                 mov     eax, [ebp-$20]
009FB140   BADCB69F00             mov     edx, $009FB6DC

* Reference to: System.Proc_00904C30
|
009FB145   E8E69AF0FF             call    00904C30
009FB14A   7513                   jnz     009FB15F

* Reference to Top100Form
|
009FB14C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.Classla : TLabel
|
009FB14F   8B8028030000           mov     eax, [eax+$0328]

* Possible String Reference to: 'Dark Wizard'
|
009FB155   BAE8B69F00             mov     edx, $009FB6E8

* Reference to: Controls.Proc_0094B208
|
009FB15A   E8A900F5FF             call    0094B208
009FB15F   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB161   8B4060                 mov     eax, [eax+$60]
009FB164   8B4030                 mov     eax, [eax+$30]
009FB167   BA06000000             mov     edx, $00000006

* Reference to: DB.Proc_0097CB48
|
009FB16C   E8D719F8FF             call    0097CB48
009FB171   8D55DC                 lea     edx, [ebp-$24]
009FB174   8B08                   mov     ecx, [eax]
009FB176   FF5160                 call    dword ptr [ecx+$60]
009FB179   8B45DC                 mov     eax, [ebp-$24]
009FB17C   BAFCB69F00             mov     edx, $009FB6FC

* Reference to: System.Proc_00904C30
|
009FB181   E8AA9AF0FF             call    00904C30
009FB186   7513                   jnz     009FB19B

* Reference to Top100Form
|
009FB188   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.Classla : TLabel
|
009FB18B   8B8028030000           mov     eax, [eax+$0328]

* Possible String Reference to: 'Soul Master'
|
009FB191   BA08B79F00             mov     edx, $009FB708

* Reference to: Controls.Proc_0094B208
|
009FB196   E86D00F5FF             call    0094B208
009FB19B   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB19D   8B4060                 mov     eax, [eax+$60]
009FB1A0   8B4030                 mov     eax, [eax+$30]
009FB1A3   BA06000000             mov     edx, $00000006

* Reference to: DB.Proc_0097CB48
|
009FB1A8   E89B19F8FF             call    0097CB48
009FB1AD   8D55D8                 lea     edx, [ebp-$28]
009FB1B0   8B08                   mov     ecx, [eax]
009FB1B2   FF5160                 call    dword ptr [ecx+$60]
009FB1B5   8B45D8                 mov     eax, [ebp-$28]

* Possible String Reference to: '16'
|
009FB1B8   BA1CB79F00             mov     edx, $009FB71C

* Reference to: System.Proc_00904C30
|
009FB1BD   E86E9AF0FF             call    00904C30
009FB1C2   7513                   jnz     009FB1D7

* Reference to Top100Form
|
009FB1C4   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.Classla : TLabel
|
009FB1C7   8B8028030000           mov     eax, [eax+$0328]

* Possible String Reference to: 'Dark Knight'
|
009FB1CD   BA28B79F00             mov     edx, $009FB728

* Reference to: Controls.Proc_0094B208
|
009FB1D2   E83100F5FF             call    0094B208
009FB1D7   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB1D9   8B4060                 mov     eax, [eax+$60]
009FB1DC   8B4030                 mov     eax, [eax+$30]
009FB1DF   BA06000000             mov     edx, $00000006

* Reference to: DB.Proc_0097CB48
|
009FB1E4   E85F19F8FF             call    0097CB48
009FB1E9   8D55D4                 lea     edx, [ebp-$2C]
009FB1EC   8B08                   mov     ecx, [eax]
009FB1EE   FF5160                 call    dword ptr [ecx+$60]
009FB1F1   8B45D4                 mov     eax, [ebp-$2C]

* Possible String Reference to: '17'
|
009FB1F4   BA3CB79F00             mov     edx, $009FB73C

* Reference to: System.Proc_00904C30
|
009FB1F9   E8329AF0FF             call    00904C30
009FB1FE   7513                   jnz     009FB213

* Reference to Top100Form
|
009FB200   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.Classla : TLabel
|
009FB203   8B8028030000           mov     eax, [eax+$0328]

* Possible String Reference to: 'Blade Knight'
|
009FB209   BA48B79F00             mov     edx, $009FB748

* Reference to: Controls.Proc_0094B208
|
009FB20E   E8F5FFF4FF             call    0094B208
009FB213   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB215   8B4060                 mov     eax, [eax+$60]
009FB218   8B4030                 mov     eax, [eax+$30]
009FB21B   BA06000000             mov     edx, $00000006

* Reference to: DB.Proc_0097CB48
|
009FB220   E82319F8FF             call    0097CB48
009FB225   8D55D0                 lea     edx, [ebp-$30]
009FB228   8B08                   mov     ecx, [eax]
009FB22A   FF5160                 call    dword ptr [ecx+$60]
009FB22D   8B45D0                 mov     eax, [ebp-$30]

* Possible String Reference to: '32'
|
009FB230   BA60B79F00             mov     edx, $009FB760

* Reference to: System.Proc_00904C30
|
009FB235   E8F699F0FF             call    00904C30
009FB23A   7513                   jnz     009FB24F

* Reference to Top100Form
|
009FB23C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.Classla : TLabel
|
009FB23F   8B8028030000           mov     eax, [eax+$0328]

* Possible String Reference to: 'Elf'
|
009FB245   BA6CB79F00             mov     edx, $009FB76C

* Reference to: Controls.Proc_0094B208
|
009FB24A   E8B9FFF4FF             call    0094B208
009FB24F   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB251   8B4060                 mov     eax, [eax+$60]
009FB254   8B4030                 mov     eax, [eax+$30]
009FB257   BA06000000             mov     edx, $00000006

* Reference to: DB.Proc_0097CB48
|
009FB25C   E8E718F8FF             call    0097CB48
009FB261   8D55CC                 lea     edx, [ebp-$34]
009FB264   8B08                   mov     ecx, [eax]
009FB266   FF5160                 call    dword ptr [ecx+$60]
009FB269   8B45CC                 mov     eax, [ebp-$34]

* Possible String Reference to: '33'
|
009FB26C   BA78B79F00             mov     edx, $009FB778

* Reference to: System.Proc_00904C30
|
009FB271   E8BA99F0FF             call    00904C30
009FB276   7513                   jnz     009FB28B

* Reference to Top100Form
|
009FB278   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.Classla : TLabel
|
009FB27B   8B8028030000           mov     eax, [eax+$0328]

* Possible String Reference to: 'Muse Elf'
|
009FB281   BA84B79F00             mov     edx, $009FB784

* Reference to: Controls.Proc_0094B208
|
009FB286   E87DFFF4FF             call    0094B208
009FB28B   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB28D   8B4060                 mov     eax, [eax+$60]
009FB290   8B4030                 mov     eax, [eax+$30]
009FB293   BA06000000             mov     edx, $00000006

* Reference to: DB.Proc_0097CB48
|
009FB298   E8AB18F8FF             call    0097CB48
009FB29D   8D55C8                 lea     edx, [ebp-$38]
009FB2A0   8B08                   mov     ecx, [eax]
009FB2A2   FF5160                 call    dword ptr [ecx+$60]
009FB2A5   8B45C8                 mov     eax, [ebp-$38]

* Possible String Reference to: '48'
|
009FB2A8   BA98B79F00             mov     edx, $009FB798

* Reference to: System.Proc_00904C30
|
009FB2AD   E87E99F0FF             call    00904C30
009FB2B2   7513                   jnz     009FB2C7

* Reference to Top100Form
|
009FB2B4   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.Classla : TLabel
|
009FB2B7   8B8028030000           mov     eax, [eax+$0328]

* Possible String Reference to: 'Magic Gladiator'
|
009FB2BD   BAA4B79F00             mov     edx, $009FB7A4

* Reference to: Controls.Proc_0094B208
|
009FB2C2   E841FFF4FF             call    0094B208
009FB2C7   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB2C9   8B4060                 mov     eax, [eax+$60]
009FB2CC   8B4030                 mov     eax, [eax+$30]
009FB2CF   BA06000000             mov     edx, $00000006

* Reference to: DB.Proc_0097CB48
|
009FB2D4   E86F18F8FF             call    0097CB48
009FB2D9   8D55C4                 lea     edx, [ebp-$3C]
009FB2DC   8B08                   mov     ecx, [eax]
009FB2DE   FF5160                 call    dword ptr [ecx+$60]
009FB2E1   8B45C4                 mov     eax, [ebp-$3C]

* Possible String Reference to: '64'
|
009FB2E4   BABCB79F00             mov     edx, $009FB7BC

* Reference to: System.Proc_00904C30
|
009FB2E9   E84299F0FF             call    00904C30
009FB2EE   7513                   jnz     009FB303

* Reference to Top100Form
|
009FB2F0   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.Classla : TLabel
|
009FB2F3   8B8028030000           mov     eax, [eax+$0328]

* Possible String Reference to: 'Dark Lord'
|
009FB2F9   BAC8B79F00             mov     edx, $009FB7C8

* Reference to: Controls.Proc_0094B208
|
009FB2FE   E805FFF4FF             call    0094B208
009FB303   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB305   8B4060                 mov     eax, [eax+$60]
009FB308   8B4030                 mov     eax, [eax+$30]
009FB30B   BA05000000             mov     edx, $00000005

* Reference to: DB.Proc_0097CB48
|
009FB310   E83318F8FF             call    0097CB48
009FB315   8D55C0                 lea     edx, [ebp-$40]
009FB318   8B08                   mov     ecx, [eax]
009FB31A   FF5160                 call    dword ptr [ecx+$60]
009FB31D   8B45C0                 mov     eax, [ebp-$40]
009FB320   BADCB79F00             mov     edx, $009FB7DC

* Reference to: System.Proc_00904C30
|
009FB325   E80699F0FF             call    00904C30
009FB32A   7513                   jnz     009FB33F

* Reference to Top100Form
|
009FB32C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.otherla : TLabel
|
009FB32F   8B8020030000           mov     eax, [eax+$0320]

* Possible String Reference to: 'Game Master'
|
009FB335   BAE8B79F00             mov     edx, $009FB7E8

* Reference to: Controls.Proc_0094B208
|
009FB33A   E8C9FEF4FF             call    0094B208
009FB33F   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB341   8B4060                 mov     eax, [eax+$60]
009FB344   8B4030                 mov     eax, [eax+$30]
009FB347   BA05000000             mov     edx, $00000005

* Reference to: DB.Proc_0097CB48
|
009FB34C   E8F717F8FF             call    0097CB48
009FB351   8D55BC                 lea     edx, [ebp-$44]
009FB354   8B08                   mov     ecx, [eax]
009FB356   FF5160                 call    dword ptr [ecx+$60]
009FB359   8B45BC                 mov     eax, [ebp-$44]
009FB35C   BAFCB79F00             mov     edx, $009FB7FC

* Reference to: System.Proc_00904C30
|
009FB361   E8CA98F0FF             call    00904C30
009FB366   7513                   jnz     009FB37B

* Reference to Top100Form
|
009FB368   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.otherla : TLabel
|
009FB36B   8B8020030000           mov     eax, [eax+$0320]

* Possible String Reference to: 'Game Master'
|
009FB371   BAE8B79F00             mov     edx, $009FB7E8

* Reference to: Controls.Proc_0094B208
|
009FB376   E88DFEF4FF             call    0094B208
009FB37B   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB37D   8B4060                 mov     eax, [eax+$60]
009FB380   8B4030                 mov     eax, [eax+$30]
009FB383   BA05000000             mov     edx, $00000005

* Reference to: DB.Proc_0097CB48
|
009FB388   E8BB17F8FF             call    0097CB48
009FB38D   8D55B8                 lea     edx, [ebp-$48]
009FB390   8B08                   mov     ecx, [eax]
009FB392   FF5160                 call    dword ptr [ecx+$60]
009FB395   8B45B8                 mov     eax, [ebp-$48]
009FB398   BAFCB69F00             mov     edx, $009FB6FC

* Reference to: System.Proc_00904C30
|
009FB39D   E88E98F0FF             call    00904C30
009FB3A2   7513                   jnz     009FB3B7

* Reference to Top100Form
|
009FB3A4   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.otherla : TLabel
|
009FB3A7   8B8020030000           mov     eax, [eax+$0320]

* Possible String Reference to: 'Banned'
|
009FB3AD   BA08B89F00             mov     edx, $009FB808

* Reference to: Controls.Proc_0094B208
|
009FB3B2   E851FEF4FF             call    0094B208
009FB3B7   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB3B9   8B4060                 mov     eax, [eax+$60]
009FB3BC   8B4030                 mov     eax, [eax+$30]
009FB3BF   BA05000000             mov     edx, $00000005

* Reference to: DB.Proc_0097CB48
|
009FB3C4   E87F17F8FF             call    0097CB48
009FB3C9   8D55B4                 lea     edx, [ebp-$4C]
009FB3CC   8B08                   mov     ecx, [eax]
009FB3CE   FF5160                 call    dword ptr [ecx+$60]
009FB3D1   8B45B4                 mov     eax, [ebp-$4C]
009FB3D4   BADCB69F00             mov     edx, $009FB6DC

* Reference to: System.Proc_00904C30
|
009FB3D9   E85298F0FF             call    00904C30
009FB3DE   7513                   jnz     009FB3F3

* Reference to Top100Form
|
009FB3E0   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.otherla : TLabel
|
009FB3E3   8B8020030000           mov     eax, [eax+$0320]

* Possible String Reference to: 'None'
|
009FB3E9   BA18B89F00             mov     edx, $009FB818

* Reference to: Controls.Proc_0094B208
|
009FB3EE   E815FEF4FF             call    0094B208
009FB3F3   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB3F5   8B4060                 mov     eax, [eax+$60]
009FB3F8   8B4030                 mov     eax, [eax+$30]
009FB3FB   BA05000000             mov     edx, $00000005

* Reference to: DB.Proc_0097CB48
|
009FB400   E84317F8FF             call    0097CB48
009FB405   8D55B0                 lea     edx, [ebp-$50]
009FB408   8B08                   mov     ecx, [eax]
009FB40A   FF5160                 call    dword ptr [ecx+$60]
009FB40D   8B45B0                 mov     eax, [ebp-$50]

* Possible String Reference to: '<NULL>'
|
009FB410   BA28B89F00             mov     edx, $009FB828

* Reference to: System.Proc_00904C30
|
009FB415   E81698F0FF             call    00904C30
009FB41A   7513                   jnz     009FB42F

* Reference to Top100Form
|
009FB41C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.otherla : TLabel
|
009FB41F   8B8020030000           mov     eax, [eax+$0320]

* Possible String Reference to: 'None'
|
009FB425   BA18B89F00             mov     edx, $009FB818

* Reference to: Controls.Proc_0094B208
|
009FB42A   E8D9FDF4FF             call    0094B208
009FB42F   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB431   8B4060                 mov     eax, [eax+$60]
009FB434   8B4030                 mov     eax, [eax+$30]
009FB437   BA01000000             mov     edx, $00000001

* Reference to: DB.Proc_0097CB48
|
009FB43C   E80717F8FF             call    0097CB48
009FB441   8D55AC                 lea     edx, [ebp-$54]
009FB444   8B08                   mov     ecx, [eax]
009FB446   FF5160                 call    dword ptr [ecx+$60]
009FB449   8B55AC                 mov     edx, [ebp-$54]

* Reference to Top100Form
|
009FB44C   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.strengla : TLabel
|
009FB44F   8B8000030000           mov     eax, [eax+$0300]

* Reference to: Controls.Proc_0094B208
|
009FB455   E8AEFDF4FF             call    0094B208
009FB45A   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB45C   8B4060                 mov     eax, [eax+$60]
009FB45F   8B4030                 mov     eax, [eax+$30]
009FB462   BA02000000             mov     edx, $00000002

* Reference to: DB.Proc_0097CB48
|
009FB467   E8DC16F8FF             call    0097CB48
009FB46C   8D55A8                 lea     edx, [ebp-$58]
009FB46F   8B08                   mov     ecx, [eax]
009FB471   FF5160                 call    dword ptr [ecx+$60]
009FB474   8B55A8                 mov     edx, [ebp-$58]

* Reference to Top100Form
|
009FB477   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.vitalla : TLabel
|
009FB47A   8B8010030000           mov     eax, [eax+$0310]

* Reference to: Controls.Proc_0094B208
|
009FB480   E883FDF4FF             call    0094B208
009FB485   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB487   8B4060                 mov     eax, [eax+$60]
009FB48A   8B4030                 mov     eax, [eax+$30]
009FB48D   BA03000000             mov     edx, $00000003

* Reference to: DB.Proc_0097CB48
|
009FB492   E8B116F8FF             call    0097CB48
009FB497   8D55A4                 lea     edx, [ebp-$5C]
009FB49A   8B08                   mov     ecx, [eax]
009FB49C   FF5160                 call    dword ptr [ecx+$60]
009FB49F   8B55A4                 mov     edx, [ebp-$5C]

* Reference to Top100Form
|
009FB4A2   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.agilla : TLabel
|
009FB4A5   8B8008030000           mov     eax, [eax+$0308]

* Reference to: Controls.Proc_0094B208
|
009FB4AB   E858FDF4FF             call    0094B208
009FB4B0   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB4B2   8B4060                 mov     eax, [eax+$60]
009FB4B5   8B4030                 mov     eax, [eax+$30]
009FB4B8   BA04000000             mov     edx, $00000004

* Reference to: DB.Proc_0097CB48
|
009FB4BD   E88616F8FF             call    0097CB48
009FB4C2   8D55A0                 lea     edx, [ebp-$60]
009FB4C5   8B08                   mov     ecx, [eax]
009FB4C7   FF5160                 call    dword ptr [ecx+$60]
009FB4CA   8B55A0                 mov     edx, [ebp-$60]

* Reference to Top100Form
|
009FB4CD   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.energyla : TLabel
|
009FB4D0   8B8018030000           mov     eax, [eax+$0318]

* Reference to: Controls.Proc_0094B208
|
009FB4D6   E82DFDF4FF             call    0094B208
009FB4DB   807DFB00               cmp     byte ptr [ebp-$05], $00
009FB4DF   742D                   jz      009FB50E
009FB4E1   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB4E3   8B4060                 mov     eax, [eax+$60]
009FB4E6   8B4030                 mov     eax, [eax+$30]
009FB4E9   BA07000000             mov     edx, $00000007

* Reference to: DB.Proc_0097CB48
|
009FB4EE   E85516F8FF             call    0097CB48
009FB4F3   8D559C                 lea     edx, [ebp-$64]
009FB4F6   8B08                   mov     ecx, [eax]
009FB4F8   FF5160                 call    dword ptr [ecx+$60]
009FB4FB   8B559C                 mov     edx, [ebp-$64]

* Reference to Top100Form
|
009FB4FE   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.Label70 : TLabel
|
009FB501   8B8030030000           mov     eax, [eax+$0330]

* Reference to: Controls.Proc_0094B208
|
009FB507   E8FCFCF4FF             call    0094B208
009FB50C   EB13                   jmp     009FB521

* Reference to Top100Form
|
009FB50E   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.Label70 : TLabel
|
009FB511   8B8030030000           mov     eax, [eax+$0330]

* Possible String Reference to: 'Not avilable'
|
009FB517   BA38B89F00             mov     edx, $009FB838

* Reference to: Controls.Proc_0094B208
|
009FB51C   E8E7FCF4FF             call    0094B208
009FB521   8B03                   mov     eax, [ebx]

* Reference to field TLabel.OFFS_0060
|
009FB523   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_00988BD0
|
009FB526   E8A5D6F8FF             call    00988BD0
009FB52B   33C0                   xor     eax, eax
009FB52D   5A                     pop     edx
009FB52E   59                     pop     ecx
009FB52F   59                     pop     ecx
009FB530   648910                 mov     fs:[eax], edx
009FB533   EB2D                   jmp     009FB562
009FB535   E98E89F0FF             jmp     00903EC8

* Reference to Top100Form
|
009FB53A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.reschecker : TCheckBox
|
009FB53D   8B8038030000           mov     eax, [eax+$0338]
009FB543   33D2                   xor     edx, edx
009FB545   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_64
|
009FB547   FF5164                 call    dword ptr [ecx+$64]

* Reference to Top100Form
|
009FB54A   8B45FC                 mov     eax, [ebp-$04]

* Reference to control TTop100Form.reschecker : TCheckBox
|
009FB54D   8B8038030000           mov     eax, [eax+$0338]
009FB553   33D2                   xor     edx, edx
009FB555   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00C8
|
009FB557   FF91C8000000           call    dword ptr [ecx+$00C8]

* Reference to: System.Proc_009042F4
|
009FB55D   E8928DF0FF             call    009042F4

****** END
|
009FB562   33C0                   xor     eax, eax
009FB564   5A                     pop     edx
009FB565   59                     pop     ecx
009FB566   59                     pop     ecx
009FB567   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '_^[‹å]Ã'
|
009FB56A   6884B59F00             push    $009FB584
009FB56F   8D459C                 lea     eax, [ebp-$64]
009FB572   BA17000000             mov     edx, $00000017

* Reference to: System.Proc_00904858
|
009FB577   E8DC92F0FF             call    00904858
009FB57C   C3                     ret

009FB57D   E9FA8BF0FF             jmp     0090417C
009FB582   EBEB                   jmp     009FB56F

****** END
|
009FB584   5F                     pop     edi
009FB585   5E                     pop     esi
009FB586   5B                     pop     ebx
009FB587   8BE5                   mov     esp, ebp
009FB589   5D                     pop     ebp
009FB58A   C3                     ret

*)
end;

procedure TTop100Form.FormKeyPress(Sender : TObject);
begin
(*
009FB848   80391B                 cmp     byte ptr [ecx], $1B
009FB84B   7505                   jnz     009FB852

* Reference to : TApplication._PROC_0096912C()
|
009FB84D   E8DAD8F6FF             call    0096912C
009FB852   C3                     ret

*)
end;

procedure TTop100Form.addToRememberedClick(Sender : TObject);
begin
(*
009FB854   55                     push    ebp
009FB855   8BEC                   mov     ebp, esp
009FB857   6A00                   push    $00
009FB859   53                     push    ebx
009FB85A   56                     push    esi
009FB85B   8BD8                   mov     ebx, eax
009FB85D   33C0                   xor     eax, eax
009FB85F   55                     push    ebp

* Possible String Reference to: 'éÇˆðÿëð^[Y]Ãè³ôÿÿÃ‹ÀU‹ì3ÀUhé¸Ÿ'
|
009FB860   68B0B89F00             push    $009FB8B0
009FB865   64FF30                 push    dword ptr fs:[eax]
009FB868   648920                 mov     fs:[eax], esp

* Reference to control TTop100Form.toplist : TListBox
|
009FB86B   8BB334030000           mov     esi, [ebx+$0334]
009FB871   8BC6                   mov     eax, esi
009FB873   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00C8
|
009FB875   FF92C8000000           call    dword ptr [edx+$00C8]
009FB87B   8BD0                   mov     edx, eax
009FB87D   8D4DFC                 lea     ecx, [ebp-$04]

* Reference to field TListBox.OFFS_0218
|
009FB880   8B8618020000           mov     eax, [esi+$0218]
009FB886   8B18                   mov     ebx, [eax]
009FB888   FF530C                 call    dword ptr [ebx+$0C]
009FB88B   8B55FC                 mov     edx, [ebp-$04]

* Reference to TCharacterMarkForm instance
|
009FB88E   A138FEA000             mov     eax, dword ptr [$00A0FE38]
009FB893   8B00                   mov     eax, [eax]

* Reference to : TCharacterMarkForm._PROC_009FA7F4()
|
009FB895   E85AEFFFFF             call    009FA7F4
009FB89A   33C0                   xor     eax, eax
009FB89C   5A                     pop     edx
009FB89D   59                     pop     ecx
009FB89E   59                     pop     ecx
009FB89F   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '^[Y]Ãè³ôÿÿÃ‹ÀU‹ì3ÀUhé¸Ÿ'
|
009FB8A2   68B7B89F00             push    $009FB8B7
009FB8A7   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009FB8AA   E8858FF0FF             call    00904834
009FB8AF   C3                     ret

009FB8B0   E9C788F0FF             jmp     0090417C
009FB8B5   EBF0                   jmp     009FB8A7

****** END
|
009FB8B7   5E                     pop     esi
009FB8B8   5B                     pop     ebx
009FB8B9   59                     pop     ecx
009FB8BA   5D                     pop     ebp
009FB8BB   C3                     ret

*)
end;

procedure TTop100Form.BitBtn1Click(Sender : TObject);
begin
(*

* Reference to : TTop100Form._PROC_009FAD74()
|
009FB8BC   E8B3F4FFFF             call    009FAD74
009FB8C1   C3                     ret

*)
end;

procedure TTop100Form._PROC_009FAD74(Sender : TObject);
begin
(*
009FAD74   55                     push    ebp
009FAD75   8BEC                   mov     ebp, esp
009FAD77   6A00                   push    $00
009FAD79   53                     push    ebx
009FAD7A   56                     push    esi
009FAD7B   57                     push    edi
009FAD7C   8BF0                   mov     esi, eax
009FAD7E   33C0                   xor     eax, eax
009FAD80   55                     push    ebp

* Possible String Reference to: 'é›’ðÿëð‹Ã_^[Y]Ã'
|
009FAD81   68DCAE9F00             push    $009FAEDC
009FAD86   64FF30                 push    dword ptr fs:[eax]
009FAD89   648920                 mov     fs:[eax], esp

* Reference to control TTop100Form.addToRemembered : TSpeedButton
|
009FAD8C   8B863C030000           mov     eax, [esi+$033C]
009FAD92   33D2                   xor     edx, edx
009FAD94   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TSpeedButton.OFFS_64
|
009FAD96   FF5164                 call    dword ptr [ecx+$64]

* Reference to: top100Unit.Proc_009FAD50
|
009FAD99   E8B2FFFFFF             call    009FAD50
009FAD9E   84C0                   test    al, al
009FADA0   741D                   jz      009FADBF

* Reference to control TTop100Form.reschecker : TCheckBox
|
009FADA2   8B8638030000           mov     eax, [esi+$0338]
009FADA8   33D2                   xor     edx, edx
009FADAA   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_64
|
009FADAC   FF5164                 call    dword ptr [ecx+$64]

* Reference to control TTop100Form.reschecker : TCheckBox
|
009FADAF   8B8638030000           mov     eax, [esi+$0338]
009FADB5   33D2                   xor     edx, edx
009FADB7   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TCheckBox.OFFS_00C8
|
009FADB9   FF91C8000000           call    dword ptr [ecx+$00C8]
009FADBF   33D2                   xor     edx, edx
009FADC1   55                     push    ebp
009FADC2   68BAAE9F00             push    $009FAEBA
009FADC7   64FF32                 push    dword ptr fs:[edx]
009FADCA   648922                 mov     fs:[edx], esp

* Reference to control TTop100Form.toplist : TListBox
|
009FADCD   8B8634030000           mov     eax, [esi+$0334]
009FADD3   8B10                   mov     edx, [eax]

* Possible reference to virtual method TListBox.OFFS_00D4
|
009FADD5   FF92D4000000           call    dword ptr [edx+$00D4]

* Reference to TDataModule_Main instance
|
009FADDB   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FADE0   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FADE2   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FADE5   E8D2B7F8FF             call    009865BC

* Reference to TDataModule_Main instance
|
009FADEA   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FADEF   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FADF1   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FADF4   E8BFF5F9FF             call    0099A3B8
009FADF9   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_44
|
009FADFB   FF5244                 call    dword ptr [edx+$44]

* Reference to TDataModule_Main instance
|
009FADFE   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FAE03   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FAE05   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FAE08   E8ABF5F9FF             call    0099A3B8

* Possible String Reference to: 'select top 100 Name from Character 
|                                order by cLevel DESC '
|
009FAE0D   BAF4AE9F00             mov     edx, $009FAEF4
009FAE12   8B08                   mov     ecx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_38
|
009FAE14   FF5138                 call    dword ptr [ecx+$38]

* Reference to TDataModule_Main instance
|
009FAE17   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FAE1C   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FAE1E   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865B0
|
009FAE21   E88AB7F8FF             call    009865B0

* Reference to TDataModule_Main instance
|
009FAE26   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FAE2B   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FAE2D   8B4060                 mov     eax, [eax+$60]
009FAE30   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_014C
|
009FAE32   FF924C010000           call    dword ptr [edx+$014C]
009FAE38   8BD8                   mov     ebx, eax
009FAE3A   83EB01                 sub     ebx, +$01
009FAE3D   7105                   jno     009FAE44

* Reference to: System.Proc_00903928
|
009FAE3F   E8E48AF0FF             call    00903928
009FAE44   85DB                   test    ebx, ebx
009FAE46   7C43                   jl      009FAE8B
009FAE48   43                     inc     ebx

* Reference to TDataModule_Main instance
|
009FAE49   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FAE4E   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FAE50   8B4060                 mov     eax, [eax+$60]

* Reference to field TADOQuery.OFFS_0030
|
009FAE53   8B4030                 mov     eax, [eax+$30]
009FAE56   33D2                   xor     edx, edx

* Reference to: DB.Proc_0097CB48
|
009FAE58   E8EB1CF8FF             call    0097CB48
009FAE5D   8D55FC                 lea     edx, [ebp-$04]
009FAE60   8B08                   mov     ecx, [eax]
009FAE62   FF5160                 call    dword ptr [ecx+$60]
009FAE65   8B55FC                 mov     edx, [ebp-$04]

* Reference to control TTop100Form.toplist : TListBox
|
009FAE68   8B8634030000           mov     eax, [esi+$0334]

* Reference to field TListBox.OFFS_0218
|
009FAE6E   8B8018020000           mov     eax, [eax+$0218]
009FAE74   8B08                   mov     ecx, [eax]
009FAE76   FF5138                 call    dword ptr [ecx+$38]

* Reference to TDataModule_Main instance
|
009FAE79   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FAE7E   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FAE80   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_00988BD0
|
009FAE83   E848DDF8FF             call    00988BD0
009FAE88   4B                     dec     ebx
009FAE89   75BE                   jnz     009FAE49

* Reference to TDataModule_Main instance
|
009FAE8B   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FAE90   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FAE92   8B4060                 mov     eax, [eax+$60]

* Reference to: DB.Proc_009865BC
|
009FAE95   E822B7F8FF             call    009865BC

* Reference to TDataModule_Main instance
|
009FAE9A   A18CFBA000             mov     eax, dword ptr [$00A0FB8C]
009FAE9F   8B00                   mov     eax, [eax]

* Reference to control TDataModule_Main.Muquery : TADOQuery
|
009FAEA1   8B4060                 mov     eax, [eax+$60]

* Reference to: ADODB.Proc_0099A3B8
|
009FAEA4   E80FF5F9FF             call    0099A3B8
009FAEA9   8B10                   mov     edx, [eax]

* Possible reference to virtual method TADOQuery.OFFS_44
|
009FAEAB   FF5244                 call    dword ptr [edx+$44]
009FAEAE   B301                   mov     bl, $01
009FAEB0   33C0                   xor     eax, eax
009FAEB2   5A                     pop     edx
009FAEB3   59                     pop     ecx
009FAEB4   59                     pop     ecx
009FAEB5   648910                 mov     fs:[eax], edx
009FAEB8   EB0C                   jmp     009FAEC6
009FAEBA   E90990F0FF             jmp     00903EC8
009FAEBF   33DB                   xor     ebx, ebx

* Reference to: System.Proc_009042F4
|
009FAEC1   E82E94F0FF             call    009042F4

****** END
|
009FAEC6   33C0                   xor     eax, eax
009FAEC8   5A                     pop     edx
009FAEC9   59                     pop     ecx
009FAECA   59                     pop     ecx
009FAECB   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: '‹Ã_^[Y]Ã'
|
009FAECE   68E3AE9F00             push    $009FAEE3
009FAED3   8D45FC                 lea     eax, [ebp-$04]

* Reference to: System.Proc_00904834
|
009FAED6   E85999F0FF             call    00904834
009FAEDB   C3                     ret

009FAEDC   E99B92F0FF             jmp     0090417C
009FAEE1   EBF0                   jmp     009FAED3

****** END
|
009FAEE3   8BC3                   mov     eax, ebx
009FAEE5   5F                     pop     edi
009FAEE6   5E                     pop     esi
009FAEE7   5B                     pop     ebx
009FAEE8   59                     pop     ecx
009FAEE9   5D                     pop     ebp
009FAEEA   C3                     ret

*)
end;

procedure TTop100Form._PROC_009FB82B(Sender : TObject);
begin
(*
009FB82B   4C                     dec     esp
009FB82C   4C                     dec     esp
009FB82D   3E0000                 add     ds:[eax], al
009FB830   FFFF                   DB  $FF, $FF  //      
009FB832   FFFF                   DB  $FF, $FF  //      
009FB834   0C00                   or      al, $00
009FB836   0000                   add     [eax], al

*)
end;

procedure TTop100Form._PROC_009FB8C4(Sender : TObject);
begin
(*
009FB8C4   55                     push    ebp
009FB8C5   8BEC                   mov     ebp, esp
009FB8C7   33C0                   xor     eax, eax
009FB8C9   55                     push    ebp

* Possible String Reference to: 'éŽˆðÿëø]Ã‹Àƒ-È ¡'
|
009FB8CA   68E9B89F00             push    $009FB8E9
009FB8CF   64FF30                 push    dword ptr fs:[eax]
009FB8D2   648920                 mov     fs:[eax], esp
009FB8D5   FF05C820A100           inc     dword ptr [$00A120C8]
009FB8DB   33C0                   xor     eax, eax
009FB8DD   5A                     pop     edx
009FB8DE   59                     pop     ecx
009FB8DF   59                     pop     ecx
009FB8E0   648910                 mov     fs:[eax], edx

****** FINALLY
|

* Possible String Reference to: ']Ã‹Àƒ-È ¡'
|
009FB8E3   68F0B89F00             push    $009FB8F0
009FB8E8   C3                     ret

009FB8E9   E98E88F0FF             jmp     0090417C
009FB8EE   EBF8                   jmp     009FB8E8

****** END
|
009FB8F0   5D                     pop     ebp
009FB8F1   C3                     ret

*)
end;

procedure TTop100Form._PROC_009FB8F4(Sender : TObject);
begin
(*
009FB8F4   832DC820A10001         sub     dword ptr [$00A120C8], +$01
009FB8FB   C3                     ret

*)
end;

end.